"""The bridge lab: N river crossings on one template map, for the user's QA rounds (review/qa/README.md).

Each plot is a small piece of country: two clearings either side of a stream, a road between them planned with the
crossing (Land.plan_crossing, as the story maps do), the stream dug square across the road on a straight stretch, and
the crossing laid by the kit's Waterworks: a rope bridge (Westwood's stream bridges), a plank deck (Con05A) or a ford.
The plots vary on a fixed schedule: the crossing kind, the road's axis on screen, the stream's width and water, the
road's surface and the forest.

    py review/qa/bridgelab.py [--n 20] [--seed 1] [--out DIR]

Writes DIR/map/BridgeLab.map, DIR/variants.json (each crossing's label, kind, axis, width, water, forest and its centre
in world px) and, with --render, DIR/renders/BR-NN.png (the editor's full render cropped round each crossing, labelled).
Never installs a map or launches the game: the only program it starts is the map editor's headless renderer.
"""
import argparse, json, math, os, random, sys, zlib

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
for p in (os.path.join(REPO, "validate"), os.path.join(REPO, "mapgen"), os.path.join(REPO, "rules")):
    if p not in sys.path: sys.path.insert(0, p)

from nox import Spec, SOLO                                                  # noqa: E402
from kit.layout import Land, square_px, cell_square, tile_square           # noqa: E402
from kit.water import Waterworks, px_of_uv                                 # noqa: E402
from kit.vegetation import Planter, FORESTS, TOWN_PLANTING                 # noqa: E402

# (kind, deck width) on a fixed turn: Westwood's stream bridges are mostly rope-bridge kits
KINDS = [("rope", 0), ("plank", 2), ("rope", 0), ("ford", 3), ("plank", 3), ("rope", 0), ("plank", 2), ("ford", 4),
         ("rope", 0), ("plank", 3)]
WIDTHS = [2.2, 2.8, 3.4, 2.0, 3.0, 4.0, 2.4, 2.6, 3.6, 2.2, 3.2]
WATERS = ["clear", "clear", "clear", "swamp", "clear", "clear", "swamp", "clear"]
ROADS = ["DirtDark2", "DirtDark2", "RoughCobble", "DirtLight2", "DirtDark2"]
FOREST_TURN = ["deciduous", "conifer", "oak", "aspen", "pine", "dusk", "ancient"]
COLS = [30, 76, 122, 168, 214]
ROWS = [34, 88, 142, 196]


def seed_of(*parts):
    return zlib.crc32("|".join(str(p) for p in parts).encode("utf-8"))


def uv(X, Y):
    return (X + Y, X - Y)


def generate(n=20, seed=1, out_dir=None, name="BridgeLab", log=print):
    rng = random.Random(seed_of("bridgelab", seed))
    m = Spec(name, summary="Bridge lab", description="Bridge lab: river crossings for QA. Generated by Claude.",
             author="vdystopia (generated by Claude)", version="1", date="2026", type=SOLO, minPlayers=1, maxPlayers=1)
    m.d["nxz"] = False
    m.d["ambient"] = [150, 146, 120]
    m.loot = False
    land = Land(rng, u_range=(8, 504), v_range=(-250, 250))
    plots = []
    for k in range(n):
        X, Y = COLS[k % len(COLS)], ROWS[(k // len(COLS)) % len(ROWS)]
        prng = random.Random(seed_of("bridgelab", seed, k))
        kind, deck = KINDS[k % len(KINDS)]
        axis = "u" if (k + seed) % 2 == 0 else "v"
        half = 10                                          # squares from the crossing to each clearing's centre
        if axis == "u": A, B = (X - half / 2, Y - half / 2), (X + half / 2, Y + half / 2)
        else: A, B = (X - half / 2, Y + half / 2), (X + half / 2, Y - half / 2)
        p = dict(k=k, label=f"BR-{k + 1:02d}", X=X, Y=Y, kind=kind, deck=deck, axis=axis,
                 width=WIDTHS[(k * 3 + seed) % len(WIDTHS)], water=WATERS[(k + seed) % len(WATERS)],
                 road=ROADS[(k + 2 * seed) % len(ROADS)], forest=FOREST_TURN[(k + seed) % len(FOREST_TURN)], rng=prng)
        if kind == "ford": p["width"] = min(p["width"], 3.0)     # a ford crosses a shallow stream
        if kind == "plank": p["width"] = min(p["width"], 3.0)    # a plank deck spans a narrow stream (Con05A)
        a_, b_ = f"b{k}a", f"b{k}b"
        land.area(a_, uv(*A), 2 * prng.uniform(6.5, 8.0), region=f"p{k}")
        land.area(b_, uv(*B), 2 * prng.uniform(6.5, 8.0), region=f"p{k}")
        land.link(a_, b_, 10, bend=0.05, road=True, pockets=(0, 0))
        p["areas"] = (a_, b_)
        plots.append(p)
    # the plots joined by forest paths (Land.carve keeps one connected piece of land): a spine below each row, each plot
    # joined to it from the clearing on the side away from its stream's lower tail, the rows joined at the west edge
    rows = sorted({p["Y"] for p in plots})
    for r, Y in enumerate(rows):
        land.area(f"sp{r}w", uv(8, Y + 27), 8, region="spine")
        prev = f"sp{r}w"
        for p in [p for p in plots if p["Y"] == Y]:
            nm = f"sp{p['k']}"
            land.area(nm, uv(p["X"], Y + 27), 8, region="spine")
            land.link(prev, nm, 7, bend=0.1, road=False, pockets=(0, 0))
            land.link(p["areas"][1 if p["axis"] == "u" else 0], nm, 7, bend=0.1, road=False, pockets=(0, 0))
            prev = nm
        if r: land.link(f"sp{r - 1}w", f"sp{r}w", 7, bend=0.1, road=False, pockets=(0, 0))
    for p in plots:
        cross = land.plan_crossing(*p["areas"], t=0.5, approach=6)
        C = cross["uv"]
        fu, fv = cross["flow"]
        L = 26                                            # uv: the stream runs on into the forest at both ends
        p["cross"] = cross
        p["stream"] = [(C[0] - L * fu + p["rng"].uniform(-3, 3) * fv, C[1] - L * fv + p["rng"].uniform(-3, 3) * fu),
                       (C[0] - 10 * fu, C[1] - 10 * fv), C, (C[0] + 10 * fu, C[1] + 10 * fv),
                       (C[0] + L * fu + p["rng"].uniform(-3, 3) * fv, C[1] + L * fv + p["rng"].uniform(-3, 3) * fu)]
        land.reserve_band(p["stream"], p["width"] / 2 + 1.5)
        # the stream's banks are open ground a little way up and down from the crossing
        land.area(f"b{p['k']}s", C, 2 * 6.0, region=f"p{p['k']}")
    land.blends(m)
    for p in plots:
        land.paint_roads(m, p["road"], width_squares=2.4, skip=land.reserved)
    land.carve(margin=3.0)
    land.assign_regions()
    land.open_links()
    by = {f"p{p['k']}": p for p in plots}
    land.apply(m, wall=lambda r: FORESTS[by[r]["forest"] if r in by else "deciduous"]["wall"], floor="GrassNorm")
    land.ground_variety(m, clear=3)
    ww = Waterworks(m, rng, inside=lambda x, y: m.floor.get((x, y), "").startswith(("Grass", "Dirt", "Rough")))
    for p in plots:
        C, cross = p["cross"]["uv"], p["cross"]
        body = ww.stream(p["stream"], width=p["width"], family=p["water"], wiggle=1.2, calm=[(C, 14)])
        if p["kind"] == "rope":
            span = round(p["width"] + 6)
            a_uv, b_uv = (((C[0] - span, C[1]), (C[0] + span, C[1])) if cross["axis"] == "u" else
                          ((C[0], C[1] + span), (C[0], C[1] - span)))
            res = ww.rope_bridge(a_uv, b_uv, kit=cross["kit"])
        elif p["kind"] == "plank":
            res = ww.plank_bridge(body, at=C, along=cross["axis"], deck_width=p["deck"])
        else:
            res = ww.ford(body, t=0.5, width=p["deck"])
        p["result"] = res["kind"] if res else None
        for t in body.tiles:
            if "Water" in m.floor.get(t, ""): land.water.add(cell_square(*t))
    ww.finish()
    keep = set()
    for p in plots:
        ci, cj = p["cross"]["centre"]
        keep |= {(int(ci) + a, int(cj) + b) for a in range(-4, 5) for b in range(-4, 5)}
    planter = Planter(m, rng, land, "deciduous", keep_clear=keep,
                      forest_of=lambda s: by[land.region_of(s)]["forest"] if land.region_of(s) in by else "deciduous",
                      settled=tuple(by))
    planter.plant_all(groves=0, profile=TOWN_PLANTING)
    planter.rock_piles(max(4, len(land.squares) // 1200))
    a0 = land.areas[plots[0]["areas"][0]]["c"]
    m.obj_px("PlayerStart", *px_of_uv(*a0))
    os.makedirs(out_dir, exist_ok=True)
    lines = m.build(out_dir, check=False)
    for l in lines:
        if l.startswith("ERROR"): log(l)
    variants = []
    for p in plots:
        x, y = px_of_uv(*p["cross"]["uv"])
        variants.append(dict(label=p["label"], kind=p["kind"], built=p["result"], deck=p["deck"], axis=p["axis"],
                             stream_width=p["width"], water=p["water"], road=p["road"], forest=p["forest"],
                             centre=[round(x), round(y)]))
    return dict(map=os.path.join(out_dir, name + ".map"), variants=variants)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=20)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--out", default=os.path.join(REPO, "review", "out", "qa", "bridges"))
    ap.add_argument("--render", action="store_true")
    a = ap.parse_args()
    res = generate(a.n, a.seed, os.path.join(a.out, "map"))
    with open(os.path.join(a.out, "variants.json"), "w", encoding="utf-8") as f:
        json.dump(res, f, indent=1)
    print(f"{len(res['variants'])} crossings: {res['map']}")
    if a.render:
        import qarender
        qarender.crop_labelled(res["map"], [(v["label"], v["centre"], describe(v)) for v in res["variants"]],
                               os.path.join(a.out, "renders"), window=(1000, 750))


def describe(v):
    k = {"rope": "rope bridge", "plank": f"plank deck {v['deck']} wide", "ford": f"ford {v['deck']} wide"}[v["kind"]]
    return f"{k} - {v['water']} stream {v['stream_width']} tiles - {v['road']} road - {v['forest']} wood"


if __name__ == "__main__":
    main()
