"""AshRoad: the road out of Emberhollow's caldera, where its Cinder Gate leads; the campaign's last stop for now. The
road climbs out of the ash to a lookout over the cooled lava fields: a waymark, a fire basin, a sign that closes the
third chapter.

    py mapgen/designs/ashroad.py [seed]
"""
import math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO
from kit.layout import Land, square_px
from kit.biome import Dresser
from kit.quests import QuestBook, A
from kit.story import StoryMap
from kit import camps

SEED = int(sys.argv[1]) if len(sys.argv) > 1 else 2
rng = random.Random(SEED)
NAME = "AshRoad"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "out", "ashroad")


def uv(X, Y):
    return (X + Y, X - Y)


m = Spec(NAME, summary="The Ash Road", description="[env:lava] The road out of Emberhollow's caldera to a lookout over "
         "the lava fields. Generated by Claude.", author="vdystopia (generated by Claude)", version="1", date="2026",
         type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
q = QuestBook(NAME)
land = Land(rng, u_range=(120, 400), v_range=(-120, 120))
land.area("gate", uv(130, 70), 16)
land.area("lookout", uv(126, 130), 28)
land.area("on", uv(140, 192), 14)
for a_, b_ in (("gate", "lookout"), ("lookout", "on")):
    land.link(a_, b_, 13, bend=0.25, road_material="CaveHardBrown")
d = Dresser(m, rng, land, "lava")
land.paint_roads(m, "CaveHardBrown", width_squares=2.4)
lc = land.areas["lookout"]["c"]
land.taken |= {s for s in land.squares if math.hypot(s[0] - lc[0] - 4, s[1] - lc[1]) <= 4}
land.carve(margin=4.0)
outcrops = land.thickets(14, size=(1.2, 2.4), clear=1)
land.open_links()
land.apply(m, wall=d.wall, floor=d.base)
d.cap_islands(outcrops)
d.ground()
sc = camps.Scene(m, rng, land, (lc[0] + 4, lc[1]))
sc.put("DunMirMileStone", *sc.at(0, 0))
for k in range(7):
    sc.put(rng.choice(("CaveRocksLarge", "CaveRocksMedium", "CaveRocksSmall")), *sc.at(1.1 + 0.3 * (k % 3), k * 0.9))
sc.put("DunMirFlameBasinLit", *sc.at(2.6, 2.4))
sc.put("Chest2", *sc.at(3.0, 4.2), items=[("Gold", {"Amount": 35}), "RedPotion", "BluePotion"])
road = min(land.roads, key=lambda s: math.hypot(s[0] - lc[0], s[1] - lc[1]))
camps.signpost(m, land, (road[0] - 1.5, road[1] + 1.5),
               q.text("THE ASH ROAD\nBehind you the vents breathe again and Emberhollow's gate stands open.\n\n"
                      "(The end of the third chapter. The road goes on.)", "Sign"))
d.vegetate(groves=1)
d.scatter_open(scale=0.4)
d.rim(scale=0.5)
d.lights(scale=1.0)
d.planter.rock_piles(3)
gc = land.areas["gate"]["c"]
m.obj_px("PlayerStart", *square_px(gc[0] + 0.5, gc[1] - 0.5))
StoryMap(m, rng, land, None).wild({"Imp": 3}, away_from=gc, min_away=8,
                                  per100=0.4, avoid=[(lc[0] + 4, lc[1])])
q.start([q.journal("I came out through the Cinder Gate onto the Ash Road. Emberhollow breathes easier behind me.", 1),
         A.print("The Ash Road.")])
m.scripts.update(q.files())

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    q.write_strings(OUT)
    lines = m.build(os.path.abspath(OUT))
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK", "SCRIPTS"))))
