"""Building lab: every building role of the kit (kit/identity.py BUILDINGS) at one scale, each on open ground,
generated by kit/building.py from its role's room program and furnished. The rooms are declared (BldLab.rooms.json) so
review/roomscore.py scores them; review/buildingscore.py scores the buildings themselves: size, shape, rooms against
Westwood's sizes for their kinds, doors, and whether every room can be reached.

    py mapgen/designs/buildinglab.py [scale] [seed]          scale 1.0 = Westwood's sizes, 1.25 the kit's default
"""
import json, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO, rect_tiles, rect_wall_cells
from kit.building import generate_building
from kit.identity import BUILDINGS
from kit.originality import furnish_original

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "mapgen", "out", "buildinglab")
FIELD = (112, 396, -98, 98)
STYLE_OF = {"log_cabin": "town", "stucco_house": "town", "cobble_house": "town", "stone_house": "town"}


def build(scale=1.25, seed=1):
    rng = random.Random(seed)
    m = Spec("BldLab", summary="Building lab", description=f"Every building role at scale {scale}. Generated by Claude.",
             author="vdystopia (generated by Claude)", version="1", date="2026", type=SOLO, minPlayers=1, maxPlayers=1)
    m.d["nxz"] = False
    m.d["ambient"] = [165, 160, 155]
    u0, u1, v0, v1 = FIELD
    for mat, prio in (("GrassNorm", 0), ("GrassSparse2", 1), ("GrassDense", 2), ("DirtDark2", 3), ("DirtHard", 4)):
        m.blending(mat, prio)                       # the buildings' aprons and paths blend into the grass (TreePlace's order)
    for x, y in rect_tiles(u0, u1, v0, v1): m.tile(x, y, "GrassNorm")
    for x, y in rect_wall_cells(u0, u1, v0, v1): m.wall(x, y, "BrickPlain")
    roles = list(BUILDINGS)
    occupied, built, rooms_out = set(), [], []
    u, v, row = u0 + 6, v0 + 6, 0
    for role in roles:
        r = BUILDINGS[role]
        w, h = r["size"]
        W, H = 2 * round(w * scale / 2), 2 * round(h * scale / 2)
        if v + H > v1 - 6: u, v, row = u + row + 8, v0 + 6, 0
        if u + W > u1 - 6:
            print(f"  no room left for {role}"); continue
        b = generate_building(m, rng, (u, v), (W, H), r["style"], program=[k for k, _ in r["rooms"]], occupied=occupied,
                              entrance_side="v_min", building_id=role, min_units=int(r.get("min_units", 0) * scale * scale))
        if b is None:
            print(f"  {role} did not fit"); v += H + 8; row = max(row, W); continue
        occupied |= b.cells
        built.append((role, b))
        v += H + 8
        row = max(row, W)
    for role, b in built:
        for room in b.rooms:
            furnish_original(m, room, kind=room.kind, rng=random.Random(rng.random()),
                             style=BUILDINGS[role].get("furnish") or STYLE_OF.get(b.style, "town"))
            xs = [x for x, _ in room.tiles]; ys = [y for _, y in room.tiles]
            rooms_out.append(dict(number=len(rooms_out) + 1, building=role, kind=room.kind, purpose=f"{role} at scale {scale}",
                                  tiles=len(room.tiles), box=[min(xs) - 1, min(ys) - 1, max(xs) + 3, max(ys) + 3],
                                  floor=sorted([x, y] for x, y in room.tiles)))
    m.obj("PlayerStart", u0 + 3, v0 + 3)
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "BldLab.rooms.json"), "w", encoding="utf-8") as f: json.dump(rooms_out, f, indent=1)
    meta = [dict(role=role, style=b.style, shape=b.shape, units=list(b.size_units), footprint=len(b.footprint),
                 rooms=[dict(kind=r.kind, tiles=len(r.tiles), doors=len(r.doors)) for r in b.rooms],
                 entrances=len(b.entrances), unreachable=list(b.unreachable),
                 box=[min(x for x, _ in b.footprint), min(y for _, y in b.footprint),
                      max(x for x, _ in b.footprint) + 2, max(y for _, y in b.footprint) + 2]) for role, b in built]
    with open(os.path.join(OUT, "BldLab.buildings.json"), "w", encoding="utf-8") as f: json.dump(meta, f, indent=1)
    lines = m.build(OUT)
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK"))))
    return os.path.join(OUT, "BldLab.map")


if __name__ == "__main__":
    build(float(sys.argv[1]) if len(sys.argv) > 1 else 1.25, int(sys.argv[2]) if len(sys.argv) > 2 else 1)
