"""Darkdelve: a cave system under the mountains (biome: cave; rules/BIOMES.md), built from the centre outwards.

At its heart a great cavern rings a black underground lake, mushrooms glowing on its shores. Tunnels lead out:
- east, a crystal grotto glowing blue;
- north, a spider warren of webbed tunnels strewn with bones;
- west, the ogres' keep: an old keep of dungeon stone they took over, their feasting hall, straw beds and hoard;
- south, an abandoned miners' camp, where the way in arrives.

Single player (Solo), one PlayerStart, no .nxz.
    py mapgen/designs/darkdelve.py [out_dir|-] [seed]
"""
import math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO
from kit.identity import MapIdentity, AreaIdentity
from kit.layout import Land, square_px, square_tile, N4
from kit.biome import Dresser

SEED = int(sys.argv[2]) if len(sys.argv) > 2 else 5
rng = random.Random(SEED)
HERE = os.path.dirname(os.path.abspath(__file__))

ID = MapIdentity(
    name="Darkdelve",
    theme="a cave system under the mountains: a great cavern rings a black underground lake, and tunnels lead out to "
          "a crystal grotto, a spider warren, the ogres' keep of dungeon stone and an abandoned miners' camp where the "
          "way in arrives",
    environment="cave", mood="dark, damp, echoing",
    areas=[AreaIdentity("heart", "the great cavern round the underground lake, mushrooms glowing on its shores",
                        landmark="the black lake"),
           AreaIdentity("grotto", "a crystal grotto glowing blue"),
           AreaIdentity("warren", "the spider warren: webbed tunnels strewn with bones"),
           AreaIdentity("den", "the ogres' keep: an old keep of dungeon stone they took over, their feasting hall, "
                               "straw beds and hoard, bones and the remains of meals about it"),
           AreaIdentity("camp", "the abandoned miners' camp where the way in arrives")])

m = Spec("Darkdelve", summary="Darkdelve - a cave system",
         description=f"[env:{ID.environment}] {ID.theme[0].upper() + ID.theme[1:]}. Generated by Claude.",
         author="vdystopia (generated by Claude)", version="0.2", date="Sunday, October 4 2026",
         type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False

# ---- 1. the plan: the caverns and the tunnels joining them (uv positions) ----------------------------------------
land = Land(rng, u_range=(20, 490), v_range=(-226, 226))
A = land.area
A("heart", (255, 0), 62, stretch=1.25, angle=0.3, roughness=0.18)
A("grotto", (315, 110), 34, roughness=0.3)
A("warren", (180, 100), 30, stretch=1.3, angle=-0.6, roughness=0.32)
A("warren_b", (110, 40), 22, roughness=0.32)
A("den", (195, -110), 38, roughness=0.28)
A("camp", (340, -90), 40, roughness=0.22)
A("gate", (405, -50), 18, roughness=0.2)
for k_, ar in land.areas.items():                     # every cavern stays inside the map with room for its walls
    x_, y_ = ar["c"][0] + ar["c"][1], ar["c"][0] - ar["c"][1]
    assert 12 + ar["r"] <= x_ <= 243 - ar["r"] and 12 + ar["r"] <= y_ <= 243 - ar["r"], (k_, x_, y_)
for a_, b_, w_ in (("heart", "grotto", 16), ("heart", "warren", 14), ("warren", "warren_b", 12), ("heart", "den", 16),
                   ("heart", "camp", 18), ("camp", "gate", 14), ("den", "warren_b", 12), ("grotto", "camp", 12)):
    land.link(a_, b_, w_, bend=0.35, road=False, pockets=(1, 2))

# ---- 2. the centre first: the underground lake --------------------------------------------------------------------
d = Dresser(m, rng, land, "cave")
lake = d.reserve_pool((255, 0), 30, stretch=1.35, angle=0.3, roughness=0.25)
# the ogres' keep (dungeon stone, as Westwood builds in its caves) in the west cavern, facing the lake
keep_b = d.structure("ogre_keep", "den", toward="heart", name="the ogres' keep")

# ---- 3. the land grows round what was placed; walls and floors ----------------------------------------------------
land.carve(margin=4.0)
land.apply(m, wall=d.wall, floor=d.base)
d.ground()
d.paint_pools()

# ---- 4. life: what stands in each cavern --------------------------------------------------------------------------
centre = {k: (land.areas[k]["c"][0], land.areas[k]["c"][1]) for k in land.areas}
in_area = lambda name, s: land._in_area((s[0] + 0.5, s[1] - 0.5), land.areas[name])
start = min(land.squares, key=lambda s: math.hypot(s[0] - centre["gate"][0], s[1] - centre["gate"][1]))
keep = {(start[0] + a, start[1] + b) for a in range(-3, 4) for b in range(-3, 4)}
d.taken |= keep

# the lake shore: patches of glowing mushrooms (Westwood's caves: 4 mushrooms per 100 open tiles, in patches)
shore = [s for s in land.squares if any((s[0] + a, s[1] + b) in lake for a in range(-3, 4) for b in range(-3, 4))]
d.clusters({"Mushroom3": 6, "Mushroom5": 3, "Mushroom1": 2, "Mushroom4": 2}, shore, 14, size=(4, 9), radius=1.6,
           gap=0.7, spacing=5.0)

# the crystal grotto: formations of blue crystals round a tall one, open floor between, cyan light over each
grotto = [s for s in land.squares if in_area("grotto", s)]
for ci, cj in d.clusters({"MineCrystal01": 3, "MineCrystal02": 3, "MineCrystal03": 2, "MineCrystal04": 2, "MineCrystal05": 3},
                         grotto, 9, size=(5, 9), radius=1.8, gap=0.8, spacing=6.0, core="MineCrystalUp02"):
    if rng.random() < 0.6:
        m.obj_px("ColorLight", *square_px(ci, cj), xfer=d._light_xfer((64, 160, 224), 200, 50))

# the spider warren: webs on every wall, bones in heaps
warren = [s for s in land.squares if in_area("warren", s) or in_area("warren_b", s)]
d._place({"SpiderWebNorthEast": 3, "SpiderWebEast": 3, "SpiderWebNorth": 3}, warren, 6, min_gap=1.3, wall_clear=0)
d.clusters({"LegBone": 3, "ArmBone": 2, "Skull": 2}, warren, 7, size=(3, 6), radius=1.4, gap=0.6, spacing=5.0)

# the ogre den: straw beds, the remains of meals, a stool by the fire
den = [s for s in land.squares if in_area("den", s) and s not in land.taken]
d.clusters({"Straw2": 3, "Straw1": 2}, den, 5, size=(2, 3), radius=1.2, gap=1.2, spacing=4.5)
d.clusters({"OgreHutMeat": 2, "LegBone": 2, "Skull": 1, "ArmBone": 1}, den, 4, size=(3, 5), radius=1.3, gap=0.7, spacing=5.0)

# the miners' camp: a few stacks of crates, tool barrels and carts left by the tunnel, beams for shoring
camp = [s for s in land.squares if in_area("camp", s) and s not in keep]
d.clusters({"DarkCrate1": 3, "DarkCrate2": 3, "Crate1": 1}, camp, 4, size=(3, 5), radius=1.5, gap=1.4, spacing=7.0)
d.clusters({"BarrelWithTools1": 2, "Barrel2": 2, "BarrelWithTools2": 1}, camp, 3, size=(2, 4), radius=1.2, gap=1.0, spacing=6.0)
d.clusters({"MineOreCart1": 2, "MineManaCart1": 1}, camp, 3, size=(1, 2), radius=1.5, gap=2.0, spacing=6.0)
d.clusters({"MineBeam1": 1, "MineBeam2": 1}, camp, 2, size=(2, 3), radius=1.5, gap=1.5, spacing=8.0)

# the keep's rooms, furnished as Westwood's ogre lairs are, and the ogres who hold it
furnished = d.furnish_structures()
n_keep = d.garrison()

# ---- 5. the biome's ground cover, wall plants, lights and creatures ------------------------------------------------
n_trees, n_small = d.vegetate(keep_clear=keep, groves=4)
d.scatter_open()
d.rim()
n_lights = d.lights()
n_mon = d.creatures(avoid=[start])
m.scripts.update(d.population.behaviours.files(m.d['name']))     # packs and skittish creatures (kit/behaviours)
x, y = square_px(start[0] + 0.5, start[1] - 0.5)
m.obj_px("PlayerStart", x, y)

if __name__ == "__main__" or True:
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "out")
    if out != "-":
        d.declare_rooms(os.path.join(os.path.abspath(out), m.d["name"] + ".rooms.json"))
        lines = m.build(out)
        print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK"))))
    print(f"land {len(land.squares)} squares | lake {len(lake)} | pillars {n_trees} small {n_small} | lights {n_lights} | "
          f"creatures {n_mon} | keep {'yes' if keep_b else 'NO'}: {', '.join(f'{k} {n}' for _, k, n in furnished)}, "
          f"keepers {n_keep}")
