"""DysCrypt: first generated map. A single small crypt room for 2-8 players.

Layout (u/v coordinates, room centre at u=256, v=0, walls 16 units out on each side):
- Mana obelisk in the centre.
- 8 player starts on a ring around it, near the walls.
- 4 weapons on the diagonals, potions around the obelisk.
- 3 crowns (red, blue, neutral) so King of the Realm works, like every stock arena map.
- 4 torch poles in the corners, plus moderate ambient light.
"""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec

U, V = 256, 0  # room centre
m = Spec("DysCrypt",
         summary="DysCrypt - small crypt arena",
         description="A single crypt chamber for quick 2-8 player fights. Generated by Claude.",
         author="vdystopia (generated by Claude)",
         version="0.1",
         date="Saturday, October 3 2026",
         type=0x34,           # arena: deathmatch, elimination, king of the realm
         minPlayers=2, maxPlayers=8)
m.d["ambient"] = [120, 112, 128]

m.room(U - 16, U + 16, V - 16, V + 16, wall="DungeonStone", floor="CryptFloor")

m.obj("Obelisk", U, V)

for du, dv in [(11, 0), (-11, 0), (0, 11), (0, -11), (8, 8), (-8, -8), (8, -8), (-8, 8)]:
    m.obj("PlayerStart", U + du, V + dv)

m.obj("Longsword", U + 5, V + 5)
m.obj("WarHammer", U - 5, V + 5)
m.obj("Bow", U - 5, V - 5)
m.obj("Quiver", U - 4, V - 6)
m.obj("LesserFireballWand", U + 5, V - 5)

for du, dv in [(3.5, 0), (-3.5, 0)]:
    m.obj("RedPotion", U + du, V + dv)
for du, dv in [(0, 3.5), (0, -3.5)]:
    m.obj("BluePotion", U + du, V + dv)

m.obj("Crown", U, V + 7, team=0)
m.obj("Crown", U - 7, V, team=1)
m.obj("Crown", U + 7, V, team=2)

for du, dv in [(12, 12), (-12, -12), (12, -12), (-12, 12)]:
    m.obj("TorchPole", U + du, V + dv)

if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "out")
    print("\n".join(m.build(os.path.abspath(out))))
