"""DysVale: phase 3 showcase. Everything is generated by the kit, nothing copied from Westwood:
a hedged meadow with a winding stream (two plank bridges and a ford), a pond with docks, and
seven original buildings in four styles (inn, shop, smithy, cottages), each room furnished by the
furnisher and checked for originality against all stock rooms.

Single player (Solo), one PlayerStart, no .nxz.
"""
import math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO, px
from kit.water import Waterworks
from kit.building import generate_building
from kit.originality import furnish_original

SEED = int(sys.argv[2]) if len(sys.argv) > 2 else 5
rng = random.Random(SEED)

m = Spec("DysVale", summary="DysVale - kit showcase village",
         description="A small village generated entirely by the map kit. Generated by Claude.",
         author="vdystopia (generated by Claude)", version="0.1", date="Saturday, October 3 2026",
         type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
m.d["ambient"] = [150, 146, 120]

U0, U1, V0, V1 = 180, 332, -66, 66
m.room(U0, U1, V0, V1, wall="DecidiousWallGreen", floor="GrassNorm")
for (x, y) in list(m.floor):                         # grass variety, sparse spills onto normal (floors rules)
    u, v = x + y + 2, x - y
    n = math.sin(u * 0.09 + 1.1) + math.sin(v * 0.11 + 0.4) + 0.5 * math.sin((u - v) * 0.05)
    if n > 1.0: m.floor[(x, y)] = "GrassSparse2"
    elif n < -1.2: m.floor[(x, y)] = "GrassDense"
m.blending("GrassSparse2", 2)
m.blending("GrassDense", 1)
m.blending("GrassNorm", 0)

# ---- water
ww = Waterworks(m, rng)
stream = ww.stream([(U0 + 2, -4), (214, 4), (246, -8), (280, 6), (U1 - 2, -2)], width=2.6, wiggle=2.5)
ww.plank_bridge(stream, t=0.30)
ww.plank_bridge(stream, t=0.68)
ww.ford(stream, t=0.88)
pond = ww.pond((300, 42), radius=8)
ww.dock(pond, "down", length=2)
ww.finish()

WATERISH = ("Water", "WoodSlat")
occupied = set()
for (x, y), mat in m.floor.items():                  # keep buildings off water, bridges and docks (+ margin)
    if any(k in mat for k in WATERISH):
        for dx in range(-4, 5):
            for dy in range(-4, 5): occupied.add((x + dx, y + dy))

# ---- buildings: north bank (v > 0) and south bank (v < 0)
plans = [("stucco_house", ["tavern", "kitchen", "bedroom"], (194, 16), (44, 34), "v_min"),   # inn
         ("cobble_house", ["shop", "storeroom"], (242, 22), (26, 22), "v_min"),
         ("log_cabin", ["bedroom"], (272, 24), (16, 14), "v_min"),
         ("stone_house", ["smithy", "storeroom"], (196, -50), (24, 20), "v_max"),
         ("log_cabin", ["living_room", "bedroom"], (232, -48), (20, 18), "v_max"),
         ("stucco_house", ["dining_hall", "bedroom"], (262, -56), (30, 28), "v_max"),
         ("log_cabin", ["bedroom"], (298, -40), (14, 14), "v_max")]
buildings = []
for k, (style, program, origin, size, side) in enumerate(plans):
    b = None
    for attempt in range(30):
        spread = 2 + attempt // 6
        jitter = (origin[0] + 2 * rng.randint(-spread, spread), origin[1] + 2 * rng.randint(-spread, spread))
        b = generate_building(m, rng, jitter, size, style, program=program, occupied=occupied,
                              entrance_side=side, building_id=f"B{k}")
        if b: break
    if not b:
        print(f"could not place {style} {program}"); continue
    occupied |= b.cells
    buildings.append(b)

checks = []
for b in buildings:
    for room in b.rooms:
        objs, res = furnish_original(m, room, kind=room.kind, rng=rng, style="town")
        checks.append((b.id, room.kind, len(objs), res["max_sim"], res["ok"]))

# ---- outdoor dressing: trees thicken toward the hedge (decoration rules), undergrowth throughout
inside = lambda u, v, mg: U0 + mg < u < U1 - mg and V0 + mg < v < V1 - mg


def ground_free(u, v):
    x, y = int((u + v) // 2), int((u - v) // 2)
    for dx in (-1, 0, 1):
        for dy in (-1, 0, 1):
            c = (x + dx, y + dy)
            if c in occupied or c in m.wallmap: return False
            if (c[0] + c[1]) % 2: continue                # floor tiles only exist where x + y is even
            mat = m.floor.get(c)
            if mat is None or any(k in mat for k in WATERISH) or mat.startswith(("Dirt", "Wood")): return False
    return True


TREES = ["TreeForest01", "TreeForest02", "TreeForest03", "TreeForest04", "TreeForest05", "TreeForest07",
         "TreeForest08", "TreeForest13", "TreeForest14", "TreeForest15", "TreeForest16", "TreeForest17"]
SMALL = ["Plant4", "Plant5", "PlantForest1", "PlantForest2", "PlantFern1", "Bush6", "Bush9", "Bush11",
         "FlowersYellowSparse", "FlowersPurpleSparse", "FlowersWhiteSparse", "GrassTuft2", "Mushroom3"]
placed = []
for _ in range(7000):
    u, v = rng.uniform(U0, U1), rng.uniform(V0, V1)
    edge = min(u - U0, U1 - u, v - V0, V1 - v)
    tree = rng.random() < (0.55 if edge < 8 else 0.2 if edge < 14 else 0.06)
    r = 2.8 if tree else 1.1
    if inside(u, v, 1.5) and ground_free(u, v) and all(math.hypot(u - a, v - b) > r + rr for a, b, rr in placed):
        placed.append((u, v, r))
        m.obj(rng.choice(TREES if tree else SMALL), u, v)
for _ in range(10):
    m.obj(rng.choice(["AmbBird1", "AmbBird2", "AmbCricket1"]), rng.uniform(U0 + 6, U1 - 6), rng.uniform(V0 + 6, V1 - 6))

m.obj("PlayerStart", U0 + 10, 14)
m.polygon("DysVale:Vale", (150, 146, 120), [px(U0, V0), px(U0, V1), px(U1, V1), px(U1, V0)])

if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] != "-" else os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "out")
    lines = m.build(os.path.abspath(out))
    print("\n".join(l for l in lines if not l.startswith("XFER")))
    print(f"buildings: {len(buildings)} | rooms: {len(checks)} | rooms flagged as near copies: {sum(1 for c in checks if not c[4])}")
    for c in checks: print("  ", *c)
