"""DysVale v0.3: generator v2 showcase. Everything is generated, nothing copied from Westwood.

A forest vale shaped like Westwood's outdoor maps: six areas joined by winding passages in a loop,
with a dirt road running through every passage.
- The village packs its buildings along the roads around a cobbled square with a well.
- A stream comes out of the forest, passes under the mill road (a plank bridge), then runs beside
  the woodcutter's road before turning back into the forest.
- The mill glade has a pond with a dock.
- The north grove is a quiet clearing; the lookout, at the far end of the loop, has a standing stone.
- Tree lines stand in front of the forest walls, with groves, undergrowth in single-type patches and
  flower patches by the roads.

Single player (Solo), one PlayerStart (the west gate), no .nxz.
    py mapgen/designs/dysvale.py [out_dir|-] [seed]
"""
import os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO, px
from kit.layout import Land, square_tile, square_px, px_square, cell_square
from kit.vegetation import Planter, FORESTS
from kit.water import Waterworks, xy_to_uv
from kit.building import generate_building
from kit.originality import furnish_original
from kit.village import Village

SEED = int(sys.argv[2]) if len(sys.argv) > 2 else 7
rng = random.Random(SEED)
FOREST = "deciduous"

m = Spec("DysVale", summary="DysVale - a village in a forest vale",
         description="A forest village with a stream, a mill pond and a woodcutter's clearing. Generated by Claude.",
         author="vdystopia (generated by Claude)", version="0.3", date="Saturday, October 3 2026",
         type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
m.d["ambient"] = [150, 146, 120]

# ---- 1. the shape: areas joined by winding passages ------------------------------------------------
land = Land(rng, u_range=(100, 446), v_range=(-160, 160))
land.area("gate", (140, -46), 20)
land.area("village", (222, 2), 54, stretch=1.15, angle=0.5)
land.area("mill", (338, 88), 30)
land.area("woodcut", (332, -100), 24)
land.area("grove", (170, 110), 18)
land.area("lookout", (408, -6), 20)
land.link("gate", "village", 13)
land.link("village", "mill", 14)
land.link("village", "woodcut", 24, bend=0.18)
land.link("village", "grove", 11)
land.link("mill", "lookout", 11)
land.link("woodcut", "lookout", 11, bend=0.35)
land.carve()
land.apply(m, wall=FORESTS[FOREST]["wall"], floor="GrassNorm")
land.ground_variety(m)
land.blends(m)
in_land = lambda x, y: cell_square(x, y) in land.squares or (x, y) in m.floor

# ---- 2. water: a stream between the village and the mill glade, and the mill pond --------------------
ww = Waterworks(m, rng)
link = {(l["a"], l["b"]): l for l in land.links}


def along(path, t0, t1, offset, n=6):
    """Points along a passage's centre line, shifted sideways by `offset` squares (uv coordinates)."""
    out = []
    for k in range(n):
        i = int((t0 + (t1 - t0) * k / (n - 1)) * (len(path) - 1))
        a, b = path[max(0, i - 2)], path[min(len(path) - 1, i + 2)]
        tx, ty = b[0] - a[0], b[1] - a[1]
        L = (tx * tx + ty * ty) ** 0.5 or 1
        si, sj = path[i][0] - ty / L * offset, path[i][1] + tx / L * offset
        out.append((2 * si, 2 * sj))
    return out


# the stream comes out of the forest, passes under the mill road, then runs beside the woodcutter's road
vm, vw = link[("village", "mill")]["path"], link[("village", "woodcut")]["path"]
mid = vm[len(vm) // 2]
stream_path = [(2 * mid[0] - 30, 2 * mid[1] + 70), (2 * mid[0], 2 * mid[1])] + along(vw, 0.35, 0.72, 3.6) +               along(vw, 0.78, 0.8, 16, n=2)                     # turns back into the forest before the clearing
stream = ww.stream(stream_path, width=3.4, wiggle=1.5)
pond = ww.pond((346, 104), radius=6)


def crossing_t(body, link_path):
    """Where a passage's centre line meets the stream: fraction along the stream."""
    best = None
    for si, sj in link_path:
        x, y = (si + sj), (si - sj)                  # square centre ~ tile cell
        for k, (bx, by) in enumerate(body.path_xy):
            d = (bx - x) ** 2 + (by - y) ** 2
            if best is None or d < best[0]: best = (d, k)
    return best[1] / max(1, len(body.path_xy) - 1)


ww.plank_bridge(stream, t=crossing_t(stream, link[("village", "mill")]["path"]))
for b in ww.bodies:
    for t in b.tiles:
        if "Water" in m.floor.get(t, ""): land.water.add(cell_square(*t))

# ---- 3. roads, the village square and its well -------------------------------------------------------
land.paint_roads(m, "DirtDark2", width_squares=2.6)
land.paint_square(m, "village", 9, "RoughCobble")
vc = land.areas["village"]["c"]
m.obj_px("Well", *square_px(vc[0], vc[1]))

# ---- 4. buildings along the roads, entrances facing them ---------------------------------------------
plans = [  # (area, style, program, size uv)
    ("village", "stucco_house", ["tavern", "kitchen", "bedroom"], (40, 32)),
    ("village", "cobble_house", ["shop", "storeroom"], (26, 22)),
    ("village", "stone_house", ["smithy", "storeroom"], (24, 20)),
    ("village", "log_cabin", ["living_room", "bedroom"], (20, 18)),
    ("village", "log_cabin", ["bedroom"], (16, 14)),
    ("mill", "log_cabin", ["living_room", "storeroom"], (18, 16)),
    ("woodcut", "log_cabin", ["bedroom"], (14, 12)),
]
buildings, doors_out = [], []
for k, (area, style, program, size) in enumerate(plans):
    b = None
    tried = free = 0
    for origin, side in [lot for a in area.split("|") for lot in land.lots(a, size)]:
        tried += 1
        if not land.lot_free(origin, size, margin=1): continue
        free += 1
        b = generate_building(m, rng, origin, size, style, program=program, entrance_side=side,
                              building_id=f"B{k}", occupied={c for s in land.taken for c in [square_tile(*s)]}, tries=12)
        if b: break
    if not b:
        print(f"could not place {style} {program} in {area} ({tried} lots, {free} free)"); continue
    land.take_cells(b.cells, margin=1)
    buildings.append(b)
    for d in b.entrances:
        land.path_between(m, px_square(*d.px))
        doors_out.append(px_square(*d.px))

furnished = []
for b in buildings:
    for room in b.rooms:
        objs, res = furnish_original(m, room, kind=room.kind, rng=rng, style="town")
        furnished.append((b.id, room.kind, len(objs), res["max_sim"], res["ok"]))

# ---- 4b. village dressing: gardens, props against walls, benches by the square, ground bits ----------
vil = Village(m, rng, land)
for b in buildings:
    if rng.random() < 0.6: vil.garden(b, size=(rng.randint(3, 5), rng.randint(2, 4)))
    vil.wall_props(b)
vil.benches("village", 3)

# ---- 5. lights: torch poles around the square and along the village roads ----------------------------
import json
_presets = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "rules", "out", "lighting.json")))["colorlight"]["presets"]
ORANGE = max((p for p in _presets if p["family"] == "orange" and p["animation"] == "steady" and p["intensity_class"] == "full"),
             key=lambda p: p["weighted_share"])


def torch_pole(x, y):
    m.obj_px("TorchPole", x, y)
    if rng.random() < 0.6: m.obj_px("ColorLight", x, y - 5, xfer=dict(ORANGE["xfer"]))

r = 9 / 2 + 1.2
for a, b2 in ((r, 0), (-r, 0), (0, r), (0, -r)):
    s = (int(vc[0] + a), int(vc[1] + b2) + 1)
    if s in land.squares and s not in land.taken: torch_pole(*square_px(vc[0] + a, vc[1] + b2))
VR = land.areas["village"]["r"] * 1.25
for path in land.road_paths:
    for i in range(6, len(path) - 6, 22):
        si, sj = path[i]
        if (si - vc[0]) ** 2 + (sj - vc[1]) ** 2 > VR ** 2: continue
        ti, tj = path[i + 1][0] - path[i - 1][0], path[i + 1][1] - path[i - 1][1]
        L = (ti * ti + tj * tj) ** 0.5 or 1
        qi, qj = si - tj / L * 2.2, sj + ti / L * 2.2
        s = (int(qi), int(qj) + 1)
        if s in land.squares and s not in land.taken and s not in land.roads and s not in land.water:
            torch_pole(*square_px(qi, qj))

# ---- 5b. the lookout: an old standing stone at the far end of the loop road ----------------------------
lk = land.areas["lookout"]["c"]
m.obj_px("ObeliskPrimitive", *square_px(lk[0] + 2, lk[1]))
land.taken |= {(int(lk[0]) + 2 + a, int(lk[1]) + 1 + b) for a in (-1, 0, 1) for b in (-1, 0, 1)}

# ---- 6. clearings' props: the woodcutter's logs and stumps ------------------------------------------
wc = land.areas["woodcut"]["c"]
for _ in range(14):
    si, sj = wc[0] + rng.gauss(0, 3.5), wc[1] + rng.gauss(0, 3.5)
    s = (int(si), int(sj) + 1)
    if s in land.squares and s not in land.taken and s not in land.roads and s not in land.water:
        m.obj_px(rng.choice(["Stump1", "Stump2", "Stump3", "ForestLog01", "ForestLog02", "ForestLog03"]), *square_px(si, sj))
        land.taken.add(s)

# ---- 7. vegetation, then the water's finishing (shore walls, reeds) ----------------------------------
gate = land.areas["gate"]["c"]
keep = {(int(gate[0]) + a, int(gate[1]) + b) for a in range(-3, 4) for b in range(-3, 4)}
keep |= {(d[0] + a, d[1] + b) for d in doors_out for a in range(-2, 3) for b in range(-2, 3)}
ww.dock(pond, "down", length=2)
for c in list(ww.no_walls): land.taken.add(cell_square(*c))
vil.ground_bits(2.0)
planter = Planter(m, rng, land, FOREST, keep_clear=keep)
n_trees, n_small = planter.plant_all(groves=3)
ww.finish()

m.obj_px("PlayerStart", *square_px(gate[0], gate[1]))
xs = [square_px(s[0], s[1]) for s in land.squares]
m.polygon("DysVale:Vale", (150, 146, 120), [(min(x for x, _ in xs) - 40, min(y for _, y in xs) - 40),
                                            (max(x for x, _ in xs) + 40, min(y for _, y in xs) - 40),
                                            (max(x for x, _ in xs) + 40, max(y for _, y in xs) + 40),
                                            (min(x for x, _ in xs) - 40, max(y for _, y in xs) + 40)])

if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] != "-" else os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "out")
    lines = m.build(os.path.abspath(out))
    print("\n".join(l for l in lines if not l.startswith("XFER")))
    print(f"land {len(land.squares)} tiles | roads {len(land.roads)} | buildings {len(buildings)}/{len(plans)} | "
          f"trees {n_trees} | plants {n_small} | rooms flagged as near copies: {sum(1 for c in furnished if not c[4])}")
