"""DysVale v0.4: built from its identity (generator v3). Everything is generated; nothing is copied
from Westwood.

The identity below comes first. It says what the place is, what each area is for, and who lives and
works in each building. The generators then follow it:
- work goes from the centre outwards: the square and its well first, the streets leaving it, the
  public buildings facing the square, then homes along the streets and the outlying areas' features;
- only then does the land grow around everything placed, ending in the forest wall;
- each building gets the rooms its role needs, each room only what its identity allows;
- outdoor props are scenes that show each building's trade;
- spacing comes before painting, so roads keep clear of the stream except at the bridge, and grass
  patches keep clear of every road, bank and building.

Single player (Solo), one PlayerStart (the west gate), no .nxz.
    py mapgen/designs/dysvale.py [out_dir|-] [seed]
"""
import json, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO
from kit.identity import MapIdentity, AreaIdentity, BuildingIdentity, BUILDINGS
from kit.layout import Land, square_tile, square_px, px_square, cell_square
from kit.vegetation import Planter, FORESTS
from kit.village import Village, _squares_of
from kit.water import Waterworks
from kit.building import generate_building
from kit.originality import furnish_original

SEED = int(sys.argv[2]) if len(sys.argv) > 2 else 7
rng = random.Random(SEED)
FOREST = "deciduous"

# ---- 0. identity: what this place is ---------------------------------------------------------------------
ID = MapIdentity(
    name="DysVale",
    theme="a logging and milling village in a deep forest vale, where the stream turns the mill and the "
          "woodcutters bring timber down the loop road",
    environment="town", mood="quiet, green, lived-in",
    areas=[AreaIdentity("gate", "where the forest road enters the vale; travellers arrive here"),
           AreaIdentity("village", "the heart of the vale: a cobbled square with the well, the inn, the store and the smithy",
                        landmark="Well"),
           AreaIdentity("mill", "the miller's glade on the shore of the lake, with the mill's dock reaching out into it"),
           AreaIdentity("woodcut", "the woodcutter's clearing, stumps all around"),
           AreaIdentity("grove", "a quiet grove north of the village"),
           AreaIdentity("lookout", "an old standing stone at the far end of the loop road", landmark="ObeliskPrimitive")],
    buildings=[BuildingIdentity("inn", "village", "The Tankard", "Ostrum the innkeeper"),
               BuildingIdentity("store", "village", "Vale Supplies", "Hedda the trader"),
               BuildingIdentity("smithy", "village", "the forge", "Brannoc the smith"),
               BuildingIdentity("home", "village", "", "a villager's family"),
               BuildingIdentity("home", "village", "", "a villager's family"),
               BuildingIdentity("cottage", "village", "", "an old widow"),
               BuildingIdentity("mill", "mill", "the mill house", "Tamsin the miller"),
               BuildingIdentity("woodcutter", "woodcut", "the woodcutter's hut", "Garret the woodcutter")])

m = Spec("DysVale", summary="DysVale - a village in a forest vale",
         description=f"[env:{ID.environment}] {ID.theme[0].upper() + ID.theme[1:]}. Generated by Claude.",
         author="vdystopia (generated by Claude)", version="0.4", date="Saturday, October 3 2026",
         type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
m.d["ambient"] = [150, 146, 120]

# ---- 1. the plan: where each area's centre is and which roads join them (nothing is built yet) ---------
land = Land(rng, u_range=(100, 446), v_range=(-160, 160))
land.area("village", (222, 2), 50, clearing=False)    # the village's extent comes from what is built
land.area("gate", (140, -46), 16)
land.area("mill", (308, 66), 18)
land.area("woodcut", (332, -100), 18)
land.area("grove", (170, 110), 16)
land.area("lookout", (412, -40), 14)
for a_, b_, w_ in (("gate", "village", 13), ("village", "mill", 14), ("village", "woodcut", 14),
                   ("village", "grove", 11), ("mill", "lookout", 11), ("woodcut", "lookout", 11)):
    land.link(a_, b_, w_, bend={("woodcut", "lookout"): 0.35, ("mill", "lookout"): 0.08}.get((a_, b_), 0.25))
land.blends(m)
# the mill road crosses the stream on a bridge. The crossing is planned now, with the road: the road runs
# straight over it and the stream is laid to flow across the road there (a bridge fitted onto an existing
# stream afterwards ends up jammed against the forest)
cross = land.plan_crossing("village", "mill", t=0.5)
link = {(l["a"], l["b"]): l for l in land.links}


def along(path, t0, t1, offset, n=6):
    """Points along a passage's centre line, shifted sideways by `offset` squares (uv coordinates)."""
    out = []
    for k in range(n):
        i = int((t0 + (t1 - t0) * k / (n - 1)) * (len(path) - 1))
        a, b = path[max(0, i - 2)], path[min(len(path) - 1, i + 2)]
        tx, ty = b[0] - a[0], b[1] - a[1]
        L = (tx * tx + ty * ty) ** 0.5 or 1
        out.append((2 * (path[i][0] - ty / L * offset), 2 * (path[i][1] + tx / L * offset)))
    return out


# the stream is planned now (so nothing is built on it) and dug once the land exists. It comes out of
# the forest, flows straight across the mill road at the planned crossing, then runs 5.5 squares off the
# woodcutter's road (road half-width 1.3 + 2.5 squares of bank + stream half-width 1.7)
vm, vw = link[("village", "mill")]["path"], link[("village", "woodcut")]["path"]
C = cross["uv"]
far = (C[0] - 30, C[1] + 70)                          # where the stream comes out of the forest
fu, fv = cross["flow"]
if (C[0] - far[0]) * fu + (C[1] - far[1]) * fv < 0: fu, fv = -fu, -fv
STREAM = ([far, (C[0] - 16 * fu, C[1] - 16 * fv), (C[0] - 7 * fu, C[1] - 7 * fv), C, (C[0] + 7 * fu, C[1] + 7 * fv)]
          + along(vw, 0.35, 0.72, 5.5) + along(vw, 0.78, 0.8, 18, n=2))
# the lake lies east of the mill glade, where the mill road ends: big enough that the mill's dock
# reaches out into open water (radius in tiles; the shore wanders up to 35% beyond it)
LAKE = ((344, 72), 11)
land.reserve_band(STREAM, 3.5)
land.reserve_band([LAKE[0], (LAKE[0][0] + 0.1, LAKE[0][1])], LAKE[1] * 1.35 + 2)

# ---- 2. the centre: the square and its well, and the streets leaving it -----------------------------------
land.paint_square(m, "village", 10, "RoughCobble")
vc = land.areas["village"]["c"]
m.obj_px("Well", *square_px(vc[0], vc[1]))
land.taken |= {(int(vc[0]) + a, int(vc[1]) + 1 + b) for a in (-1, 0, 1) for b in (-1, 0, 1)}
land.paint_roads(m, "DirtDark2", width_squares=2.6, skip=land.reserved)

# ---- 3. buildings, from the square outwards: public buildings face the square, homes line the streets ----
placed, door_paths = [], set()
order = sorted(range(len(ID.buildings)), key=lambda k: (BUILDINGS[ID.buildings[k].role]["faces"] != "square", k))
for k in order:
    bid = ID.buildings[k]
    role = BUILDINGS[bid.role]
    size = role["size"]
    program = [kind for kind, _ in role["rooms"]]
    lots = land.square_lots(size) if role["faces"] == "square" and bid.area == "village" else []
    lots += land.lots(bid.area, size)
    b = None
    for origin, side in lots:
        if not land.lot_free(origin, size, margin=1): continue
        b = generate_building(m, rng, origin, size, role["style"], program=program, entrance_side=side,
                              building_id=f"B{k}", occupied={square_tile(*s) for s in land.taken}, tries=12,
                              shape=role.get("shape"), min_units=role.get("min_units", 0))
        if b: break
    if not b:
        print(f"could not place the {bid.role} ({bid.name or bid.occupant}) in the {bid.area}"); continue
    land.take_cells(b.cells, margin=1)
    land.wall_cells |= {c for c in m.wallmap}
    land.taken_strict |= _squares_of(b.footprint)
    placed.append((bid, b))
    foot = _squares_of(b.footprint)
    # buildings that face the square must open onto it
    if role["faces"] == "square" and bid.area == "village" and b.entrances:
        out_sq = land.door_outside(b.entrances[0], foot)
        ci = sum(i for i, _ in foot) / len(foot); cj = sum(j for _, j in foot) / len(foot)
        dist = lambda a, b_: ((a[0] - b_[0]) ** 2 + (a[1] - b_[1]) ** 2) ** 0.5
        if out_sq is None or dist(out_sq, vc) >= dist((ci, cj), vc) - 1:
            print(f"  the {bid.role}'s door does not face the square")

# streets keep clear of walls; then every door gets a path routed to the streets; then any road that
# still runs into the side of a building is cut back
land.clear_walls(m)
for bid, b in placed:
    foot = _squares_of(b.footprint)
    for d in b.entrances:
        path = land.connect_door(m, d, foot)
        if path is None: print(f"  no path from the {bid.role}'s door")
        else: door_paths |= set(path)
land.trim_dead_ends(m, keep=door_paths)

furnished = []
for bid, b in placed:
    for room in b.rooms:
        objs, res = furnish_original(m, room, kind=room.kind, rng=rng, style="town")
        furnished.append((bid.role, room.kind, len(objs), res["ok"]))

# ---- 4. the outlying areas' features: the standing stone, the woodcutter's stumps --------------------------
lk = land.areas["lookout"]["c"]
m.obj_px("ObeliskPrimitive", *square_px(lk[0] + 2, lk[1]))
land.taken |= {(int(lk[0]) + 2 + a, int(lk[1]) + 1 + b) for a in (-1, 0, 1) for b in (-1, 0, 1)}
wc = land.areas["woodcut"]["c"]
for _ in range(10):                                  # felled trees: stumps and logs around the clearing
    si, sj = wc[0] + rng.gauss(0, 4.5), wc[1] + rng.gauss(0, 4.5)
    s = (int(si), int(sj) + 1)
    if s not in land.taken and s not in land.roads and s not in land.reserved and s not in land.taken_strict:
        m.obj_px(rng.choice(["Stump1", "Stump2", "Stump3", "Stump4", "ForestLog01", "ForestLog03"]), *square_px(si, sj))
        land.taken.add(s)

# ---- 5. the land grows around everything placed, ending in the forest wall --------------------------------
land.carve(margin=4.5)
land.apply(m, wall=FORESTS[FOREST]["wall"], floor="GrassNorm")

# ---- 6. water dug into the land: the stream with its planned bridge, the mill lake -------------------------
ww = Waterworks(m, rng, inside=lambda x, y: m.floor.get((x, y), "").startswith(("Grass", "Dirt")))
stream = ww.stream(STREAM, width=3.4, wiggle=0.8)
lake = ww.pond(*LAKE)
ww.plank_bridge(stream, at=cross["uv"], along=cross["axis"])
for b_ in ww.bodies:
    for t in b_.tiles:
        if "Water" in m.floor.get(t, ""): land.water.add(cell_square(*t))

# ---- 7. the square's life, the trades' scenes, gardens ------------------------------------------------------
vil = Village(m, rng, land)
for bid, b in placed:
    role = BUILDINGS[bid.role]
    for sc in role["scenes"]: vil.scene(b, sc)
    if rng.random() < role["garden"]: vil.garden(b, size=(rng.randint(3, 5), rng.randint(2, 4)))

presets = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "rules", "out", "lighting.json")))["colorlight"]["presets"]
ORANGE = max((p for p in presets if p["family"] == "orange" and p["animation"] == "steady" and p["intensity_class"] == "full"),
             key=lambda p: p["weighted_share"])


def torch_pole(si, sj, square=False):
    s = (int(si), int(sj) + 1)
    if s not in land.squares or s in land.water: return False
    if not square and (s in land.taken or s in land.roads or s in land.plaza): return False
    x, y = square_px(si, sj)
    m.obj_px("TorchPole", x, y)
    m.obj_px("ColorLight", x, y - 5, xfer=dict(ORANGE["xfer"]))
    land.taken.add(s)
    return True


# the square is a composed set piece: the well at the centre, benches on all four sides facing it,
# torch poles on the diagonals, all symmetric
vil.square_piece(vc, 5, pole=lambda si, sj: torch_pole(si, sj, square=True), per_side=2)

# street lights keep a steady rhythm: every 12 squares along each street leaving the square, always
# on the same hand, until the street leaves the village
VR = land.areas["village"]["r"] * 1.1
lights = []
for path in land.road_paths:
    pts = path if (path[0][0] - vc[0]) ** 2 + (path[0][1] - vc[1]) ** 2 < (path[-1][0] - vc[0]) ** 2 + (path[-1][1] - vc[1]) ** 2 else path[::-1]
    if (pts[0][0] - vc[0]) ** 2 + (pts[0][1] - vc[1]) ** 2 > 4: continue      # only streets from the square
    walked = 0.0
    nxt = 5 + 6                                    # first light just past the square's edge
    for i in range(1, len(pts) - 1):
        walked += ((pts[i][0] - pts[i - 1][0]) ** 2 + (pts[i][1] - pts[i - 1][1]) ** 2) ** 0.5
        if (pts[i][0] - vc[0]) ** 2 + (pts[i][1] - vc[1]) ** 2 > VR ** 2: break
        if walked < nxt: continue
        ti, tj = pts[i + 1][0] - pts[i - 1][0], pts[i + 1][1] - pts[i - 1][1]
        L = (ti * ti + tj * tj) ** 0.5 or 1
        qi, qj = pts[i][0] + tj / L * 2.4, pts[i][1] - ti / L * 2.4      # right-hand side
        if all((qi - a) ** 2 + (qj - b) ** 2 > 36 for a, b in lights) and torch_pole(qi, qj):
            lights.append((qi, qj))
        nxt += 12

# ---- 8. ground patches (after everything they must keep clear of), vegetation, water's finish -------------
land.ground_variety(m, clear=3)
gate = land.areas["gate"]["c"]
keep = {(int(gate[0]) + a, int(gate[1]) + b) for a in range(-3, 4) for b in range(-3, 4)}
for bid, b in placed:
    for d in b.entrances:
        di, dj = px_square(*d.px)
        keep |= {(di + a, dj + b2) for a in range(-2, 3) for b2 in range(-2, 3)}
# the mill's dock starts where the mill road reaches the lake and runs out into open water
mill_end = link[("village", "mill")]["path"][-1]
dock = ww.dock(lake, "down", length=2, beyond=5, near=(2 * mill_end[0], 2 * mill_end[1]))
if dock:
    du_, dv_ = dock["start"]
    land.connect(m, px_square((du_ + dv_) / 2 * 23, (du_ - dv_) / 2 * 23))
else:
    print("no room for the mill's dock")
for c in list(ww.no_walls): land.taken.add(cell_square(*c))
vil.ground_bits(1.5)
planter = Planter(m, rng, land, FOREST, keep_clear=keep)
n_trees, n_small = planter.plant_all(groves=3)
ww.finish()

m.obj_px("PlayerStart", *square_px(gate[0], gate[1]))
xs = [square_px(s[0], s[1]) for s in land.squares]
m.polygon("DysVale:Vale", (150, 146, 120), [(min(x for x, _ in xs) - 40, min(y for _, y in xs) - 40),
                                            (max(x for x, _ in xs) + 40, min(y for _, y in xs) - 40),
                                            (max(x for x, _ in xs) + 40, max(y for _, y in xs) + 40),
                                            (min(x for x, _ in xs) - 40, max(y for _, y in xs) + 40)])

if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] != "-" else os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "out")
    lines = m.build(os.path.abspath(out))
    print("\n".join(l for l in lines if not l.startswith("XFER")))
    print(ID.describe())
    print(f"land {len(land.squares)} tiles | buildings {len(placed)}/{len(ID.buildings)} | trees {n_trees} | plants {n_small}")
    for f in furnished: print("  ", *f)
