"""Emberdeep: a volcanic underworld (biome: lava; rules/BIOMES.md), built from the centre outwards.

At its heart a lake of lava seethes below black cliffs, flames dancing on it and crusts of cooled rock drifting; a
shrine of dark obelisks stands on its north shore. Around it:
- north-west, a ruined demon forge: fire grates in rows, flame basins, rubble;
- north-east, a field of bones and skulls among cooled lava;
- south-west, the vents: fire bursting from the rock round a second pool of lava;
- south-east, the scorched ledge where the way in arrives.

Single player (Solo), one PlayerStart, no .nxz.
    py mapgen/designs/emberdeep.py [out_dir|-] [seed]
"""
import math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO
from kit.identity import MapIdentity, AreaIdentity
from kit.layout import Land, square_px, square_tile, N4
from kit.biome import Dresser

SEED = int(sys.argv[2]) if len(sys.argv) > 2 else 7
rng = random.Random(SEED)
HERE = os.path.dirname(os.path.abspath(__file__))

ID = MapIdentity(
    name="Emberdeep",
    theme="a volcanic underworld: a lake of lava seethes below black cliffs with a shrine of dark obelisks on its "
          "shore; round it a ruined demon forge, a field of bones among cooled lava, fire vents round a second pool, "
          "and the scorched ledge where the way in arrives",
    environment="lava", mood="searing, red, ominous",
    areas=[AreaIdentity("heart", "the lava lake below black cliffs and the obsidian shrine on its shore", landmark="the lava lake"),
           AreaIdentity("forge", "a ruined demon forge: fire grates in rows, flame basins, rubble"),
           AreaIdentity("bones", "a field of bones and skulls among cooled lava"),
           AreaIdentity("vents", "fire bursting from the rock round a second pool of lava"),
           AreaIdentity("ledge", "the scorched ledge where the way in arrives")])

m = Spec("Emberdeep", summary="Emberdeep - a volcanic underworld",
         description=f"[env:{ID.environment}] {ID.theme[0].upper() + ID.theme[1:]}. Generated by Claude.",
         author="vdystopia (generated by Claude)", version="0.1", date="Saturday, October 3 2026",
         type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False

land = Land(rng, u_range=(20, 490), v_range=(-226, 226))
A = land.area
A("heart", (255, 0), 70, stretch=1.2, angle=0.6, roughness=0.18)
A("forge", (180, 110), 36, roughness=0.24)
A("bones", (330, 115), 34, roughness=0.3)
A("vents", (180, -110), 40, roughness=0.28)
A("ledge", (335, -95), 30, roughness=0.22)
A("gate", (395, -45), 16, roughness=0.2)
for k_, ar in land.areas.items():
    x_, y_ = ar["c"][0] + ar["c"][1], ar["c"][0] - ar["c"][1]
    assert 12 + ar["r"] <= x_ <= 243 - ar["r"] and 12 + ar["r"] <= y_ <= 243 - ar["r"], (k_, x_, y_)
for a_, b_, w_ in (("heart", "forge", 16), ("heart", "bones", 14), ("heart", "vents", 16), ("heart", "ledge", 18),
                   ("ledge", "gate", 14), ("forge", "vents", 12), ("bones", "ledge", 12)):
    land.link(a_, b_, w_, bend=0.3, road=False, pockets=(1, 2))

# ---- the centre first: the lava lake behind its cliffs, and the second pool in the vents -------------------------
d = Dresser(m, rng, land, "lava")
lake = d.reserve_pool((255, 0), 34, stretch=1.3, angle=0.6, roughness=0.28)
pool2 = d.reserve_pool((170, -120), 14, roughness=0.3)
land.carve(margin=4.0)
land.assign_regions()
crags = land.thickets(18, size=(1.2, 2.4), clear=3, avoid={s for s in land.squares if math.hypot(
    s[0] - land.areas["gate"]["c"][0], s[1] - land.areas["gate"]["c"][1]) < 12})
land.apply(m, wall=d.wall, floor=d.base)
d.cap_islands(crags, "VolcanicCraggy")
d.ground()
d.paint_pools()

hc = land.areas["heart"]["c"]
in_area = lambda name, s: land._in_area((s[0] + 0.5, s[1] - 0.5), land.areas[name])
centre = {k: land.areas[k]["c"] for k in land.areas}
start = min(land.squares, key=lambda s: math.hypot(s[0] - centre["gate"][0], s[1] - centre["gate"][1]))
keep = {(start[0] + a, start[1] + b) for a in range(-3, 4) for b in range(-3, 4)}
d.taken |= keep

# the obsidian shrine on the lake's north shore: a ring of dark obelisks round a flame basin, red light
shore = sorted((s for s in land.squares if any((s[0] + a, s[1] + b) in lake for a in range(-4, 5) for b in range(-4, 5))),
               key=lambda s: (s[1] - hc[1]) * 0.7 + (s[0] - hc[0]) * -0.7)
shrine = (shore[0][0] + 0.5, shore[0][1] - 3.0) if shore else hc
if (int(shrine[0]), int(shrine[1]) + 1) in land.squares:
    for k in range(6):
        a = k * 2 * math.pi / 6
        m.obj_px("ObeliskPrimitive", *square_px(shrine[0] + 2.4 * math.cos(a), shrine[1] + 2.4 * math.sin(a)))
    m.obj_px("DunMirFlameBasinLit", *square_px(*shrine))
    m.obj_px("ColorLight", *square_px(*shrine), xfer=d._light_xfer((255, 64, 0), 220, 70))
    d.taken |= {(int(shrine[0]) + a, int(shrine[1]) + 1 + b) for a in range(-4, 5) for b in range(-4, 5)}

# the demon forge: rows of fire grates, flame basins, rubble
forge = [s for s in land.squares if in_area("forge", s)]
fc = land.areas["forge"]["c"]
for row in (-2, 2):
    for k in range(-3, 4):
        si, sj = fc[0] + k * 1.6, fc[1] + row
        if (int(si), int(sj) + 1) in land.squares:
            m.obj_px("FireGrate", *square_px(si, sj)); d.taken.add((int(si), int(sj) + 1))
d.clusters({"Brick": 3, "CaveRocksMedium": 2, "Rock4": 1}, forge, 6, size=(3, 5), radius=1.4, gap=0.9, spacing=5.0)
d.clusters({"DunMirFlameBasinLit": 1}, forge, 3, size=(1, 1), spacing=6.0)

# the bone field: heaps of bones and skulls among cooled lava
bones = [s for s in land.squares if in_area("bones", s)]
d.clusters({"LegBone": 3, "ArmBone": 2, "Skull": 3}, bones, 10, size=(4, 8), radius=1.6, gap=0.6, spacing=5.0)
d.clusters({"LavaHardened5": 1, "LavaHardened7": 1}, bones, 6, size=(1, 2), radius=1.2, gap=1.6, spacing=6.0)

# the vents: fire grates and flames bursting from the rock round the second pool
vents = [s for s in land.squares if in_area("vents", s)]
d.clusters({"FireGrate": 2, "SmallFlameImmobile": 2, "MediumFlameImmobile": 1}, vents, 8, size=(2, 4), radius=1.3,
           gap=1.0, spacing=5.0)

# ---- the biome: flames and bubbles on the lava, rocks and bones, red light, demons -------------------------------
n_liq = d.dress_liquid()
n_trees, n_small = d.vegetate(keep_clear=keep, groves=2)
d.scatter_open()
d.rim()
n_lights = d.lights()
n_mon = d.creatures(avoid=[start], groups=(1, 3))
x, y = square_px(start[0] + 0.5, start[1] - 0.5)
m.obj_px("PlayerStart", x, y)

out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "out")
if out != "-":
    lines = m.build(out)
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK"))))
print(f"land {len(land.squares)} squares | lava {len(d.pools)} | crags {len(crags)} | on the lava {n_liq} | rocks {n_trees} "
      f"small {n_small} | lights {n_lights} | creatures {n_mon}")
