"""Frostfang: a frozen waste (biome: ice; rules/BIOMES.md), built from the centre outwards.

At its heart a frozen lake lies under the ice cliffs, an old shrine of standing stones on its shore. Snow-laden
pines and bare white trees crowd the edges of the plateaus. Around the lake:
- north, a pine wood heavy with snow;
- east, a crystal ice cave glittering blue;
- west, the wolves' den, littered with bones;
- south, the hunters' camp where the way in arrives.

Single player (Solo), one PlayerStart, no .nxz.
    py mapgen/designs/frostfang.py [out_dir|-] [seed]
"""
import math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO
from kit.identity import MapIdentity, AreaIdentity
from kit.layout import Land, square_px, square_tile, N4
from kit.biome import Dresser

SEED = int(sys.argv[2]) if len(sys.argv) > 2 else 3
rng = random.Random(SEED)
HERE = os.path.dirname(os.path.abspath(__file__))

ID = MapIdentity(
    name="Frostfang",
    theme="a frozen waste: a frozen lake lies under ice cliffs with an old shrine of standing stones on its shore, a "
          "pine wood heavy with snow, a glittering ice cave, the wolves' den and the hunters' camp where the way in "
          "arrives",
    environment="ice", mood="cold, still, blue",
    areas=[AreaIdentity("heart", "the frozen lake and its shrine of standing stones", landmark="the frozen lake"),
           AreaIdentity("pines", "the snow-heavy pine wood"),
           AreaIdentity("icecave", "an ice cave glittering with blue crystals"),
           AreaIdentity("den", "the wolves' den, littered with bones"),
           AreaIdentity("camp", "the hunters' camp where the way in arrives")])

m = Spec("Frostfang", summary="Frostfang - a frozen waste",
         description=f"[env:{ID.environment}] {ID.theme[0].upper() + ID.theme[1:]}. Generated by Claude.",
         author="vdystopia (generated by Claude)", version="0.2", date="Sunday, October 4 2026",
         type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False

land = Land(rng, u_range=(20, 490), v_range=(-226, 226))
A = land.area
A("heart", (255, 0), 70, stretch=1.3, angle=-0.4, roughness=0.16)
A("pines", (190, 110), 44, stretch=1.2, angle=0.5, roughness=0.26)
A("icecave", (330, 100), 44, roughness=0.26)
A("den", (170, -110), 34, roughness=0.28)
A("camp", (340, -100), 36, roughness=0.2)
A("gate", (400, -40), 16, roughness=0.2)
for k_, ar in land.areas.items():
    x_, y_ = ar["c"][0] + ar["c"][1], ar["c"][0] - ar["c"][1]
    assert 12 + ar["r"] <= x_ <= 243 - ar["r"] and 12 + ar["r"] <= y_ <= 243 - ar["r"], (k_, x_, y_)
for a_, b_, w_ in (("heart", "pines", 20), ("heart", "icecave", 14), ("heart", "den", 18), ("heart", "camp", 20),
                   ("camp", "gate", 14), ("pines", "den", 16), ("icecave", "camp", 12)):
    land.link(a_, b_, w_, bend=0.3, road=False, pockets=(1, 2))

# ---- the centre first: the frozen lake (walkable dark ice) and its shrine ------------------------------------------
d = Dresser(m, rng, land, "ice")
# the dark temple sunk in the ice cave (the Land of the Dead's ornate walls, as Westwood builds in its ice), facing the lake
temple = d.structure("ice_temple", "icecave", toward="heart", scale=1.0, name="the dark temple")
land.carve(margin=4.0)
hc = land.areas["heart"]["c"]
lake = {s for s in land.squares if land._in_area((s[0] + 0.5, s[1] - 0.5), dict(land.areas["heart"], r=land.areas["heart"]["r"] * 0.55))}
# ice outcrops: cliff-ringed islands break the plateaus up, as the Wastelands' cliffs do (Westwood's ice maps carry 28
# to 33 wall pieces per 100 floor tiles); none on the lake or by the way in
gate_c = land.areas["gate"]["c"]
calm = lake | {s for s in land.squares if math.hypot(s[0] - gate_c[0], s[1] - gate_c[1]) < 12}
land.assign_regions()
outcrops = land.thickets(150, size=(1.3, 3.0), clear=2, avoid=calm)
land.apply(m, wall=d.wall, floor=d.base)
d.cap_islands(outcrops)                                          # snow on the outcrops' tops
for s in lake: m.floor[square_tile(*s)] = "IceFloorDark"          # dark slate ice: the frozen lake
d.ground()
# the shrine: a ring of standing stones on the north shore, a crystal at its middle, cold light
shrine = (hc[0] - 6, hc[1] + 9)
for k in range(7):
    a = k * 2 * math.pi / 7
    m.obj_px("ObeliskPrimitive", *square_px(shrine[0] + 2.6 * math.cos(a), shrine[1] + 2.6 * math.sin(a)))
m.obj_px("MineCrystal05", *square_px(*shrine))
m.obj_px("ColorLight", *square_px(*shrine), xfer=d._light_xfer((96, 160, 255), 220, 60))
d.taken |= {(int(shrine[0]) + a, int(shrine[1]) + 1 + b) for a in range(-4, 5) for b in range(-4, 5)}
# cracks in the lake's ice
d.clusters({"IceCrack2": 3, "IceCrack4": 2, "IceCrack6": 2}, lake, 10, size=(1, 3), radius=1.5, gap=1.4, spacing=6.0)

in_area = lambda name, s: land._in_area((s[0] + 0.5, s[1] - 0.5), land.areas[name])
centre = {k: land.areas[k]["c"] for k in land.areas}
start = min(land.squares, key=lambda s: math.hypot(s[0] - centre["gate"][0], s[1] - centre["gate"][1]))
keep = {(start[0] + a, start[1] + b) for a in range(-3, 4) for b in range(-3, 4)}
d.taken |= keep

# the ice cave: crystal formations, blue light
cave = [s for s in land.squares if in_area("icecave", s) and s not in land.taken]
for ci, cj in d.clusters({"MineCrystal05": 4, "MineCrystal02": 2, "MineCrystal04": 2}, cave, 7, size=(4, 8), radius=1.7,
                         gap=0.8, spacing=6.0, core="MineCrystalUp03"):
    if rng.random() < 0.6: m.obj_px("ColorLight", *square_px(ci, cj), xfer=d._light_xfer((96, 160, 255), 190, 45))
# the wolves' den: bones in heaps
den = [s for s in land.squares if in_area("den", s)]
d.clusters({"LegBone": 3, "ArmBone": 2, "Skull": 1}, den, 6, size=(3, 6), radius=1.4, gap=0.6, spacing=5.0)
# the hunters' camp: tents of hides are not in the game: stacked crates, barrels, a fire basin
camp = [s for s in land.squares if in_area("camp", s) and s not in keep]
d.clusters({"DarkCrate1": 2, "Crate1": 2, "Crate2": 1}, camp, 3, size=(2, 4), radius=1.3, gap=1.4, spacing=7.0)
d.clusters({"Barrel": 2, "Barrel2": 2}, camp, 2, size=(2, 3), radius=1.0, gap=1.0, spacing=6.0)
d.clusters({"DunMirFlameBasinLit": 1}, camp, 1, size=(1, 1), spacing=8.0)

# ---- the temple's rooms, furnished as the Land of the Dead's are, and the undead who keep it ----------------------
furnished = d.furnish_structures()
n_keep = d.garrison()

# ---- the biome: snow trees thick along the cliffs and in groves, rocks, cold lights, wolves ----------------------
n_trees, n_small = d.vegetate(keep_clear=keep | lake, groves=4)
d.scatter_open()
d.rim()
n_lights = d.lights()
n_mon = d.creatures(avoid=[start], groups=(2, 4))
m.scripts.update(d.population.behaviours.files(m.d['name']))     # packs and skittish creatures (kit/behaviours)
x, y = square_px(start[0] + 0.5, start[1] - 0.5)
m.obj_px("PlayerStart", x, y)

out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "out")
if out != "-":
    d.declare_rooms(os.path.join(os.path.abspath(out), m.d["name"] + ".rooms.json"))
    lines = m.build(out)
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK"))))
print(f"land {len(land.squares)} squares | lake {len(lake)} | outcrops {len(outcrops)} | trees {n_trees} small {n_small} | lights {n_lights} | creatures {n_mon} | "
      f"temple {'yes' if temple else 'NO'}: {', '.join(f'{k} {n}' for _, k, n in furnished)}, keepers {n_keep}")
