"""Harpoon lab: the fireball staff that throws harpoons (rules/WEAPONS.md, kit/behaviours/weapons.go).

A Lesser Fireball staff lies by the start, named HarpoonStaff. Pick it up and fire: while you hold it, each fireball
becomes a harpoon bolt that flies straight and fast. A creature it strikes is wounded and reeled in to you. A bolt that
reaches a wall, or flies its full reach, is gone. Zombies stand in a row across the hall to try it on; an ordinary
Lesser Fireball staff lies beside it to compare.

    py mapgen/designs/harpoonlab.py [out_dir|-]
"""
import os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO, px
from kit.npcs import Population

HERE = os.path.dirname(os.path.abspath(__file__))
rng = random.Random(1)
m = Spec("Harpoon", summary="Harpoon lab", description="[env:castle] A fireball staff that throws harpoons. "
         "Generated by Claude.", author="vdystopia (generated by Claude)", version="0.1", date="2026",
         type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
m.d["ambient"] = [180, 175, 170]
P = lambda u, v: px(u, v)
m.room(220, 300, -30, 30, wall="BrickPlain", floor="CobbleStone")
for k in range(4):                                # lights along the hall
    m.obj_px("TorchPole", *P(226 + 22 * k, 26))
pop = Population(m, rng)
m.obj_px("LesserFireballWand", *P(290, -2), scr="HarpoonStaff")   # the harpoon staff
m.obj_px("LesserFireballWand", *P(290, 6))                         # an ordinary one, to compare
for k in range(5):                                # targets across the hall
    pop.creature("Zombie", *P(236, -16 + 8 * k), action="idle", aggr=0.0)
pop.behaviours.harpoon_staff("HarpoonStaff")
m.obj_px("PlayerStart", *P(294, 0))
m.scripts.update(pop.behaviours.files(m.d["name"]))

out_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "out")
if out_dir != "-":
    lines = m.build(out_dir)
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK", "SCRIPTS"))))
