"""Harrowby replay: the rooms the user flagged after the Harrowby playtest (2026-10-05, review/FEEDBACK.md HB-1..HB-5),
rebuilt wall for wall, floor for floor and door for door from the map the user played, then furnished again by the kit
as it stands now. A before-and-after on the same rooms: the kit's later changes moved Harrowby's buildings, so the
rebuilt town's rooms are no longer those rooms. Never installed; not a map to play.

    py mapgen/designs/hbreplay.py [source.map] [room number ...]

The source is the map the user played (mapgen/out/harrowby_before/Harrowby.map, copied from the installed build, with
its rooms.json); the replay writes mapgen/out/hbreplay/HBReplay.map and its rooms.json, so `py review/rooms.py
mapgen/out/hbreplay/HBReplay.map --each` draws each room beside the playtest's (review/out/Harrowby/before/NN.png).
"""
import json, os, random, sys, zlib
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(HERE, "..", "..", "validate"))
from nox import Spec, SOLO
from kit.model import Room, Door
from kit.identity import BUILDINGS
from kit.originality import furnish_original
import mapdata as md

REPO = os.path.dirname(os.path.dirname(HERE))
SOURCE = os.path.join(REPO, "mapgen", "out", "harrowby_before", "Harrowby.map")
OUT = os.path.join(REPO, "mapgen", "out", "hbreplay")
# the five rooms of the feedback, by their number in the played map's rooms.json, with the building role they belong to
FLAGGED = {28: ("cottage", "HB-1: the log-house room with two cauldrons, the bed and the chest by the fires, sacks down a wall"),
           9: ("townhall", "HB-2: the moot hall, trophies behind statues, chests by the hearth, an empty south corner"),
           11: ("townhall", "HB-3: the reeve's chamber with four chests and three table sets"),
           10: ("townhall", "HB-4: the reeve's library, statues side by side, candelabras, the chest by the door"),
           12: ("townhall", "HB-5: the storeroom with a whole wall of log shelves")}
FIELD = (130, 380, -120, 120)


def _slot(cells, taken):
    """An even shift (dx, dy) that puts a room's cells inside the field (6 cells in from its walls), clear of `taken`."""
    u0, u1, v0, v1 = FIELD
    for dy in range(-260, 260, 2):
        for dx in range(-260, 260, 2):
            moved = [(x + dx, y + dy) for x, y in cells]
            if all(u0 + 8 <= x + y <= u1 - 8 and v0 + 8 <= x - y <= v1 - 8 and (x, y) not in taken for x, y in moved):
                return dx, dy
    raise RuntimeError("the field cannot hold another room")


def replay(source=SOURCE, numbers=None, seed=3):
    rooms_json = json.load(open(os.path.splitext(source)[0] + ".rooms.json"))
    jdir = os.path.join(OUT, "source_json")
    m0 = md.load(md.export(source, out_dir=jdir))
    numbers = numbers or sorted(FLAGGED)
    m = Spec("HBReplay", summary="Harrowby replay", description="The playtest's flagged rooms, furnished again. Generated by "
             "Claude.", author="vdystopia (generated by Claude)", version="1", date="2026", type=SOLO, minPlayers=1,
             maxPlayers=1)
    m.d["nxz"] = False
    m.d["ambient"] = [165, 160, 155]
    u0, u1, v0, v1 = FIELD
    m.room(u0, u1, v0, v1, wall="BrickPlain", floor="GrassNorm")
    out, taken = [], set()                 # grid cells the rooms placed so far keep (with a margin)
    rng = random.Random(seed)
    floors = {}
    for num in numbers:
        rec = next(r for r in rooms_json if r["number"] == num)
        tiles = {tuple(t) for t in rec["floor"]}
        x0, y0, x1, y1 = rec["box"]
        cells = {(x + a, y + b) for x, y in tiles for a in (0, 1) for b in (0, 1)}
        dx, dy = _slot(cells, taken)
        near = {(x + a, y + b) for x, y in cells for a in (-1, 0, 1) for b in (-1, 0, 1)}
        walls = {c: w for c, w in m0.walls.items() if c in near}
        for (x, y), w in walls.items():
            m.wall(x + dx, y + dy, w.material)
        for (x, y) in tiles:
            mat = m0.tiles.get((x, y), {}).get("material", "WoodLight2")
            m.tile(x + dx, y + dy, mat)
            floors[mat] = floors.get(mat, 0) + 1
        doors = []
        for d in m0.doors:
            g = d["gap"]
            if not any((g[0] + a, g[1] + b) in cells for a, b in md.N4): continue
            gap = (g[0] + dx, g[1] + dy)
            if gap in m.door_gaps: continue
            obj = m.door(d["obj"]["type"], gap, d["line"])
            other = next((r2["number"] for r2 in rooms_json if r2["number"] != num and
                          any((g[0] + a, g[1] + b) in {(x + p, y + q) for x, y in map(tuple, r2["floor"]) for p in (0, 1) for q in (0, 1)}
                              for a, b in md.N4)), None)
            doors.append(Door(gap=gap, line=d["line"], type=obj["type"], connects=(f"r{num}", f"r{other}" if other else "outside"),
                              px=(obj["x"], obj["y"])))
        role, why = FLAGGED.get(num, ("home", ""))
        floor = max(floors, key=floors.get) if floors else "WoodLight2"
        floors.clear()
        room = Room(id=f"r{num}", tiles={(x + dx, y + dy) for x, y in tiles}, floor=floor,
                    walls={(x + dx, y + dy) for x, y in walls}, doors=doors, kind=rec["kind"], building=role)
        style = BUILDINGS.get(role, {}).get("furnish") or "town"
        m.d["name"] = "Harrowby"            # the building's palette as the played map drew it (Furnisher palette)
        furnish_original(m, room, kind=rec["kind"], rng=random.Random(rng.random()), style=style)
        m.d["name"] = "HBReplay"
        print(f"room {num} {rec['kind']}: the knowledge base refused {getattr(room, 'kb_refused', {})}")
        bx = [x for x, _ in room.tiles]; by = [y for _, y in room.tiles]
        out.append(dict(number=num, building=rec["building"], kind=rec["kind"], purpose=why, tiles=len(room.tiles),
                        box=[min(bx) - 1, min(by) - 1, max(bx) + 3, max(by) + 3], floor=sorted([x, y] for x, y in room.tiles)))
        taken |= {(x + dx + a, y + dy + b) for x, y in cells for a in range(-6, 7) for b in range(-6, 7)}
    m.obj("PlayerStart", u0 + 4, v0 + 4)
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "HBReplay.rooms.json"), "w", encoding="utf-8") as f: json.dump(out, f, indent=1)
    lines = m.build(OUT)
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK"))))
    return os.path.join(OUT, "HBReplay.map")


if __name__ == "__main__":
    args = sys.argv[1:]
    src = args.pop(0) if args and args[0].endswith(".map") else SOURCE
    replay(src, [int(a) for a in args] or None)
