"""Mirefen: an eel-fishers' village at the edge of the Black Fen, and the story of the drowned chapel (chapter five;
swamp palette, kit/biome.py BIOMES["swamp"], measured on Westwood's swamps). Built with kit/story.py.

The story
- The causeway brings the player to Mirefen from the south: a huddle of log houses round a fire basin on the only
  dry ground in the fen. Old Wenna, mending nets by the causeway, tells them the dead walk the reeds.
- Main quest, the Drowned Chapel: a necromancer, Morvane, has taken the old chapel sunk in the fen to the east and
  raises the drowned from its crypt; the dead come up through the reeds at night. Elder Haska has shut the north
  causeway gate (the way on) until they stop. Morvane dead, Haska opens the gate.
- The Lost Boy: Tam, the fisher Orrin's son, went into the reeds after frogs and has not come back. He is hiding by
  the wasp nest in the west fen, too frightened to move while the wasps are about. Clear the wasps and he runs home
  (A.walk to his father's door); Orrin pays.
- The Great Leech: a leech as long as a boat lives in the deep pool north of the village and has taken two of
  Brask's eel traps. Brask pays for it.
- The trading post and the Eel and Lantern inn buy and sell; caches lie hidden in the reeds; the villagers each know
  something.
- The exit (the north causeway) leads to Greywatch, the border castle on the hill road (chapter six).

    py mapgen/designs/mirefen.py [seed]
"""
import math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO, CELL
from kit.identity import MapIdentity, AreaIdentity, BuildingIdentity, BUILDINGS, rooms_sidecar
from kit.layout import Land, square_tile, square_px, bfs_distance
from kit.biome import Dresser
from kit.village import Village
from kit.quests import QuestBook, A, QUEST, COMPLETED, HINT
from kit.story import StoryMap
from kit import camps

SEED = int(sys.argv[1]) if len(sys.argv) > 1 else 3
rng = random.Random(SEED)
NAME = "Mirefen"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "out", "mirefen")
NEXT_MAP = "Greywatch"
PATH = "DirtLight2"                 # the trodden ways of the fen (a floor of the swamp palette)


def uv(X, Y):
    return (X + Y, X - Y)


ID = MapIdentity(
    name=NAME,
    theme="an eel-fishers' village on the only dry ground at the edge of the Black Fen: log houses round a fire basin, "
          "a drowned chapel out in the fen where a necromancer raises the dead, a deep pool, a wasp nest in the reeds",
    environment="town", mood="damp, fearful",
    areas=[AreaIdentity("south", "the causeway from the south: the start"),
           AreaIdentity("town", "Mirefen's dry ground and its houses", landmark="the fire basin"),
           AreaIdentity("chapel", "the drowned chapel in the east fen"),
           AreaIdentity("wasps", "the wasp nest in the west fen"),
           AreaIdentity("pool", "the deep pool north of the village"),
           AreaIdentity("gate", "the north causeway gate"),
           AreaIdentity("north", "the causeway north: the way out")],
    buildings=[BuildingIdentity("foreman", "town", "the elder's house", "Elder Haska"),
               BuildingIdentity("store", "town", "the trading post", "the trader"),
               BuildingIdentity("inn", "town", "The Eel and Lantern", "the innkeeper"),
               BuildingIdentity("home", "town", "Orrin's house", "Orrin and Tam"),
               BuildingIdentity("cottage", "town", "", "Brask the eel-catcher"),
               BuildingIdentity("cottage", "town", "", "Wenna")])

m = Spec(NAME, summary="Mirefen", description=f"[env:{ID.environment}] {ID.theme[0].upper() + ID.theme[1:]}. "
         f"Generated by Claude.", author="vdystopia (generated by Claude)", version="1", date="2026", type=SOLO,
         minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
q = QuestBook(NAME)

# ---- 1. the plan ---------------------------------------------------------------------------------------------------
land = Land(rng, u_range=(24, 488), v_range=(-232, 232))
AREAS = {"south": ((120, 226), 18), "town": ((118, 150), 74), "chapel": ((206, 132), 44), "wasps": ((44, 128), 26),
         "pool": ((130, 70), 34), "gate": ((92, 52), 14), "north": ((76, 22), 12)}
for k_, ((X_, Y_), r_) in AREAS.items():
    land.area(k_, uv(X_, Y_), r_, clearing=k_ not in ("town", "chapel"), roughness=0.3)
    ar = land.areas[k_]
    x_, y_ = ar["c"][0] + ar["c"][1], ar["c"][0] - ar["c"][1]
    assert 12 + ar["r"] <= x_ <= 243 - ar["r"] and 12 + ar["r"] <= y_ <= 243 - ar["r"], (k_, x_, y_)
for a_, b_, w_, road_ in (("south", "town", 13, True), ("town", "chapel", 11, False), ("town", "wasps", 10, False),
                          ("town", "pool", 11, False), ("town", "gate", 12, True), ("gate", "north", 12, True)):
    land.link(a_, b_, w_, bend=0.3, road=road_, road_material=PATH, pockets=(1, 2) if road_ else (1, 1))
d = Dresser(m, rng, land, "swamp")
m.blending("RoughCobble", 7, edge="BlendEdge")
# the drowned chapel stands out in the east fen, its door toward the village (placed before the land grows round it)
chapel_b = d.structure("chapel", "chapel", toward="town", scale=1.0, name="the drowned chapel")

# ---- 2. the centre: the dry ground and its fire basin --------------------------------------------------------------
land.paint_square(m, "town", 8, "RoughCobble")
vc = land.areas["town"]["c"]
land.taken |= {(int(vc[0]) + a, int(vc[1]) + 1 + b) for a in (-1, 0, 1) for b in (-1, 0, 1)}
land.paint_roads(m, PATH, width_squares=2.4, skip=land.reserved)

# ---- 3. the houses, and the chapel out in the fen ------------------------------------------------------------------
sm = StoryMap(m, rng, land, ID)
placed = sm.place_buildings(no_build={"south": 8, "wasps": 10, "pool": 12})
sm.connect_and_furnish(path_material=PATH)
d.furnish_structures()

# ---- 4. the land: the fen's pools, root walls, every way open ------------------------------------------------------
land.carve(margin=4.0)
pc_, wc_ = land.areas["pool"]["c"], land.areas["wasps"]["c"]
pools = []
for c_, r_ in ((pc_, land.areas["pool"]["r"] * 0.55), ((wc_[0] + 4, wc_[1] - 3), 3.5),
               ((vc[0] + 22, vc[1] + 10), 4.5), ((vc[0] - 14, vc[1] + 18), 4.0)):
    pools.append({s for s in land.squares if s not in land.roads and s not in land.taken
                  and math.hypot(s[0] - c_[0], s[1] - c_[1]) <= r_ * (1 + 0.22 * math.sin(3 * math.atan2(s[1] - c_[1], s[0] - c_[0])))})
water = set().union(*pools)
lanes = sm.keep_open({"south": 4, "wasps": 5, "pool": 4})
calm = water | lanes
outcrops = land.thickets(110, size=(1.0, 2.2), clear=1, avoid=frozenset(calm | land.taken))
land.open_links()
land.apply(m, wall=d.wall, floor=d.base)
d.cap_islands(outcrops)
d.ground()
for pool in pools:
    shore = [s for s in pool if any((s[0] + a, s[1] + b) not in pool for a, b in ((1, 0), (-1, 0), (0, 1), (0, -1)))]
    depth = bfs_distance(shore, pool, 6)
    for s in pool:
        m.floor[square_tile(*s)] = "WaterSwampDeep" if depth.get(s, 0) >= 2 else "WaterSwampShallow"
    land.water |= pool

# the chapel stands drowned: shallow fen water laps round it, three to five squares out (two left room for no
# buffer floor between its paving and the water), the path to its door kept dry
if chapel_b:
    from kit.village import _squares_of
    foot_ = _squares_of(chapel_b.footprint)
    near_ = bfs_distance(list(foot_), land.squares, 6)
    door_ = set()
    for d_ in chapel_b.entrances:
        o_ = land.door_outside(d_, foot_)
        if o_: door_ |= {(o_[0] + a, o_[1] + b) for a in range(-2, 3) for b in range(-2, 3)}
    moat = {s_ for s_, dd in near_.items() if 3 <= dd <= 5 and s_ not in lanes and s_ not in land.roads
            and s_ not in door_ and s_ not in foot_}
    for s_ in moat:
        m.floor[square_tile(*s_)] = "WaterSwampShallow"
    land.water |= moat

gate_halves, gate_pts, gate_sq = sm.gate_across(("gate", "north"), prefix="CausewayGate", material="Log",
                                                gate="BarredGate")
sm.exit_to("north", NEXT_MAP, prefix="CausewayExit")

# ---- 5. the places of the story ------------------------------------------------------------------------------------
vil = Village(m, rng, land)
m.obj_px("DunMirFlameBasinLit", *square_px(vc[0], vc[1] - 0.5))
for k in range(4):
    a = k * math.pi / 2 + math.pi / 4
    m.obj_px(("Bench1", "Bench4", "Bench5", "Bench2")[k], *square_px(vc[0] + 2.6 * math.cos(a), vc[1] - 0.5 + 2.6 * math.sin(a)))
vil.SIGN_TEXT = dict(vil.SIGN_TEXT, inn=q.text("The Eel and Lantern\nHot eel, warm beds", "Sign"),
                     store=q.text("Mirefen Trading Post\nNets, salt, steel", "Sign"))
for bid, b in placed:
    if bid.area == "town":
        for sc in BUILDINGS[bid.role]["scenes"]: vil.scene(b, sc, role=bid.role)
# the wasp nests in the west fen, Tam's hiding place among them
wsc = camps.Scene(m, rng, land, (wc_[0], wc_[1]))
for a in (0.5, 2.6, 4.6):
    wsc.put("WaspNest", *wsc.at(2.6, a))
tam_xy = wsc.px(0.6, 1.5)
# the leech's pool: bones on the shore, a broken trap
lsc = camps.Scene(m, rng, land, (pc_[0], pc_[1] + land.areas["pool"]["r"] * 0.7))
for k in range(5):
    lsc.put(rng.choice(("ArmBone", "LegBone", "Skull")), *lsc.at(rng.uniform(0.5, 2.0), rng.uniform(0, 6.3)))
lsc.put("Barrel2", *lsc.at(1.4, 1.0))
# caches in the reeds
caches = []
for near_, loot_ in ((wc_, [("Gold", {"Amount": 40}), "CurePoisonPotion", "CurePoisonPotion"]),
                     (land.areas["chapel"]["c"], [("Gold", {"Amount": 55}), "BluePotion", "RedPotion"]),
                     (pc_, [("Gold", {"Amount": 30}), "LeatherArmoredBoots"])):
    s_ = sm.hidden_spot(near_, r=(6, 12))
    if s_: caches.append(camps.cache(m, rng, land, (s_[0] + 0.5, s_[1] - 0.5), loot_, stump=True))
south_c = land.areas["south"]["c"]
camps.signpost(m, land, (south_c[0] + 2.5, south_c[1] - 1.5),
               q.text("MIREFEN\nKeep to the causeway. The fen keeps what it takes.", "Sign"))
gs_ = sm.road_near((gate_sq[0] + 3, gate_sq[1] + 3))
camps.signpost(m, land, (gs_[0] + 2.0, gs_[1] - 0.5),
               q.text("CAUSEWAY CLOSED\nBy order of the Elder, until the dead lie still.", "Sign"))

# ---- 6. what grows, light ------------------------------------------------------------------------------------------
keep_clear = {(int(vc[0]) + a, int(vc[1]) + b) for a in range(-6, 7) for b in range(-6, 7)}
n_trees, n_small = d.vegetate(keep_clear=keep_clear, groves=3)
d.scatter_open()
d.rim()
n_lights = d.lights()
vign = d.planter.forest_floor(4, kinds=("fallen_log", "stump"))
start_xy = square_px(south_c[0] + 0.5, south_c[1] - 0.5)
m.obj_px("PlayerStart", *start_xy)

# ---- 7. the people -------------------------------------------------------------------------------------------------
pop, B = sm.pop, sm.B
person = sm.person
vx, vy = square_px(*vc)
st = sm.room_of("foreman", "study")
hx, hy = sm.free_px(st) if st else square_px(vc[0] + 3, vc[1])
person("Con02a", "Aldwyn", hx, hy, "Haska")
wx, wy = square_px(south_c[0] + 1.5, south_c[1] - 4)
person("Con02a", "Julie2", wx, wy, "Wenna", face=start_xy)
ox, oy = sm.outside_door("home") or square_px(vc[0] - 3, vc[1])
person("Con03A", "Osborn", ox + 20, oy + 10, "Orrin", face=(vx, vy))
home_wp = pop.waypoint_path("TamHome", [(ox + 30, oy + 20)])
person("Con02a", "Bryan", *tam_xy, "Tam", action=0)
brask_home = next((b for bid, b in placed if bid.occupant.startswith("Brask")), None)
bx_, by_ = (sm.outside_door(building=brask_home) if brask_home else None) or square_px(vc[0], vc[1] + 3)
person("Con03A", "Millard", bx_ + 15, by_ + 15, "Brask", face=(vx, vy))
gx, gy = square_px(gate_sq[0] + 0.5, gate_sq[1] - 0.5)
gdx, gdy = vx - gx, vy - gy; gl = math.hypot(gdx, gdy) or 1
person("Con02a", "Bridge_Guard", gx + 70 * gdx / gl, gy + 70 * gdy / gl, "CausewayGuard", face=(vx, vy))
WARES = {"store": [(4, "CurePoisonPotion"), (3, "RedPotion"), (2, "BluePotion"), (3, "Meat"), (2, "Quiver"), (1, "Bow"),
                   (1, "ChainCoif"), (1, "ChainLeggings"), (1, "MorningStar"), (1, "WoodenShield")],
         "inn": [(5, "Meat"), (4, "Cider"), (3, "RedApple"), (2, "CurePoisonPotion")]}
GREET = {"store": q.text("Salt, nets, steel. Cure-potions, too: you'll want them out there, the fen bites.", "Shop"),
         "inn": q.text("Sit by the fire and dry off. Eel stew's hot. Nobody goes out after dark any more.", "Shop")}
n_shops = sm.shops(WARES, GREET)
FOLK = [("Con02a", "Tanya"), ("Con02a", "Heckler"), ("Con02a", "Morgan"), ("Con08a", "Gretchen"), ("Con02a", "Clyde")]
RUMOURS = ["They say Morvane was a priest once, at the old chapel, before the fen took it. Now he raises the drowned.",
           "Orrin's boy Tam went frogging in the west reeds yesterday. Orrin's half mad with worry.",
           "Brask lost two eel traps in the north pool. Says something as long as a boat took them.",
           "The causeway north is shut. Haska won't open it while the dead walk.",
           "Burn the leeches off with fire, my mother said. Or just don't go in the water."]
sm.townsfolk(FOLK, vc, q=q, rumours=RUMOURS, after=("dead:Morvane1", "The dead are quiet! Bless you, traveller."),
             pics=("MaidenPic3", "MalePic1", "MorganPic", "MaidenPic", "MalePic7"), radius=4.5)

# ---- 8. the fights -----------------------------------------------------------------------------------------------
chapel_r = next((r for r in (chapel_b.rooms if chapel_b else []) if r.kind == "chapel"), None)
crypt_r = next((r for r in (chapel_b.rooms if chapel_b else []) if r.kind == "crypt"), None)
morvane = sm.keepers(crypt_r or chapel_r, ["Necromancer"], "Morvane") if (crypt_r or chapel_r) else []
drowned = (sm.keepers(chapel_r, ["Skeleton", "Ghost", "Skeleton", "Ghost"], "Drowned") if chapel_r else []) + \
          (sm.keepers(crypt_r, ["SkeletonLord", "Skeleton"], "CryptDead") if crypt_r else [])
if crypt_r:
    loot_xy = sm.free_px(crypt_r, clear=26)
    m.obj_px("CryptChest3", *loot_xy, items=[("Gold", {"Amount": 90}), "SpellBook", "BluePotion", "WizardHelm"])
wasps = []
for k, a in enumerate((0.3, 1.5, 2.9, 4.1, 5.3)):
    x_, y_ = wsc.px(3.4, a)
    pop.creature("Wasp", x_, y_, action="guard", scr=f"Wasp{k + 1}", aggr=0.83)
    wasps.append(f"Wasp{k + 1}")
lx_, ly_ = square_px(pc_[0], pc_[1])
pop.creature("GiantLeech", lx_, ly_, action="guard", scr="GreatLeech", aggr=0.83, HealthMultiplier=3.0)
for k in range(2):
    pop.creature("GiantLeech", lx_ + (k * 2 - 1) * 60, ly_ + 40, action="guard", scr=f"Leechling{k + 1}", aggr=0.83)
sm.wild({"CarnivorousPlant": 3, "Bat": 2, "WillOWisp": 1, "SpittingSpider": 1, "Ghost": 1}, away_from=vc, min_away=24,
        avoid=(land.areas["chapel"]["c"], wc_, pc_, south_c, gate_sq, land.areas["north"]["c"]), per100=0.45, gap=6)

# ---- 9. the story ----------------------------------------------------------------------------------------------------
q.start([A.lock("CausewayGate1"), A.lock("CausewayGate2"), A.disable("CausewayExit1"), A.disable("CausewayExit2"),
         A.disable("CausewayExit3"),
         q.journal("The causeway has brought me to Mirefen, an eel-fishers' village at the edge of the Black Fen.", HINT)])
q.talker("Wenna", [
    q.say("The dead are lying still again. I can mend my nets in peace. Thank you, dear.",
          when=q.when(flag=q.dead("Morvane1")), who="Wenna"),
    q.say("Haska's house is the stone one by the fire. Tell her you'll go to the chapel; she'll listen to a sword.",
          when=q.when(flag="met_wenna"), who="Wenna"),
    q.say("A traveller, through the fen? You're brave or daft. Keep to the causeway. The dead walk the reeds at night "
          "now, ever since Morvane took the old chapel in the east fen. Elder Haska will tell you more.",
          do=[A.flag("met_wenna"), q.journal("Wenna, mending nets by the causeway, says the dead walk the fen since a "
                                             "necromancer, Morvane, took the old chapel. Elder Haska leads Mirefen.")],
          who="Wenna")])
q.talker("Haska", [
    q.say("Morvane is dead? Then the drowned will rest, and the causeway is yours. Here, with Mirefen's thanks.",
          when=q.when(flag=q.dead("Morvane1"), not_="haska_paid"),
          do=[A.gold(150), A.give("CurePoisonPotion", 2), A.give("SteelShield"), A.flag("haska_paid"),
              A.unlock("CausewayGate1"), A.unlock("CausewayGate2"), A.enable("CausewayExit1"), A.enable("CausewayExit2"),
              A.enable("CausewayExit3"),
              q.journal("Morvane is dead and the drowned lie still. Elder Haska opened the north causeway.", COMPLETED)],
          who="Haska"),
    q.say("The causeway is open. Walk it in daylight.", when=q.when(flag="haska_paid"), who="Haska"),
    q.say("The chapel is out east, across the fen path. He keeps to the crypt beneath it, among the drowned.",
          when=q.at("chapel", 1), who="Haska"),
    q.say("I am Haska; I speak for Mirefen. The old chapel in the east fen sank before my grandmother was born. This "
          "spring a necromancer called Morvane took it, and since then the drowned come up out of the reeds. I have shut "
          "the north causeway: nobody goes out to be dragged under. Kill Morvane and I will open it, and pay you besides.",
          do=[A.stage("chapel", 1), q.journal("Elder Haska has shut the north causeway until the necromancer Morvane, in "
                                              "the drowned chapel in the east fen, is dead.")], who="Haska")])
q.on_death("Morvane1", [A.print("Morvane crumples, and the cold goes out of the fen."),
                        q.journal("Morvane is dead. Elder Haska will want to know.", QUEST)])
q.talker("Orrin", [
    q.say("Tam! You found him! Here, it's all I have. Thank you, thank you.",
          when=q.when(flag="tam_home", not_="orrin_paid"),
          do=[A.gold(80), A.give("Meat", 2), A.give("RedPotion", 2), A.flag("orrin_paid"),
              q.journal("I found Tam in the reeds and he ran home. Orrin paid what he could.", COMPLETED)], who="Orrin"),
    q.say("He's eating like a wolf. He'll be all right.", when=q.when(flag="orrin_paid"), who="Orrin"),
    q.say("My boy, Tam. He went into the west reeds after frogs and he hasn't come back. There are wasps out there, "
          "great nests of them. Please find him.",
          do=[A.stage("tam", 1), q.journal("Orrin's son Tam went into the west reeds and has not come back. There are "
                                           "wasp nests out there.")], who="Orrin")])
q.talker("Tam", [
    q.say("You killed them? All the wasps? I'm going home! Thank you!", when=q.when(flag=q.dead(*wasps), not_="tam_home"),
          do=[A.flag("tam_home"), A.walk("Tam", home_wp[0])], who="Tam"),
    q.say("I'm going home now.", when=q.when(flag="tam_home"), who="Tam"),
    q.say("Don't move! They're everywhere! I can't run past them, they'll sting me to death!", who="Tam")])
q.talker("Brask", [
    q.say("The big one's dead? Ha! My traps are safe. Here, you earned it, and a leech-skin cloak.",
          when=q.when(flag=q.dead("GreatLeech"), not_="brask_paid"),
          do=[A.gold(70), A.give("MedievalCloak"), A.flag("brask_paid"),
              q.journal("I killed the great leech of the north pool. Brask paid me.", COMPLETED)], who="Brask"),
    q.say("Eels are biting again. Good days.", when=q.when(flag="brask_paid"), who="Brask"),
    q.say("Something in the north pool's taking my traps. A leech, long as a boat. Kill it and I'll make it worth "
          "your while.", do=[A.stage("leech", 1), q.journal("Brask the eel-catcher wants the great leech of the north "
                                                          "pool dead.")], who="Brask")])
q.talker("CausewayGuard", [
    q.say("Gate's open. Mind the soft ground.", when=q.when(flag="haska_paid"), who="Guard"),
    q.say("Causeway's shut by the Elder's word. Talk to Haska.", who="Guard")])
q.near(*square_px(*land.areas["chapel"]["c"]), 260, [A.print("Stone pokes up out of the black water: the drowned "
                                                             "chapel. Something moves inside.")])
for who_, pic_ in (("Haska", "AldwynPic"), ("Wenna", "MaidenPic2"), ("Orrin", "Townsman2Pic"), ("Tam", "MalePic5"),
                   ("Brask", "MalePic9"), ("CausewayGuard", "Warrior2Pic")):
    q.portrait(who_, pic_)

m.scripts.update(B.files(m.d["name"]))
m.scripts.update(q.files())

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    rooms_sidecar(placed + [(BuildingIdentity(role, area, nm, "Morvane"), b) for role, area, b, nm in d.structures],
                  os.path.join(OUT, f"{NAME}.rooms.json"))
    q.write_strings(OUT)
    lines = m.build(os.path.abspath(OUT))
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK", "SCRIPTS"))))
    print(f"land {len(land.squares)} squares | buildings {len(placed)}/{len(ID.buildings)} (missed: {', '.join(sm.missed) or 'none'}) "
          f"| trees {n_trees} | lights {n_lights} | shops {n_shops} | caches {len(caches)} | lines {len(q.strings)}")
