"""ModLab: creative additions to the base game, laid out to try one by one (dystopiannox/mods/MODLAB.md;
scripts: kit/behaviours/mods.go, wired by kit/mods.py). Every feature has a sign with its ID.

- the armoury (west end of the long gallery, by the start): six power weapons W1-W6 on the floor, a sign by each;
- the training yard (middle of the gallery, T1): creatures that wait frozen until you come near or strike them,
  and come back six seconds after they die, to try the weapons on;
- five pens along the north side of the gallery, M1-M5: a new monster in each, frozen until you step into its pen,
  back twenty seconds after it dies;
- the forge (south of the armoury, S1): an anvil, the forge plate (the grey stone patch), the smith, gold, and
  spare weapons to work or melt down. A sealed vault east of everything holds the forged copies the anvil hands out,
  and a sealed test cell is where the self-test runs on a dedicated server.

    py mapgen/designs/modlab.py [out_dir|-]
"""
import json, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO, px, uv_to_xy
from kit.npcs import Population
from kit.mods import Mods, WEAPONS, MONSTERS

HERE = os.path.dirname(os.path.abspath(__file__))
NAME = "ModLab"
rng = random.Random(7)
m = Spec(NAME, summary="Mod lab", description="[env:castle] Power weapons, new monsters and a smithing forge. "
         "Generated by Claude.", author="vdystopia (generated by Claude)", version="0.1", date="2026",
         type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
m.d["ambient"] = [200, 195, 190]
m.loot = False
P = lambda u, v: px(u, v)
TEXT = {}


def text(key, s):
    k = f"{NAME}:{key}"
    assert len(k) <= 31, k
    TEXT[k] = s
    return k


def sign(key, s, u, v, kind="Sign1"):
    return m.obj_px(kind, *P(u, v), xfer={"Text": text(key, s)})


def gate(u_mid, v):
    """A three-cell opening in the wall line at v (rect walls run along u in steps of 2)."""
    for u in (u_mid - 2, u_mid, u_mid + 2):
        m.remove_wall(*(int(c) for c in uv_to_xy(u, v)))


def weapon(t, u, v):
    return m.obj_px(t, *P(u, v))


# ---- the rooms ------------------------------------------------------------------------------------------------
m.room(200, 380, -20, 20, wall="BrickPlain", floor="CobbleStone")            # the long gallery
PEN_FLOORS = ["DirtLight2", "DirtHard", "LOTDPitted", "VolcanicCraggy", "TileDark"]
for k in range(5):                                                              # five pens on its north side
    m.room(200 + 36 * k, 236 + 36 * k, 20, 56, wall="BrickPlain", floor=PEN_FLOORS[k])
    gate(218 + 36 * k, 20)
m.room(200, 260, -56, -20, wall="BrickPlain", floor="DirtDark2")               # the forge, south of the armoury
gate(230, -20)

for u, v in ((204, 16), (204, -16), (300, 16), (300, -16), (376, 16), (376, -16), (204, -52), (256, -52)):
    m.obj_px("TorchPole", *P(u, v))

pop = Population(m, rng)
mods = Mods(m, pop)
mods.test_cell(400, -48)                                                        # sealed: the self-test's stand-ins

# ---- the armoury: W1-W6 --------------------------------------------------------------------------------------
sign("Welcome", "MODLAB - creative additions to Nox.\nArmoury here (W1-W6), training yard east (T1), monster pens "
     "north (M1-M5), the forge south (S1). Read the sign beside each thing. Warriors use W1, W2, W3, W5, W6; "
     "wizards and conjurers use W4.", 210, -6)
for k, wid in enumerate(WEAPONS):                                               # W1-W6 on the floor, a sign by each
    v = -15 + 6 * k
    mods.weapon(wid, *P(224, v), name=f"{wid}_{WEAPONS[wid]['name'].replace(' ', '')}")
    sign(wid, WEAPONS[wid]["text"], 220, v)
# a chest of spares by the door: a second Chakram Storm and Bloodthirst, and potions (power weapons work from chests)
m.obj_px("Chest4", *P(204, 12), items=[mods.weapon_item("W2"), mods.weapon_item("W5"), "RedPotion", "RedPotion",
                                       "RedPotion", "BluePotion"])

# ---- the training yard: T1 -----------------------------------------------------------------------------------
sign("T1", "T1 TRAINING YARD\nTry the weapons here. The creatures wait until you come near or strike them, and "
     "come back six seconds after they die.", 244, -14)
for k, (t, u, v) in enumerate((("GruntAxe", 262, -10), ("GruntAxe", 262, 10), ("Bear", 274, -4),
                               ("OgreBrute", 286, 8), ("Urchin", 286, -12), ("GruntAxe", 296, 0))):
    mods.trainee(t, *P(u, v), name=f"T1_Target{k + 1}", face=P(206, 0))

# ---- the pens: M1-M5 -----------------------------------------------------------------------------------------
for k, mid in enumerate(MONSTERS):                                              # M1-M5, one to a pen
    mid_u = 218 + 36 * k
    mods.monster(mid, *P(mid_u, 40), name=f"{mid}_{MONSTERS[mid]['name'][4:].replace(' ', '')}", wait=230.0,
                 respawn=20.0, face=P(mid_u, 20))
    sign(mid, MONSTERS[mid]["text"], mid_u + 5, 15)

# ---- the forge: S1 -------------------------------------------------------------------------------------------
sign("S1", "S1 THE FORGE (smithing)\nLay a weapon beside the anvil and step on the forge plate (the grey stone "
     "patch south-east of the anvil). A longsword, battle axe, the Flamebrand (W1) or the Quake Hammer (W3) becomes fine, superb, then masterwork: the game's own "
     "enchantments, stronger each tier (cost 100 / 200 / 400 gold). Any other weapon is melted down for 20 gold. Each "
     "piece raises the smith's level: tier N needs level N, and each level takes 8% off the price. Gold is in the "
     "west corner; talk to the smith (walk up) for his level.", 236, -24)
mods.forge(anvil=P(230, -40), smith=P(228, -42), plate=P(237, -36), vault_uv=(400, -12),
           tier0={"flamebrand": ["W1_Flamebrand"], "quake": ["W3_QuakeHammer"]})
m.obj_px("Bellows1", *P(222, -53))
for k in range(6):                                                    # 1,800 gold in the west corner
    m.obj_px("Gold", *P(205 + 3 * (k % 3), -48 - 4 * (k // 3)), xfer={"Amount": 300})
for k, t in enumerate(("Longsword", "Longsword", "BattleAxe", "BattleAxe")):   # spare weapons to work
    weapon(t, 252, -52 + 5 * k)
for k, t in enumerate(("Sword", "Sword", "Sword", "Staff", "OgreAxe")):        # and to melt down
    weapon(t, 246 + 3 * (k % 3), -27 - 3 * (k // 3))

m.obj_px("PlayerStart", *P(206, 0))
mods.attach()

out_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "out")
if out_dir != "-":
    lines = m.build(out_dir)
    with open(os.path.join(out_dir, f"{NAME}.strings.json"), "w", encoding="utf-8") as f:
        json.dump(TEXT, f, ensure_ascii=False, indent=1)
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK", "SCRIPTS"))))
print(f"creatures {len(pop.placed)} | signs {len(TEXT)} | mod calls {len(mods.calls)}")
