"""Mossford: a single-player river village in the woods, at roughly the scale of Con07B.

- A diamond-shaped town ringed by a forest hedge wall, with a river winding through the middle.
- Two wooden bridges carry the cross roads over the river; a dirt lane runs along each bank.
- Eight log cabins / halls with doors and furnished interiors, a cobbled square with a well,
  vegetable gardens, and lots of trees, bushes, flowers and water plants.
- Townsfolk copied from Con07B (scripts stripped) roam a waypoint network along the roads.

Single player only: map type Solo, one PlayerStart, no teams/crowns/flags, no .nxz.
"""
import math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO, CELL, uv_to_xy, px, rect_wall_cells, rect_tiles

DONOR = r"C:\GOG Games\Nox\maps\con07b\Con07B.map"
rng = random.Random(7)

m = Spec("Mossford",
         summary="Mossford - a river village in the woods",
         description="A small woodland town on both banks of a winding river. Generated by Claude.",
         author="vdystopia (generated by Claude)", version="0.1", date="Saturday, October 3 2026",
         type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
m.d["ambient"] = [150, 150, 140]

# ---------------------------------------------------------------- layout (u/v coordinates)
UA, UB, VA, VB = 184, 328, -72, 72          # town boundary (hedge wall)
BRIDGES = (220, 290)                        # u of the two cross roads / bridges
LANE_V = 42                                 # lanes at v = +42 and -42


def river_v(u):
    """Centre line of the river: meanders across the middle of the town."""
    t = (u - UA) / (UB - UA)
    return 15 * math.sin(t * math.pi * 1.7 + 0.5) + 4 * math.sin(u * 0.13)


DEEP, SHALLOW = 4.0, 8.5                     # half-widths in v units

HOUSES = [  # (u0, u1, v0, v1, wall material, kind); doors face the nearest lane
    (190, 204, 48, 62, "Log", "cabin"),
    (228, 246, 48, 64, "Log", "cabin"),
    (262, 276, 48, 62, "Log", "cabin"),
    (296, 318, 46, 64, "StuccoLightWood", "inn"),
    (190, 204, -62, -48, "Log", "cabin"),
    (228, 244, -64, -48, "Log", "cabin"),
    (276, 290, -62, -48, "Log", "cabin"),
    (298, 318, -66, -46, "StuccoLightWood", "chapel"),
]
PLAZA = (254, 36, 8.5)                       # u, v, radius (cobbled square, north side)
GARDEN = (250, 270, -64, -48)                # u0, u1, v0, v1 (south side)


def seg_dist(p, a, b):
    (pu, pv), (au, av), (bu, bv) = p, a, b
    du, dv = bu - au, bv - av
    t = max(0, min(1, ((pu - au) * du + (pv - av) * dv) / (du * du + dv * dv)))
    return math.hypot(pu - (au + t * du), pv - (av + t * dv))


def door_point(h):
    u0, u1, v0, v1 = h[:4]
    ud = (u0 + u1) // 2 // 2 * 2
    vd = v0 if v0 > 0 else v1                 # side facing the lane
    return ud, vd


ROADS = [((UA + 8, LANE_V), (UB - 8, LANE_V)), ((UA + 8, -LANE_V), (UB - 8, -LANE_V))]
ROADS += [((b, -LANE_V), (b, LANE_V)) for b in BRIDGES]
for h in HOUSES:                              # short paths from each door to its lane
    ud, vd = door_point(h)
    ROADS.append(((ud, vd), (ud, LANE_V if vd > 0 else -LANE_V)))


def on_road(u, v, w=2.6):
    return any(seg_dist((u, v), a, b) <= w for a, b in ROADS)


def in_house(u, v, margin=0):
    return any(h[0] - margin < u < h[1] + margin and h[2] - margin < v < h[3] + margin for h in HOUSES)


def in_plaza(u, v, extra=0):
    return math.hypot(u - PLAZA[0], v - PLAZA[1]) <= PLAZA[2] + extra


def in_garden(u, v, margin=0):
    return GARDEN[0] - margin <= u <= GARDEN[1] + margin and GARDEN[2] - margin <= v <= GARDEN[3] + margin


def on_bridge(u, v):
    return any(abs(u - b) <= 3.5 for b in BRIDGES) and abs(v - river_v(u)) <= SHALLOW + 2


def water(u, v):
    if on_bridge(u, v): return None
    d = abs(v - river_v(u))
    return "WaterDeep" if d <= DEEP else "WaterShallow" if d <= SHALLOW else None


def grass(u, v):
    n = math.sin(u * 0.11 + 1.3) + math.sin(v * 0.13) + 0.6 * math.sin((u + 2 * v) * 0.07)
    if abs(v - river_v(u)) < SHALLOW + 5 or n > 1.0: return "GrassDense"
    return "GrassSparse2" if n < -1.2 else "GrassNorm"


# ---------------------------------------------------------------- floor
for x, y in rect_tiles(UA, UB, VA, VB):
    u, v = x + y + 2, x - y                   # a tile is drawn centred on corner (x+1, y+1)
    if on_bridge(u, v): mat = "WoodSlatFloor"
    elif water(u, v): mat = water(u, v)
    elif in_plaza(u, v): mat = "RoughCobble"
    elif on_road(u, v): mat = "DirtLight2"
    elif in_garden(u, v): mat = "DirtDark2"
    else: mat = grass(u, v)
    m.tile(x, y, mat)

for h in HOUSES:                              # interiors (no edge blending with outside)
    for x, y in rect_tiles(*h[:4]):
        m.tile(x, y, "OakWoodFloor")

# soft edges: higher priority spills onto lower (learned from stock maps)
m.blending("WaterDeep", 6)
m.blending("WaterShallow", 5, "ShallowWaterAndGrass")
m.blending("RoughCobble", 4)
m.blending("DirtLight2", 3)
m.blending("DirtDark2", 3)
m.blending("GrassDense", 2)
m.blending("GrassNorm", 1)
m.blending("GrassSparse2", 0)

# ---------------------------------------------------------------- walls
for i, (x, y) in enumerate(sorted(rect_wall_cells(UA, UB, VA, VB))):
    m.wall(x, y, "DecidiousWallGreen", variation=rng.randrange(8))

# Invisible walls on the river's edge cells keep players out of the water (as stock maps do);
# water next to a bridge gets them too, which forms the bridge railings.
for (x, y), mat in list(m.floor.items()):
    if mat not in ("WaterDeep", "WaterShallow"): continue
    u, v = x + y + 2, x - y
    if not (UA < u < UB and VA < v < VB): continue
    if any(m.floor.get((x + dx, y + dy)) not in ("WaterDeep", "WaterShallow", None)
           for dx, dy in ((1, 1), (1, -1), (-1, 1), (-1, -1), (2, 0), (-2, 0), (0, 2), (0, -2))):
        m.wall(x, y, "InvisibleWallSet")

for h in HOUSES:
    u0, u1, v0, v1, mat, kind = h
    for x, y in rect_wall_cells(u0, u1, v0, v1):
        m.wall(x, y, mat, variation=rng.randrange(4))
    ud, vd = door_point(h)
    m.door("WoodenDoor", tuple(int(c) for c in uv_to_xy(ud, vd)), "\\")

# ---------------------------------------------------------------- house interiors


def furnish(h):
    u0, u1, v0, v1, mat, kind = h
    back = v1 - 4 if v0 > 0 else v0 + 4       # wall opposite the door
    mid_u, mid_v = (u0 + u1) / 2, (v0 + v1) / 2
    if kind == "cabin":
        m.obj("Bed1", u0 + 4, back)
        m.obj("Nightstand2", u0 + 7, back)
        m.obj("RoundTableWithFood", mid_u + 2, mid_v)
        m.obj("DarkWoodenChair1", mid_u - 1, mid_v)
        m.obj("DarkWoodenChair3", mid_u + 5, mid_v)
        m.obj("Candleabra1", u1 - 3, back)
        m.obj(rng.choice(["Chest1", "Barrel2", "DarkCrate2"]), u1 - 3, mid_v)
        m.obj("BearskinRug1", mid_u, (mid_v + back) / 2)
    elif kind == "inn":
        m.obj("FreestandingFireplace", mid_u, back)
        for du in (-6, 0, 6):
            m.obj("RoundTableWithFood", mid_u + du, mid_v - 1)
            m.obj("DarkWoodenChair5", mid_u + du - 2, mid_v - 1)
            m.obj("DarkWoodenChair1", mid_u + du + 2, mid_v - 1)
        m.obj("Barrel", u0 + 3, back); m.obj("Barrel2", u0 + 3, back - 3); m.obj("WaterBarrel", u1 - 3, back)
        m.obj("Candleabra3", u0 + 3, mid_v); m.obj("Candleabra3", u1 - 3, mid_v)
    elif kind == "chapel":
        m.obj("Candleabra3", mid_u - 5, back); m.obj("Candleabra3", mid_u + 5, back)
        m.obj("Desk1", mid_u, back)
        for du in (-5, 0, 5):
            m.obj("Bench5", mid_u + du, mid_v + (2 if v0 > 0 else -2))
        m.obj("FlowersWhiteDense", mid_u - 8, back); m.obj("FlowersPurpleDense", mid_u + 8, back)


for h in HOUSES:
    furnish(h)

# ---------------------------------------------------------------- town features
pu, pv, pr = PLAZA
m.obj("Well", pu, pv)
m.obj("TorchPole", pu + 6, pv + 6); m.obj("TorchPole", pu - 6, pv - 6)
m.obj("Bench5", pu - 6, pv + 5); m.obj("Bench5", pu + 6, pv - 5)
m.obj("FlowersYellowDense", pu + 7, pv - 1); m.obj("FlowersPurpleDense", pu - 7, pv + 1)

for u in range(UA + 14, UB - 8, 20):          # lanterns along both lanes
    for side in (1, -1):
        if not in_house(u, side * (LANE_V + 4), 2):
            m.obj("VictorianLantern1", u, side * (LANE_V + 4))

gu0, gu1, gv0, gv1 = GARDEN                   # vegetable rows
crops = ["GardenCabbage", "GardenCorn", "GardenTomatos"]
for i, u in enumerate(range(gu0 + 3, gu1 - 1, 4)):
    for v in range(gv0 + 3, gv1 - 1, 3):
        m.obj(crops[i % 3], u, v)
m.obj("Straw1", gu1 + 3, gv1 - 3); m.obj("Straw2", gu1 + 4, gv0 + 4)

for u in range(UA + 8, UB - 4, 22):           # river life
    rv = river_v(u)
    if not on_bridge(u, rv):
        m.obj("AmbBrook1", u, rv)
    for _ in range(3):
        uu, vv = u + rng.uniform(-9, 9), rv + rng.uniform(-DEEP - 3, DEEP + 3)
        if water(uu, vv): m.obj(rng.choice(["LillyPad", "LillyPadFlower", "LillyPadSparse1", "LillyPadDense1"]), uu, vv)

# ---------------------------------------------------------------- nature
placed = []


def free(u, v, r):
    return all(math.hypot(u - a, v - b) >= r + rr for a, b, rr in placed)


def clear_ground(u, v, margin):
    return (UA + margin < u < UB - margin and VA + margin < v < VB - margin and not water(u, v)
            and abs(v - river_v(u)) > SHALLOW + 1.5 and not on_road(u, v, 2.6 + margin)
            and not in_house(u, v, margin + 1) and not in_plaza(u, v, margin + 1)
            and not in_garden(u, v, margin) and not on_bridge(u, v))


TREES = ["TreeForest01", "TreeForest02", "TreeForest03", "TreeForest04", "TreeForest05", "TreeForest07",
         "TreeForest08", "TreeForest13", "TreeForest14", "TreeForest15", "TreeForest16", "TreeForest17",
         "TreeGalava02", "TreeGalava03", "TreeGalava07", "TreeGalava09"]
for _ in range(9000):                         # trees: dense forest belt, scattered inside, along the river
    u, v = rng.uniform(UA, UB), rng.uniform(VA, VB)
    edge = min(u - UA, UB - u, v - VA, VB - v)
    bank = abs(v - river_v(u)) - SHALLOW
    spacing = 3.2 if edge < 12 else 4.0 if 1.5 < bank < 7 else 8.0
    if clear_ground(u, v, 2.0) and free(u, v, spacing):
        placed.append((u, v, spacing / 2))
        m.obj(rng.choice(TREES), u, v)

SMALL = (["Bush6", "Bush7", "Bush8", "Bush9", "Bush11", "Bush12"] * 2 + ["Plant4", "Plant5", "PlantForest1",
         "PlantForest2", "PlantFern1", "PlantFern2", "FoliageDense1", "FoliageDense2", "FoliageSparse1"] * 2 +
         ["FlowersYellowSparse", "FlowersPurpleSparse", "FlowersWhiteSparse", "FlowersBlueSparse",
          "GrassTuft2", "GrassTuft3", "Mushroom1", "Mushroom3", "Mushroom4", "Mushroom5"])
for _ in range(6000):
    u, v = rng.uniform(UA, UB), rng.uniform(VA, VB)
    if clear_ground(u, v, 0.8) and free(u, v, 1.2):
        placed.append((u, v, 1.2))
        m.obj(rng.choice(SMALL), u, v)

for _ in range(400):                          # logs and rocks in the forest belt
    u, v = rng.uniform(UA, UB), rng.uniform(VA, VB)
    if min(u - UA, UB - u, v - VA, VB - v) < 12 and clear_ground(u, v, 2.0) and free(u, v, 2.5):
        placed.append((u, v, 2.5))
        m.obj(rng.choice(["ForestLog03", "Rock1", "Boulder"]), u, v)

for _ in range(14):                           # ambient wildlife sounds
    u, v = rng.uniform(UA + 6, UB - 6), rng.uniform(VA + 6, VB - 6)
    m.obj(rng.choice(["AmbBird1", "AmbBird2", "AmbCricket1"]), u, v)

# ---------------------------------------------------------------- townsfolk and their paths
wp_at = {}


def wp(u, v):
    key = (round(u), round(v))
    if key not in wp_at:
        x, y = px(u, v)
        wp_at[key] = m.waypoint(x, y)
    return wp_at[key]


def path(a, b, step=8):
    n = max(1, round(math.hypot(b[0] - a[0], b[1] - a[1]) / step))
    pts = [(a[0] + (b[0] - a[0]) * i / n, a[1] + (b[1] - a[1]) * i / n) for i in range(n + 1)]
    for p, q in zip(pts, pts[1:]):
        m.link(wp(*p), wp(*q))


for side in (1, -1):                          # lanes, split at the cross roads so they share nodes
    stops = [UA + 8] + list(BRIDGES) + [UB - 8]
    for a, b in zip(stops, stops[1:]):
        path((a, side * LANE_V), (b, side * LANE_V))
for b in BRIDGES:                             # cross roads over the bridges
    path((b, -LANE_V), (b, LANE_V))
path((PLAZA[0], LANE_V), (PLAZA[0], PLAZA[1]))

ROAMERS = ["Shari", "Kayla", "Eowynn", "Dorian", "Jorgan", "Civvy4", "Albi", "Civvy3",
           "Civvy3", "Civvy4", "Jorgan", "Kayla"]
spots = [(UA + 20, LANE_V), (UA + 50, -LANE_V), (BRIDGES[0], 20), (BRIDGES[1], -20), (UB - 30, LANE_V),
         (UB - 40, -LANE_V), (PLAZA[0], LANE_V), (240, -LANE_V), (BRIDGES[0], -LANE_V), (BRIDGES[1], LANE_V),
         (300, LANE_V), (206, -LANE_V)]
for name, (u, v) in zip(ROAMERS, spots):
    m.clone(DONOR, "Con07B:" + name, *px(u + rng.uniform(-1, 1), v + rng.uniform(-1, 1)))

inn, chapel = HOUSES[3], HOUSES[7]
m.clone(DONOR, "Con07B:Max", *px((inn[0] + inn[1]) / 2 - 4, (inn[2] + inn[3]) / 2 - 3))
m.clone(DONOR, "Con07B:Priest", *px((chapel[0] + chapel[1]) / 2, chapel[2] + 6))
m.clone(DONOR, "Con07B:Grunbar", *px(PLAZA[0] + 3, PLAZA[1] - 4))
m.clone(DONOR, "Con07B:Undertaker", *px(GARDEN[0] - 3, GARDEN[3] + 3))

# ---------------------------------------------------------------- player, lighting
m.obj("PlayerStart", BRIDGES[0] - 6, -LANE_V + 1)
m.polygon("Mossford:Town", (150, 150, 140),
          [px(UA, VA), px(UA, VB), px(UB, VB), px(UB, VA)])

if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "out")
    print("\n".join(m.build(os.path.abspath(out))))
