"""NPC lab: one section for each way creatures are placed and moved (rules/NPCS.md, kit/npcs.py):
- a walled fort whose gate guards stand facing out; the sentry among them calls out and rouses the ogres inside;
- swordsmen roaming a ring of linked waypoints round the fort (Westwood's unscripted roam);
- a skeleton lord walking a scripted patrol route, pausing at each end;
- a wolf pack: the leader wanders, the others follow; all hunt together; when the leader dies they flee;
- an ogre warlord with brutes keeping to him (Westwood's unscripted escort);
- bats and rats that flee when hit;
- skeletons waiting unseen by a chest until the player comes near;
- townsfolk walking between the spots of a little square;
- single creatures idle and on guard by the walls, as Westwood leaves most of its creatures.

    py mapgen/designs/npclab.py [out_dir|-]
"""
import math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO, px, uv_to_xy
from kit.npcs import Population

HERE = os.path.dirname(os.path.abspath(__file__))
rng = random.Random(3)
m = Spec("NpcLab", summary="NPC lab", description="[env:forest] Creatures placed and moved in every way the kit knows. "
         "Generated by Claude.", author="vdystopia (generated by Claude)", version="0.1", date="2026",
         type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
m.d["ambient"] = [170, 165, 160]
P = lambda u, v: px(u, v)                       # world pixels of a uv point

# the field and the fort (uv); the fort's gate is a 4-unit gap in its SW wall
m.room(180, 340, -80, 80, wall="BrickPlain", floor="GrassNorm")
m.room(240, 280, -20, 20, wall="StoneWall" if False else "BrickPlain", floor="CobbleStone")
for u in (258, 260, 262):                       # the gate: open the SW wall ('\\' line at v = -20)
    m.remove_wall(*(int(c) for c in uv_to_xy(u, -20)))
pop = Population(m, rng)
B = pop.behaviours

# 1. the gate: two guards facing out, the sentry rouses the ogres in the yard
g1, g2 = P(256, -24), P(264, -24)
out = P(260, -40)
pop.creature("GruntAxe", *g1, action="guard", face=out, scr="GateSentry")
pop.creature("GruntAxe", *g2, action="guard", face=out, scr="GateGuard")
for k, (u, v) in enumerate(((252, 4), (268, 8), (262, 12))):
    pop.creature("OgreBrute", *P(u, v), action="idle", scr=f"YardOgre{k + 1}")
B.sentry("GateSentry", out, rouse=["GateGuard", "YardOgre1", "YardOgre2", "YardOgre3"])

# 2. the roam ring round the fort: linked waypoints, swordsmen with the roam action (no script)
ring = [P(260 + 32 * math.cos(a), 0 + 32 * math.sin(a)) for a in [k * math.pi / 4 for k in range(8)]]
pop.roam_loop(ring, "Swordsman", n=2, prefix="Ring")

# 3. a scripted patrol: the skeleton lord walks the north-east path and back, pausing at each end
route = pop.waypoint_path("NEPatrol", [P(200, 50), P(230, 60), P(260, 66), P(300, 62)])
pop.creature("SkeletonLord", *P(200, 50), action="idle", scr="PatrolSkel")
B.patrol("PatrolSkel", route, pause=3.0, loop=False)

# 4. the wolf pack in the east
lead = pop.creature("BlackWolf", *P(320, 40), scr="PackLeader")
mem = []
for k, (du, dv) in enumerate(((-3, 2), (2, 3), (3, -2))):
    pop.creature("Wolf", *P(320 + du, 40 + dv), scr=f"PackWolf{k + 1}"); mem.append(f"PackWolf{k + 1}")
B.pack("PackLeader", mem)

# 5. Westwood's escort: an ogre warlord and his brutes in the south-east
pop.escort("OgreWarlord", P(320, -50), "OgreBrute", [P(316, -54), P(324, -46)], leader_action="guard")

# 6. skittish bats and rats in the west
for k in range(4):
    pop.creature("Bat", *P(200 + rng.uniform(-6, 6), -40 + rng.uniform(-6, 6)), scr=f"Bat{k + 1}"); B.skittish(f"Bat{k + 1}")
for k in range(3):
    pop.creature("Rat", *P(214 + rng.uniform(-5, 5), -56 + rng.uniform(-5, 5)), scr=f"Rat{k + 1}"); B.skittish(f"Rat{k + 1}", 2.0)

# 7. the ambush: a chest in the north corner, skeletons waiting unseen round it
chest = P(204, 66)
m.obj_px("Chest4", *chest)
names = []
for k in range(5):
    a = k * 2 * math.pi / 5
    pop.creature("Skeleton", chest[0] + 70 * math.cos(a), chest[1] + 70 * math.sin(a), scr=f"Ambusher{k + 1}")
    names.append(f"Ambusher{k + 1}")
B.ambush(names, chest, reach=160)

# 8. townsfolk round a little square in the south
spots = pop.waypoint_path("Square", [P(300, -74), P(318, -66), P(306, -62), P(292, -68)])
m.obj_px("Fountain" if False else "Well", *P(305, -68))
for k, t in enumerate(("Maiden", "Maiden", "Maiden")):
    pop.creature(t, *P(300 + 4 * k, -70), scr=f"Folk{k + 1}", aggr=0.0)
    B.townsfolk(f"Folk{k + 1}", spots, linger=4.0)

# 9. Westwood's commonest: single creatures idle or on guard about 2 cells from a wall, far from the start
for t, (u, v), act in (("Zombie", (186, -10), "idle"), ("Zombie", (186, 20), "idle"), ("Scorpion", (334, 0), "guard"),
                       ("Spider", (244, 76), "idle"), ("Urchin", (284, 76), "guard")):
    pop.creature(t, *P(u, v), action=act)

m.obj_px("PlayerStart", *P(332, -76))
m.scripts.update(B.files(m.d["name"]))

out_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "out")
if out_dir != "-":
    lines = m.build(out_dir)
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK", "SCRIPTS"))))
print(f"creatures {len(pop.placed)} | behaviours {len(B.calls)}")
