"""Rimehold: a hunters' outpost under the Rime Pass, and the story of the dark shrine (chapter two after Thornwick
and the north road; ice biome, rules/BIOMES.md). Built with kit/story.py on the ice palette (kit/biome.py).

The story
- The road from the south (TNorth) climbs to Rimehold, a walled-in clearing of log houses: the warden's house, the
  hunters' lodge, the trading post, the Frozen Kettle inn, Inga's house and the shrine keeper's cottage.
- Main quest, the Dark Shrine: on the frozen lake east of the outpost stands the old shrine of standing stones. Its
  heartstone (a Diamond) kept the pass warm enough to cross; the ogres of the old keep in the north-west stole it and
  the flame died. Warden Hrolf has sealed the pass gate: no one crosses until the shrine burns. Skarg, the ogres' chief,
  carries the heartstone. Set it back in the shrine (walk to it with the Diamond) and the flame returns, the gate
  opens and the pass (the exit) leads on.
- A troll lurks on the lake and comes for whoever first walks out to the shrine.
- The Lost Trapper: Oskar went into the ice cave east of the lake after crystal and never came back. His wife Inga
  asks for news. His remains lie in the cave among the spiders, with his crossbow; bring it to her.
- The Great Bear: Torvald, master of the hunters' lodge, has a bounty on the great bear of the west pines.
- The trading post and the inn buy and sell; caches lie in the snow; the outpost's folk each know something.

    py mapgen/designs/rimehold.py [seed]
"""
import math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO, CELL
from kit.identity import MapIdentity, AreaIdentity, BuildingIdentity, rooms_sidecar
from kit.layout import Land, square_tile, square_px
from kit.biome import Dresser
from kit.village import Village
from kit.quests import QuestBook, A, QUEST, COMPLETED, HINT
from kit.story import StoryMap
from kit import camps

SEED = int(sys.argv[1]) if len(sys.argv) > 1 else 5
rng = random.Random(SEED)
NAME = "Rimehold"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "out", "rimehold")
NEXT_MAP = "RimePass"
PATH = "CaveHardTan"                 # the trodden ways: bare rock through the snow (a floor of the ice palette)


def uv(X, Y):
    return (X + Y, X - Y)


ID = MapIdentity(
    name=NAME,
    theme="a hunters' outpost under the Rime Pass: log houses round a fire-basin yard, a frozen lake with a dead "
          "shrine, an ice cave, the snow pines and an old keep the ogres hold",
    environment="town", mood="cold, waiting",          # a snow town: compared with Westwood's towns
    areas=[AreaIdentity("south", "where the road from the south arrives: the start"),
           AreaIdentity("outpost", "Rimehold's yard and its houses", landmark="the fire basin"),
           AreaIdentity("lake", "the frozen lake and its dark shrine", landmark="the shrine of standing stones"),
           AreaIdentity("icecave", "the ice cave where Oskar was lost"),
           AreaIdentity("pines", "the snow pines, the great bear's ground"),
           AreaIdentity("keep", "the old keep the ogres hold"),
           AreaIdentity("gate", "the pass gate, sealed"),
           AreaIdentity("north", "the Rime Pass: the way on")],
    buildings=[BuildingIdentity("foreman", "town", "the warden's house", "Warden Hrolf"),
               BuildingIdentity("bunkhouse", "town", "the hunters' lodge", "Torvald and his hunters"),
               BuildingIdentity("store", "town", "the trading post", "the trader"),
               BuildingIdentity("inn", "town", "The Frozen Kettle", "the innkeeper"),
               BuildingIdentity("home", "town", "Inga's house", "Inga"),
               BuildingIdentity("cottage", "town", "", "Ylva the shrine keeper")])

m = Spec(NAME, summary="Rimehold", description=f"[env:{ID.environment}] {ID.theme[0].upper() + ID.theme[1:]}. "
         f"Generated by Claude.", author="vdystopia (generated by Claude)", version="1", date="2026", type=SOLO,
         minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
q = QuestBook(NAME)

# ---- 1. the plan ---------------------------------------------------------------------------------------------------
land = Land(rng, u_range=(24, 488), v_range=(-232, 232))
AREAS = {"south": ((116, 228), 18), "town": ((112, 160), 80), "lake": ((176, 112), 46), "icecave": ((222, 158), 26),
         "pines": ((52, 120), 30), "keep": ((62, 52), 34), "gate": ((160, 52), 14), "north": ((176, 20), 12)}
for k_, ((X_, Y_), r_) in AREAS.items():
    land.area(k_, uv(X_, Y_), r_, clearing=k_ != "town", roughness=0.24)
    ar = land.areas[k_]
    x_, y_ = ar["c"][0] + ar["c"][1], ar["c"][0] - ar["c"][1]
    assert 12 + ar["r"] <= x_ <= 243 - ar["r"] and 12 + ar["r"] <= y_ <= 243 - ar["r"], (k_, x_, y_)
for a_, b_, w_, road_ in (("south", "town", 14, True), ("town", "lake", 14, False), ("lake", "icecave", 11, False),
                          ("town", "pines", 12, False), ("pines", "keep", 12, False), ("town", "gate", 13, True),
                          ("gate", "north", 12, True)):
    land.link(a_, b_, w_, bend=0.24, road=road_, road_material=PATH, pockets=(1, 2) if road_ else (0, 1))
d = Dresser(m, rng, land, "ice")
m.blending("RoughCobble", 7, edge="BlendEdge")

# the ogres' keep in the north-west, its door toward the pines path (placed before the land grows round it)
keep_b = d.structure("ogre_keep", "keep", toward="pines", scale=1.0, name="the old keep")

# ---- 2. the centre: the yard and its fire basin -------------------------------------------------------------------
land.paint_square(m, "town", 9, "RoughCobble")
vc = land.areas["town"]["c"]
land.taken |= {(int(vc[0]) + a, int(vc[1]) + 1 + b) for a in (-1, 0, 1) for b in (-1, 0, 1)}
land.paint_roads(m, PATH, width_squares=2.6, skip=land.reserved)

# ---- 3. the outpost's houses from the yard outwards ----------------------------------------------------------------
sm = StoryMap(m, rng, land, ID)
placed = sm.place_buildings(no_build={"south": 8})
sm.connect_and_furnish(path_material=PATH)
furnished = d.furnish_structures()

# ---- 4. the land: the lake in its hollow, cliffs breaking the snowfields, every way open ------------------------------
land.carve(margin=4.0)
lc = land.areas["lake"]["c"]
lake = {s for s in land.squares if land._in_area((s[0] + 0.5, s[1] - 0.5), dict(land.areas["lake"], r=land.areas["lake"]["r"] * 0.6))
        and s not in land.roads}
shrine = (lc[0] - 2, lc[1] + 7)
lanes = sm.keep_open({"south": 4, "icecave": 6, "pines": 5})
land.taken |= {(int(shrine[0]) + a, int(shrine[1]) + 1 + b) for a in range(-4, 5) for b in range(-4, 5)}
calm = lake | lanes | {s for s in land.squares if math.hypot(s[0] - lc[0], s[1] - lc[1]) < 6}
outcrops = land.thickets(160, size=(1.2, 2.6), clear=1, avoid=frozenset(calm))
land.open_links()
land.apply(m, wall=d.wall, floor=d.base)
d.cap_islands(outcrops)
for s in lake: m.floor[square_tile(*s)] = "IceFloorDark"
d.ground()

# the pass gate: a wall across the road beyond the gate clearing, sealed
gate_halves, gate_pts, gate_sq = sm.gate_across(("gate", "north"), prefix="PassGate", material="Cobblestone")
sm.exit_to("north", NEXT_MAP, prefix="PassExit")

# ---- 5. the places of the story ------------------------------------------------------------------------------------
# the dark shrine: a ring of standing stones on the lake's north shore, the empty socket of the heartstone at its middle
for k in range(7):
    a = k * 2 * math.pi / 7
    m.obj_px("ObeliskPrimitive", *square_px(shrine[0] + 2.6 * math.cos(a), shrine[1] + 2.6 * math.sin(a)))
sx, sy = square_px(*shrine)
m.obj_px("MineCrystal05", sx, sy, scr="ShrineStone")
m.obj_px("ColorLight", sx, sy - 5, scr="ShrineLight", xfer=d._light_xfer((255, 170, 90), 260, 70))
d.taken |= {(int(shrine[0]) + a, int(shrine[1]) + 1 + b) for a in range(-4, 5) for b in range(-4, 5)}
# the yard: a fire basin at its middle, benches round it
vil = Village(m, rng, land)
m.obj_px("DunMirFlameBasinLit", *square_px(vc[0], vc[1] - 0.5))
for k in range(4):
    a = k * math.pi / 2 + math.pi / 4
    vil.spec.obj_px(("Bench1", "Bench4", "Bench5", "Bench2")[k], *square_px(vc[0] + 2.6 * math.cos(a), vc[1] - 0.5 + 2.6 * math.sin(a)))
vil.SIGN_TEXT = dict(vil.SIGN_TEXT, inn=q.text("The Frozen Kettle\nFire, broth and a bed", "Sign"),
                     store=q.text("Rimehold Trading Post\nFurs bought, gear sold", "Sign"),
                     bunkhouse=q.text("The Hunters' Lodge", "Sign"))
from kit.identity import BUILDINGS
for bid, b in placed:
    for sc in BUILDINGS[bid.role]["scenes"]: vil.scene(b, sc, role=bid.role)
# Oskar's end in the ice cave: his bones, his crossbow by them, the crystal he came for
cc = land.areas["icecave"]["c"]
osk = camps.Scene(m, rng, land, (cc[0] + 1.5, cc[1] + 1.0))
for t, r, a in (("Skull", 0.0, 0), ("ArmBone", 0.6, 1.0), ("LegBone", 0.8, 2.4), ("ArmBone", 0.7, 4.0), ("LegBone", 0.9, 5.2)):
    osk.put(t, *osk.at(r, a))
osk.put("CrossBow", *osk.at(1.2, 3.0))
osk.put("Quiver", *osk.at(1.4, 1.8))
d.clusters({"MineCrystal05": 4, "MineCrystal02": 2, "MineCrystal04": 2},
           [s for s in land.squares if land._in_area((s[0] + 0.5, s[1] - 0.5), land.areas["icecave"]) and s not in land.taken],
           5, size=(4, 7), radius=1.6, gap=0.8, spacing=5.0, core="MineCrystalUp03")
# the cave's own dim blue light, as Westwood darkens the cave of its Wastelands ([35, 35, 71] against 70, 70, 140)
rc_ = land.areas["icecave"]["r"] * 1.15
m.polygon(f"{NAME}:IceCave", (35, 35, 71),
          [square_px(cc[0] + rc_ * math.cos(a), cc[1] + rc_ * math.sin(a)) for a in (k * math.pi / 8 for k in range(16))])
camps.signpost(m, land, (cc[0] - 5, cc[1] + 1), q.text("Crystal here. Good seam. Back before dark. - O.", "Sign"), kind="PlankSign2")
# the bear's ground in the pines: a den of rock and bones
pc = land.areas["pines"]["c"]
bear_spots = camps.wolf_den(m, rng, land, (pc[0] - 2, pc[1]), vc)
# caches in the snow
caches = []
for near_, loot_ in ((pc, [("Gold", {"Amount": 60}), "RedPotion", "RedPotion"]),
                     (cc, [("Gold", {"Amount": 90}), "BluePotion", "CurePoisonPotion"]),
                     (land.areas["keep"]["c"], [("Gold", {"Amount": 50}), "ChainLeggings"])):
    s_ = sm.hidden_spot(near_, r=(5, 11))
    if s_: caches.append(camps.cache(m, rng, land, (s_[0] + 0.5, s_[1] - 0.5), loot_))
south_c = land.areas["south"]["c"]
camps.signpost(m, land, (south_c[0] + 2.5, south_c[1] - 1.5),
               q.text("RIMEHOLD\nLast shelter before the Rime Pass.", "Sign"))
gs_ = sm.road_near((gate_sq[0] + 3, gate_sq[1] - 3))
camps.signpost(m, land, (gs_[0] + 2.0, gs_[1] - 0.5),
               q.text("THE PASS IS SEALED\nNo crossing while the shrine is dark. - Hrolf, Warden", "Sign"))

# ---- 6. snow trees along the cliffs, rocks, cold light -------------------------------------------------------------
keep_clear = set(lake) | {(int(vc[0]) + a, int(vc[1]) + b) for a in range(-6, 7) for b in range(-6, 7)}
n_trees, n_small = d.vegetate(keep_clear=keep_clear, groves=3)
d.scatter_open(scale=0.45)            # an outpost on Westwood's sparse ice: fewer loose pieces
d.rim(scale=0.6)
n_lights = d.lights(scale=0.5)
piles = d.planter.rock_piles(max(4, len(land.squares) // 1000))
start_xy = square_px(south_c[0] + 0.5, south_c[1] - 0.5)
m.obj_px("PlayerStart", *start_xy)

# ---- 7. the people ---------------------------------------------------------------------------------------------------
pop, B = sm.pop, sm.B
vx, vy = square_px(*vc)
person = sm.person
st = sm.room_of("foreman", "study")
hx, hy = sm.free_px(st) if st else square_px(vc[0] + 3, vc[1])
person("Con03A", "Lance", hx, hy, "Hrolf")
ix, iy = sm.outside_door("home") or square_px(vc[0] - 3, vc[1])
person("Con02a", "Lydia", ix + 20, iy + 10, "Inga", face=(vx, vy))
lodge = sm.room_of("bunkhouse", "barracks")
tx, ty = sm.free_px(lodge) if lodge else square_px(vc[0], vc[1] + 3)
person("Con03A", "Janero", tx, ty, "Torvald")
yx, yy = sm.outside_door("cottage") or square_px(vc[0], vc[1] - 3)
person("Con02a", "Julie", yx + 15, yy + 15, "Ylva", face=(vx, vy))
gx, gy = square_px(gate_sq[0] + 0.5, gate_sq[1] - 0.5)
lx_, ly_ = square_px(*lc)
gdx, gdy = lx_ - gx, ly_ - gy; gl = math.hypot(gdx, gdy) or 1
person("Con02a", "Contest_Guard", gx + 70 * gdx / gl, gy + 70 * gdy / gl, "PassGuard", face=(lx_, ly_))
WARES = {"store": [(4, "RedPotion"), (3, "BluePotion"), (2, "CurePoisonPotion"), (3, "Meat"), (2, "Quiver"),
                   (1, "Bow"), (1, "MedievalCloak"), (1, "LeatherArmoredBoots"), (1, "ChainCoif"), (1, "Longsword")],
         "inn": [(5, "Meat"), (4, "Cider"), (3, "RedApple"), (2, "RedPotion")]}
GREET = {"store": q.text("Furs, arrows, steel and potions. Prices are steep up here; so is the climb.", "Shop"),
         "inn": q.text("Come in out of the cold! Broth's hot. If you're waiting on the pass, you'll be waiting a while.",
                       "Shop")}
n_shops = sm.shops(WARES, GREET)
FOLK = [("Con02a", "Tanya"), ("Con02a", "Heckler"), ("Con03A", "Osborn"), ("Con02a", "Morgan"),
        ("Con03A", "Millard"), ("Con02a", "Clyde"), ("Con08a", "Gretchen")]
RUMOURS = ["Since the shrine went dark the cold's come down off the pass like a wall. Nobody crosses now.",
           "Ogres in the old keep, north-west through the pines. Their chief, Skarg, wears the shrine's stone round "
           "his neck, they say.",
           "Don't walk out on the lake alone. Something big moves under the snow by the shrine.",
           "Torvald's offering good silver for the great bear. It's had two of his dogs.",
           "Poor Inga. Oskar knew that ice cave better than anyone, and still he hasn't come back.",
           "The Kettle's broth is the only warm thing left in Rimehold. Get some while you can.",
           "Ylva sits by her door all day watching the lake. She says the stones are cold to the touch now."]
sm.townsfolk(FOLK, vc, q=q, rumours=RUMOURS, after=("shrine_lit", "The flame's back! You can feel it from here."),
             pics=("MaidenPic3", "MalePic1", "Townsman2Pic", "MorganPic", "Townsman3Pic", "MalePic7", "MaidenPic"),
             radius=4.5)

# ---- 8. the fights -----------------------------------------------------------------------------------------------
# the ogres in their keep, Skarg in the hoard with the heartstone
hoard = next((r for role, area, b, nm in d.structures for r in b.rooms if r.kind == "ogre_hoard"), None)
hall = next((r for role, area, b, nm in d.structures for r in b.rooms if r.kind == "ogre_hall"), None)
den_r = next((r for role, area, b, nm in d.structures for r in b.rooms if r.kind == "ogre_den"), None)
skarg = sm.keepers(hoard or hall, ["OgreWarlord"], "Skarg")
ogres = (sm.keepers(hall, ["OgreBrute", "GruntAxe", "GruntAxe"], "KeepOgre") if hall else []) + \
        (sm.keepers(den_r, ["GruntAxe", "OgreBrute"], "DenOgre") if den_r else [])
# the troll of the lake, waiting by the shrine
pop.creature("Troll", sx + 90, sy + 60, action="idle", scr="LakeTroll", aggr=0.83)
# spiders in the ice cave round Oskar's bones
for k, a in enumerate((0.3, 1.9, 3.6, 5.0)):
    x_, y_ = osk.px(2.6, a)
    pop.creature("AlbinoSpider" if k % 2 else "SmallAlbinoSpider", x_, y_, action="guard", scr=f"CaveSpider{k + 1}", aggr=0.83)
# the great bear and the white wolves that follow the herds
bx_, by_ = bear_spots[0]
pop.creature("Bear", bx_, by_, action="idle", scr="GreatBear", aggr=0.83, HealthMultiplier=2.5)
sm.wild({"WhiteWolf": 3, "BlackWolf": 2, "Ghost": 1}, away_from=vc,
        avoid=(lc, cc, pc, land.areas["keep"]["c"], south_c, gate_sq, land.areas["north"]["c"]), per100=0.45, min_away=25)

# ---- 9. the story ----------------------------------------------------------------------------------------------------
q.start([A.lock("PassGate1"), A.lock("PassGate2"), A.disable("PassExit1"), A.disable("PassExit2"), A.disable("PassExit3"),
         A.disable("ShrineLight"),
         q.journal("The north road has brought me to Rimehold, the last shelter under the Rime Pass.", HINT)])
q.near(sx, sy, 260, [A.hunt("LakeTroll"), A.print("The snow heaves. A troll rises from the drift by the stones!")])
# the shrine: the heartstone set back in its socket
q.near(sx, sy, 70, [A.take("Diamond"), A.enable("ShrineLight"), A.spawn("DunMirFlameBasinLit", "ShrineStone"),
                    A.flag("shrine_lit"), A.unlock("PassGate1"), A.unlock("PassGate2"),
                    A.enable("PassExit1"), A.enable("PassExit2"), A.enable("PassExit3"),
                    A.print("You set the heartstone in the shrine. Flame leaps up between the stones, and the cold "
                            "breaks."),
                    q.journal("I set the heartstone back in the shrine on the lake. The flame burns again and the Rime "
                              "Pass is open.", COMPLETED)], when=q.when(has="Diamond"))
q.on_death("Skarg1", [A.drop("Diamond"), A.print("Skarg falls. Something glitters in the snow where he lay: the "
                                                  "heartstone."),
                      q.journal("Skarg is dead and the heartstone is mine. It goes back in the shrine on the lake.", QUEST)])
q.talker("Hrolf", [
    q.say("The flame burns and the pass is open. Rimehold owes you more than I can pay, but take this.",
          when=q.when(flag="shrine_lit", not_="hrolf_paid"), do=[A.gold(250), A.give("BluePotion", 2), A.flag("hrolf_paid")],
          who="Hrolf"),
    q.say("The pass is open. Go well, and come back in spring.", when=q.when(flag="hrolf_paid"), who="Hrolf"),
    q.say("You have it, the heartstone! Take it to the shrine on the lake and set it in the stones. Go!",
          when=q.when(has="Diamond"), who="Hrolf"),
    q.say("Skarg's ogres hold the old keep, north-west through the pines. He wears the stone. Kill him and bring it to "
          "the shrine.", when=q.at("shrine", 1), who="Hrolf"),
    q.say("Another one wanting the pass? It's sealed, and it stays sealed. The shrine on the lake kept the cold off the "
          "pass for a hundred years. This winter the ogres from the old keep came down and took its heartstone, and the "
          "flame died with it. Their chief Skarg has the stone. Kill him, set the stone back in the shrine, and I'll open "
          "the gate myself.", do=[A.stage("shrine", 1),
                                  q.journal("Warden Hrolf has sealed the Rime Pass. The ogre chief Skarg, in the old keep "
                                            "north-west through the pines, has the shrine's heartstone. With it back in "
                                            "the shrine on the lake, the pass will open.")], who="Hrolf")])
q.talker("Ylva", [
    q.say("I felt it the moment the flame came back. Thank you. The stones are glad.", when=q.when(flag="shrine_lit"), who="Ylva"),
    q.say("The heartstone goes in the middle of the ring. Walk in among the stones and the shrine will take it.",
          when=q.when(has="Diamond"), who="Ylva"),
    q.say("I keep the shrine. Kept it. Without its heartstone it is just a ring of cold stones on the ice. Bring the "
          "stone back to the ring and the flame will remember itself.", who="Ylva")])
q.on_pickup("CrossBow", [A.stage("oskar", 2), q.journal("In the ice cave I found Oskar's bones and his crossbow. Inga "
                                                       "should know.")], when=q.when(not_="oskar_done"))
q.talker("Inga", [
    q.say("His crossbow. So he's gone, then. ...Thank you for not leaving me to wonder. Take this. It was meant for the "
          "spring.", when=q.when(has="CrossBow", not_="oskar_done"), ask=True,
          do=[A.flag("oskar_done"), A.take("CrossBow"), A.gold(120), A.give("LeatherArmoredBoots"), A.give("RedPotion", 2),
              q.journal("I brought Oskar's crossbow home to Inga. She gave me his savings and boots for the road.", COMPLETED)],
          else_=[A.chat("Inga", "Please. It's all I'll have of him.")], who="Inga"),
    q.say("I'll be all right. The spring will come.", when=q.when(flag="oskar_done"), who="Inga"),
    q.say("My husband Oskar went into the ice cave east of the lake, after crystal. That was six days ago. He's never "
          "been gone more than two. Would you look for him? Please?",
          do=[A.stage("oskar", 1), q.journal("Inga's husband Oskar went into the ice cave east of the frozen lake six "
                                             "days ago and has not come back.")], who="Inga")])
q.talker("Torvald", [
    q.say("The great bear's dead? Then the bounty's yours, and a bow besides. My hunters will drink to you tonight.",
          when=q.when(flag=q.dead("GreatBear"), not_="bear_paid"),
          do=[A.gold(150), A.give("Bow"), A.give("Quiver"), A.flag("bear_paid"),
              q.journal("I killed the great bear of the west pines. Torvald paid the bounty.", COMPLETED)], who="Torvald"),
    q.say("Good hunting, friend.", when=q.when(flag="bear_paid"), who="Torvald"),
    q.say("There's a bear in the west pines bigger than any I've seen, and it's had two of my dogs. A hundred and fifty "
          "silver to whoever brings it down.",
          do=[A.stage("bear", 1), q.journal("Torvald of the hunters' lodge has a bounty of 150 on the great bear of the "
                                            "west pines.")], who="Torvald")])
q.talker("PassGuard", [
    q.say("Gate's open. Mind your footing up there.", when=q.when(flag="shrine_lit"), who="Guard"),
    q.say("Pass is sealed by the warden's order. Talk to Hrolf; his house is by the yard.", who="Guard")])
for who_, pic_ in (("Hrolf", "Warrior3Pic"), ("Ylva", "MaidenPic2"), ("Inga", "MaidenPic"), ("Torvald", "MalePic9"),
                   ("PassGuard", "Warrior2Pic")):
    q.portrait(who_, pic_)

m.scripts.update(B.files(m.d["name"]))
m.scripts.update(q.files())

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    keep_ids = [(BuildingIdentity(role, area, nm, "the ogres"), b) for role, area, b, nm in d.structures]
    rooms_sidecar(placed + keep_ids, os.path.join(OUT, f"{NAME}.rooms.json"))
    q.write_strings(OUT)
    lines = m.build(os.path.abspath(OUT))
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK", "SCRIPTS"))))
    print(f"land {len(land.squares)} squares | buildings {len(placed)}/{len(ID.buildings)} (missed: {', '.join(sm.missed) or 'none'}) "
          f"| keep {'yes' if keep_b else 'NO'} | trees {n_trees} | rock piles {len(piles)} | shops {n_shops} "
          f"| caches {len(caches)} | lines {len(q.strings)}")
