"""RimePass: the far side of the Rime Pass, where Rimehold's exit leads. The pass road comes over the saddle to a
cairn where travellers rest, with a view north; a sign closes the second chapter. The road on is the next map's.

    py mapgen/designs/rimepass.py [seed]
"""
QA_ACCEPT = [   # (tests/qa.py) a short pass road between two maps, judged against Westwood's two ice maps
    ("density", r"^Many decorations", "a short road lined with snow rocks: few open tiles to divide by"),
    ("density", r"^Many share of floor seams with edge pieces", "every seam blended, as the kit always blends them"),
    ("density", r"^Many wall pieces", "a narrow pass between rock walls; Westwood's ice maps are open caverns"),
    ("density", r"^Many crowded floor junctions", "snow, ice and the road meet in a narrow pass"),
]
import math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO
from kit.layout import Land, square_px
from kit.biome import Dresser
from kit.quests import QuestBook, A
from kit import camps

SEED = int(sys.argv[1]) if len(sys.argv) > 1 else 4
rng = random.Random(SEED)
NAME = "RimePass"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "out", "rimepass")


def uv(X, Y):
    return (X + Y, X - Y)


m = Spec(NAME, summary="The Rime Pass", description="[env:ice] The far side of the Rime Pass: the saddle, a travellers' "
         "cairn, the road north. Generated by Claude.", author="vdystopia (generated by Claude)", version="1",
         date="2026", type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
q = QuestBook(NAME)
land = Land(rng, u_range=(120, 400), v_range=(-120, 120))
land.area("saddle", uv(124, 196), 16)
land.area("cairn", uv(132, 140), 28)
land.area("on", uv(146, 80), 14)
for a_, b_ in (("saddle", "cairn"), ("cairn", "on")):
    land.link(a_, b_, 13, bend=0.25, road_material="CaveHardTan")
d = Dresser(m, rng, land, "ice")
land.paint_roads(m, "CaveHardTan", width_squares=2.4)
cc = land.areas["cairn"]["c"]
land.taken |= {s for s in land.squares if math.hypot(s[0] - cc[0] - 4, s[1] - cc[1]) <= 4}
land.carve(margin=4.0)
outcrops = land.thickets(16, size=(1.2, 2.4), clear=1)
land.open_links()
land.apply(m, wall=d.wall, floor=d.base)
d.cap_islands(outcrops)
d.ground()
# the travellers' cairn: a heap of stones round a standing stone, a fire basin, a chest left for whoever comes next
sc = camps.Scene(m, rng, land, (cc[0] + 4, cc[1]))
sc.put("ObeliskPrimitive", *sc.at(0, 0))
for k in range(9):
    sc.put(rng.choice(("CaveRocksLarge", "CaveRocksMedium", "CaveRocksSmall")), *sc.at(1.0 + 0.3 * (k % 3), k * 0.7))
sc.put("DunMirFlameBasinLit", *sc.at(2.8, 2.2))
sc.put("Chest1", *sc.at(3.2, 4.0), items=[("Gold", {"Amount": 40}), "RedPotion", "Meat"])
road = min(land.roads, key=lambda s: math.hypot(s[0] - cc[0], s[1] - cc[1]))
camps.signpost(m, land, (road[0] - 1.5, road[1] + 1.5),
               q.text("THE RIME PASS\nRimehold lies below you, its shrine burning again. Ahead, the road drops "
                      "into the smoking country round Emberhollow.", "Sign"))
d.vegetate(groves=1)
d.scatter_open(scale=0.3)
d.rim(scale=0.4)
d.lights(scale=1.2)
d.planter.rock_piles(3)
sc0 = land.areas["saddle"]["c"]
m.obj_px("PlayerStart", *square_px(sc0[0] + 0.5, sc0[1] - 0.5))
from kit.story import StoryMap
StoryMap(m, rng, land, None).exit_to("on", "Emberhol", prefix="PassExit")      # down into chapter three
StoryMap(m, rng, land, None).wild({"WhiteWolf": 2, "BlackWolf": 1}, away_from=sc0, min_away=8, per100=0.4,
                                  avoid=[(cc[0] + 4, cc[1])])
q.start([q.journal("I crossed the Rime Pass. Behind me the shrine's flame shows on the lake below Rimehold.", 1),
         A.print("The Rime Pass.")])
m.scripts.update(q.files())

# the exteriors' dressing: composed groups of the place's things on the empty ground (kit/dressing.py)
from kit.dressing import Exterior
dressed = Exterior(m, land, "ice").dress()

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    q.write_strings(OUT)
    lines = m.build(os.path.abspath(OUT))
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK", "SCRIPTS"))))
