"""Room lab: every composed room kind at three sizes, each a one-room house on open ground with its door in a
front wall, furnished by the kit.

The three sizes:
- typical: Westwood's typical room of the kind;
- large: Westwood's large rooms of the kind;
- bigger: half as big again, the scale the maps aim for.

The rooms are declared in RoomLab.rooms.json, so the checker judges each room by its kind and review/rooms.py draws
one numbered picture per room. review/roomscore.py scores them.

This is the loop for improving the furnisher: build, score, look at the pictures, fix, repeat.

    py mapgen/designs/roomlab.py [seed] [kind ...] [--stands]

--stands sets a person where people stand in each room (kit/story.py StoryMap.stand_px, by the room's type:
kit/roomtypes.py STANDS), to look at with the room.
"""
import json, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO, uv_to_xy, rect_tiles, rect_wall_cells
from kit.building import _units_for
from kit.model import Room, Door
from kit.originality import furnish_original

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "mapgen", "out", "roomlab")

# kind: (Westwood's typical floor tiles, its large rooms' floor tiles, wall, floor, furnishing style)
LAB = {
    "bedroom": (30, 70, "Log", "OakWoodFloor", "town"),
    "dwelling": (30, 60, "StuccoLightWood", "WoodLight2", "town"),
    "living_room": (35, 68, "StuccoLightWood", "WoodLight2", "town"),
    "kitchen": (35, 72, "Log", "WoodSlatFloor", "town"),
    "herbalist": (30, 70, "Log", "WoodGray2", "town"),
    "study": (30, 70, "BrickPlain", "OakWoodFloor", "town"),
    "library": (40, 100, "BrickPlain", "RedwoodFloor", "town"),
    "dining_hall": (50, 110, "StuccoLightWood", "RedwoodFloor", "town"),
    "mess_hall": (60, 120, "Log", "WoodSlatFloor", "mine"),
    "barracks": (50, 110, "Log", "DirtHard", "mine"),
    "storeroom": (25, 60, "Log", "WoodSlatFloor", "town"),
    "gear_store": (30, 70, "Log", "DirtHard", "mine"),
    "ore_store": (40, 90, "Log", "WoodLight2", "mine"),
    "smithy": (40, 60, "BrickPlain", "DirtHard", "town"),
    "tavern": (170, 230, "StuccoLightWood", "WoodLight2", "town"),
    "shop": (40, 90, "StuccoLightWood", "OakWoodFloor", "town"),
    "laboratory": (35, 80, "BrickPlain", "OakWoodFloor", "town"),
    "chapel": (78, 95, "BrickPlain", "GalavaBrownMarble", "dunmir"),
    "crypt": (70, 130, "LOTDBrick", "LOTDPitted", "lotd"),
    "hall": (90, 180, "BrickPlain", "GalavaBrownMarble", "dunmir"),
    "throne_room": (60, 110, "BrickPlain", "GalavaBrownMarble", "dunmir"),
    # the types added for variety (kit/roomtypes.py, rules/rooms/README.md "More types"): Westwood's rooms of the kind
    # where the campaign has them (the type's brief), a reasoned size where it has few or none
    "solar": (100, 140, "BrickPlain", "OakWoodFloor", "town"),
    "workshop": (30, 70, "Log", "WoodSlatFloor", "town"),
    "winch_room": (40, 110, "StoneGray", "DirtHard", "town"),
    "observatory": (60, 110, "StoneGray", "OakWoodFloor", "town"),
    "infirmary": (60, 110, "StuccoLightWood", "WoodLight2", "town"),
    "cellar": (25, 50, "StoneGray", "DirtHard", "town"),
    "treasury": (40, 80, "BrickPlain", "GalavaBrownMarble", "town"),
    "powder_store": (25, 40, "StoneGray", "DirtHard", "town"),
    "guardroom": (40, 70, "StoneGray", "WoodSlatFloor", "town"),
    "cell": (14, 30, "StoneGray", "DirtHard", "town"),
    "ogre_pen": (30, 40, "StoneGray", "DirtHard", "ogre"),
    "torture_chamber": (35, 60, "StoneGray", "DirtHard", "town"),
    "shrine": (30, 70, "BrickPlain", "GalavaBrownMarble", "town"),
    "dark_shrine": (40, 70, "LOTDBrick", "LOTDPitted", "lotd"),
    "gallery": (90, 180, "BrickPlain", "RedwoodFloor", "town"),
    "conservatory": (60, 150, "BrickPlain", "GalavaBrownMarble", "town"),
    "mausoleum": (50, 110, "StoneGray", "GalavaBrownMarble", "town"),
    "ossuary": (30, 70, "StoneGray", "DirtHard", "town"),
}
SIZES = (("typical", 0), ("large", 1), ("bigger", 1.5))
FIELD = (130, 380, -120, 120)           # u0, u1, v0, v1 of the open ground (x and y stay within 0-255)
GAP = 6                                 # uv units between rooms


def spans(tiles, rng):
    """Even u and v spans for a room of about `tiles` floor tiles (a tile is 2 x 2 uv units), 1.0-1.5 times as long
    as it is wide, either way round."""
    a = rng.uniform(1.0, 1.5)
    w = max(8, 2 * round((4 * tiles / a) ** 0.5 / 2))
    l = max(8, 2 * round(a * w / 2))
    return (l, w) if rng.random() < 0.5 else (w, l)


def build(seed=1, kinds=None, map_name="RoomLab", plan=None, stands=False):
    """Builds the lab's rooms into map `map_name`; rooms the field cannot hold go on to the next page (RoomLab2, ...).
    Returns the paths of the maps built."""
    rng = random.Random(seed)
    m = Spec(map_name, summary="Room lab", description="Every composed room kind at three sizes. Generated by Claude.",
             author="vdystopia (generated by Claude)", version="1", date="2026", type=SOLO, minPlayers=1, maxPlayers=1)
    m.d["nxz"] = False
    m.d["ambient"] = [165, 160, 155]
    u0, u1, v0, v1 = FIELD
    m.room(u0, u1, v0, v1, wall="BrickPlain", floor="GrassNorm")
    if plan is None:
        plan = []
        for kind, (typ, large, wall, floor, style) in LAB.items():
            if kinds and kind not in kinds: continue
            for label, f in SIZES:
                tiles = typ if f == 0 else int(large * f)
                plan.append((kind, label, tiles, wall, floor, style))
    overflow = []
    # shelf-pack the rooms into rows across the field, the biggest first
    plan.sort(key=lambda p: -p[2])
    rooms, u, v, row = [], u0 + 8, v0 + 8, 0
    for kind, label, tiles, wall, floor, style in plan:
        us, vs = spans(_units_for(tiles), rng)      # Westwood's sizes count the floor inside the walls' strip
        if v + vs > v1 - 8:
            u, v, row = u + row + GAP, v0 + 8, 0
        if u + us > u1 - 8:
            overflow.append((kind, label, tiles, wall, floor, style)); continue
        ru0, ru1, rv0, rv1 = u, u + us, v, v + vs
        m.room(ru0, ru1, rv0, rv1, wall=wall, floor=floor)
        # the door: in the SW wall (the '\\' line at v0) or the SE wall (the '/' line at u1), the front walls
        if rng.random() < 0.6:
            gu = 2 * rng.randint((ru0 + 4) // 2, (ru1 - 4) // 2)
            gap, line = tuple(int(c) for c in uv_to_xy(gu, rv0)), "\\"
        else:
            gv = 2 * rng.randint((rv0 + 4) // 2, (rv1 - 4) // 2)
            gap, line = tuple(int(c) for c in uv_to_xy(ru1, gv)), "/"
        d = m.door(None, gap, line)
        name = f"lab{len(rooms) + 1:02d}"
        r = Room(id=name, tiles=set(rect_tiles(ru0, ru1, rv0, rv1)), floor=floor, walls=rect_wall_cells(ru0, ru1, rv0, rv1),
                 doors=[Door(gap=gap, line=line, type=d["type"], connects=(name, "outside"), px=(d["x"], d["y"]))],
                 kind=kind, building=f"{name} {kind}")
        rooms.append((r, kind, label, style))
        v += vs + GAP
        row = max(row, us)
    out = []
    for i, (r, kind, label, style) in enumerate(rooms):
        objs, res = furnish_original(m, r, kind=kind, rng=random.Random(seed * 1000 + i), style=style)
        xs = [x for x, _ in r.tiles]; ys = [y for _, y in r.tiles]
        out.append(dict(number=i + 1, building=f"room lab ({label})", kind=kind, purpose=f"{label} size, {style} style",
                        tiles=len(r.tiles), box=[min(xs) - 1, min(ys) - 1, max(xs) + 3, max(ys) + 3],
                        floor=sorted([x, y] for x, y in r.tiles)))
    if stands:                                      # a person where people stand in each room, by its type
        from kit.story import StoryMap, STOCK
        sm = StoryMap.__new__(StoryMap)
        sm.m = m
        for i, (r, kind, label, style) in enumerate(rooms):
            x, y = sm.stand_px(r)
            m.clone(os.path.join(STOCK, "Con02a", "Con02a.map"), "Con02a:Bryan", x, y, name=f"Stand{i + 1:02d}",
                    xfer=dict(DefaultAction=4, Aggressiveness=0.0, Immortal=True))
    m.obj("PlayerStart", u0 + 4, v0 + 4)
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, f"{map_name}.rooms.json"), "w", encoding="utf-8") as f: json.dump(out, f, indent=1)
    lines = m.build(OUT)
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK"))))
    paths = [os.path.join(OUT, f"{map_name}.map")]
    if overflow:                                    # the next page
        page = int(map_name[len("RoomLab"):] or 1) + 1
        paths += build(seed, kinds, f"RoomLab{page}", overflow, stands)
    return paths


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    seed = int(args[0]) if args else 1
    build(seed, args[1:] or None, stands="--stands" in sys.argv)
