"""Swamp lab: the swamp palette (kit/biome.py BIOMES["swamp"], measured on Westwood's swamps) on a small map, to see
it before a story map uses it: glades of swamp grass and weeds joined by paths, shallow pools with deep hearts, root
walls, two-part swamp trees, polyps and mushrooms, green light, the swamp's creatures.

    py mapgen/designs/swamplab.py [seed]
"""
import math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO
from kit.layout import Land, square_px, square_tile
from kit.biome import Dresser

SEED = int(sys.argv[1]) if len(sys.argv) > 1 else 1
rng = random.Random(SEED)
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "out", "swamplab")


def uv(X, Y):
    return (X + Y, X - Y)


m = Spec("SwampLab", summary="Swamp lab", description="[env:swamp] The swamp palette on a small map. Generated by Claude.",
         author="vdystopia (generated by Claude)", version="1", date="2026", type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
land = Land(rng, u_range=(80, 430), v_range=(-150, 150))
for k, (X, Y), r in (("a", (110, 170), 34), ("b", (150, 110), 40), ("c", (100, 70), 30), ("d", (180, 160), 28)):
    land.area(k, uv(X, Y), r, roughness=0.3)
for a_, b_ in (("a", "b"), ("b", "c"), ("b", "d"), ("a", "d")):
    land.link(a_, b_, 12, bend=0.3, road=False, pockets=(1, 2))
d = Dresser(m, rng, land, "swamp")
land.carve(margin=4.0)
pools = []
for k in ("b", "c", "d"):
    c = land.areas[k]["c"]
    r = land.areas[k]["r"] * 0.45
    pools.append({s for s in land.squares if math.hypot(s[0] - c[0] - 2, s[1] - c[1] + 1) <= r * (1 + 0.2 * math.sin(3 * math.atan2(s[1] - c[1], s[0] - c[0])))})
calm = set().union(*pools)
outcrops = land.thickets(40, size=(1.0, 2.0), clear=1, avoid=frozenset(calm))
land.open_links()
land.apply(m, wall=d.wall, floor=d.base)
d.cap_islands(outcrops)
d.ground()
from kit.layout import bfs_distance
for pool in pools:
    # shallow water round the pool, deep water at its heart (two squares in from the shore), as Westwood's swamps lie
    shore = [s for s in pool if any((s[0] + a, s[1] + b) not in pool for a, b in ((1, 0), (-1, 0), (0, 1), (0, -1)))]
    depth = bfs_distance(shore, pool, 6)
    for s in pool:
        m.floor[square_tile(*s)] = "WaterSwampDeep" if depth.get(s, 0) >= 2 else "WaterSwampShallow"
    land.water |= pool
d.vegetate(keep_clear=calm, groves=3)
d.scatter_open()
d.rim()
d.lights()
d.creatures(avoid=[land.areas["a"]["c"]], groups=(1, 3))
a = land.areas["a"]["c"]
m.obj_px("PlayerStart", *square_px(a[0] + 0.5, a[1] - 0.5))

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    lines = m.build(os.path.abspath(OUT))
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK"))))
