"""TNorth: the King's Road north of Thornwick, where Thornwick's exit leads. A short forest road out of the gate's
shadow to a waystation clearing: a travellers' fire, a milestone and a sign that closes the chapter. The road on north
is the next map's to write.

    py mapgen/designs/tnorth.py [seed]
"""
import math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO
from kit.layout import Land, square_px
from kit.vegetation import Planter, FORESTS
from kit.quests import QuestBook, A
from kit import camps
from kit.story import StoryMap

SEED = int(sys.argv[1]) if len(sys.argv) > 1 else 3
rng = random.Random(SEED)
NAME = "TNorth"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "out", "tnorth")


def uv(X, Y):
    return (X + Y, X - Y)


m = Spec(NAME, summary="The North Road", description="[env:forest] The King's Road north of Thornwick, a waystation "
         "clearing in the woods. Generated by Claude.", author="vdystopia (generated by Claude)", version="1",
         date="2026", type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
m.d["ambient"] = [150, 146, 128]
q = QuestBook(NAME)

land = Land(rng, u_range=(120, 400), v_range=(-120, 120))
land.area("gate", uv(118, 190), 16)
land.area("way", uv(128, 140), 26)
land.area("on", uv(140, 82), 14)
land.link("gate", "way", 13, bend=0.25)
land.link("way", "on", 12, bend=0.25)
land.blends(m)
land.paint_roads(m, "DirtDark2", width_squares=2.6)
wc = land.areas["way"]["c"]
land.taken |= {s for s in land.squares if math.hypot(s[0] - wc[0] - 4, s[1] - wc[1]) <= 4}
land.carve(margin=4.0)
land.thickets(25, size=(0.9, 1.6), clear=2)
land.apply(m, wall=FORESTS["deciduous"]["wall"], floor="GrassNorm")
land.ground_variety(m, clear=2)
# the waystation: a travellers' fire with seats, a milestone by the road, the sign
fire = (wc[0] + 4, wc[1])
sc = camps.Scene(m, rng, land, fire)
sc.put("CampFire", *fire)
for k in range(4):
    sc.put(("ForestLog01", "ForestLog02", "ForestLog03", "ForestLog04")[k], *sc.at(1.6, k * math.pi / 2 + 0.4))   # logs to sit on
sc.put("OutdoorTraderPupTent", *sc.at(3.2, math.pi * 0.25))
sc.put("Chest2", *sc.at(3.4, math.pi * 0.8), items=[("Gold", {"Amount": 25}), "RedApple", "Cider"])
road = min(land.roads, key=lambda s: math.hypot(s[0] - wc[0], s[1] - wc[1]))
sc.put("DunMirMileStone", road[0] + 2.2, road[1] - 2.0)
camps.signpost(m, land, (road[0] - 1.5, road[1] + 1.5),
               q.text("THE KING'S ROAD\nThornwick lies south. North, the road climbs to Rimehold and the Rime "
                      "Pass.", "Sign"))
planter = Planter(m, rng, land, "deciduous")
from kit.vegetation import TOWN_PLANTING
planter.plant_all(groves=2, profile=TOWN_PLANTING)      # a roadside wood, not deep forest
planter.rock_piles(3)
gc = land.areas["gate"]["c"]
m.obj_px("PlayerStart", *square_px(gc[0] + 0.5, gc[1] - 0.5))
sm = StoryMap(m, rng, land, None)
sm.exit_to("on", "Rimehold", prefix="RoadExit")       # the road on north
# torches by the waystation's fire, and the wood's creatures keeping off the road
import json
presets = json.load(open(os.path.join(HERE, "..", "..", "rules", "out", "lighting.json")))["colorlight"]["presets"]
ORANGE = max((p for p in presets if p["family"] == "orange" and p["animation"] == "steady" and p["intensity_class"] == "full"),
             key=lambda p: p["weighted_share"])
for a in (1.2, 4.3):
    x_, y_ = sc.px(4.0, a)
    m.obj_px("TorchPole", x_, y_); m.obj_px("ColorLight", x_, y_ - 5, xfer=dict(ORANGE["xfer"]))
sm.wild({"Bat": 2, "Urchin": 2, "Wolf": 1}, away_from=gc, min_away=6, per100=0.5, avoid=[fire])
q.start([q.journal("I passed Thornwick's north gate onto the King's Road. The Red Hand will not trouble it again.", 1),
         A.print("The King's Road, north of Thornwick.")])
m.scripts.update(q.files())

# the exteriors' dressing: composed groups of the place's things on the empty ground (kit/dressing.py)
from kit.dressing import Exterior
dressed = Exterior(m, land, "green").dress()

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    q.write_strings(OUT)
    lines = m.build(os.path.abspath(OUT))
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK", "SCRIPTS"))))
