"""Town lab: the village pipeline (DysVale's, generator v3) at the scale the bigger maps need, to find what breaks when
a town holds many large buildings. A market town: a cobbled square with its well, the lord's manor, the inn, the store
and the smithy facing it; homes and cottages along the streets; a mill and a woodcutter's hut out along the roads.
Buildings at the house scale (identity.BUILDING_SCALE) times SCALE.

The rooms are declared (TownLab.rooms.json) so review/roomscore.py scores them, and the buildings
(TownLab.buildings.json) so review/buildingscore.py does.

    py mapgen/designs/townlab.py [scale] [seed]          scale 1.0 = the kit's house scale (1.25 Westwood's)
"""
import json, math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO
from kit.identity import MapIdentity, AreaIdentity, BuildingIdentity, BUILDINGS, role_size, rooms_sidecar
from kit.layout import Land, square_tile, square_px, px_square
from kit.vegetation import Planter, FORESTS
from kit.village import Village, _squares_of
from kit.building import generate_building
from kit.originality import furnish_original
from kit.npcs import Population

SCALE = float(sys.argv[1]) if len(sys.argv) > 1 and sys.argv[1] != "-" else 1.0      # "-": plan only (the smoke test)
SEED = int(sys.argv[2]) if len(sys.argv) > 2 else 3
rng = random.Random(SEED)
FOREST = "deciduous"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "out", "townlab")

ID = MapIdentity(
    name="TownLab",
    theme="a market town: a cobbled square with its fountain, the lord's manor, the inn, the store and the smithy facing "
          "it, homes and cottages along the streets, a mill and a woodcutter's hut out along the roads",
    environment="town", mood="busy, prosperous",
    areas=[AreaIdentity("town", "the square and the streets round it", landmark="Fountain"),
           AreaIdentity("gate", "where the road enters the town"),
           AreaIdentity("mill", "the mill out on the east road"),
           AreaIdentity("woods", "the woodcutter's clearing on the north road"),
           AreaIdentity("south", "homes along the south road")],
    buildings=[BuildingIdentity("manor", "town", "the manor", "the lord of the town"),
               BuildingIdentity("inn", "town", "The Crossed Keys", "the innkeeper"),
               BuildingIdentity("store", "town", "the general store", "the trader"),
               BuildingIdentity("smithy", "town", "the forge", "the smith"),
               BuildingIdentity("home", "town", "", "a family"), BuildingIdentity("home", "town", "", "a family"),
               BuildingIdentity("home", "town", "", "a family"), BuildingIdentity("home", "south", "", "a family"),
               BuildingIdentity("home", "south", "", "a family"), BuildingIdentity("cottage", "town", "", "an old couple"),
               BuildingIdentity("cottage", "south", "", "a widower"), BuildingIdentity("mill", "mill", "the mill", "the miller"),
               BuildingIdentity("woodcutter", "woods", "the woodcutter's hut", "the woodcutter")])

m = Spec("TownLab", summary="Town lab", description=f"[env:{ID.environment}] {ID.theme[0].upper() + ID.theme[1:]}. "
         f"Generated by Claude.", author="vdystopia (generated by Claude)", version="1", date="2026", type=SOLO,
         minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
m.d["ambient"] = [150, 146, 120]

# ---- 1. the plan ---------------------------------------------------------------------------------------------------
land = Land(rng, u_range=(40, 470), v_range=(-205, 205))
land.area("town", (250, 0), 110, clearing=False)
land.area("gate", (96, -40), 16)
land.area("mill", (420, 40), 20)
land.area("woods", (250, 168), 18)
land.area("south", (270, -150), 36, clearing=False)
for k_, ar in land.areas.items():
    x_, y_ = ar["c"][0] + ar["c"][1], ar["c"][0] - ar["c"][1]
    assert 12 + ar["r"] <= x_ <= 243 - ar["r"] and 12 + ar["r"] <= y_ <= 243 - ar["r"], (k_, x_, y_)
for a_, b_, w_ in (("gate", "town", 14), ("town", "mill", 13), ("town", "woods", 12), ("town", "south", 13)):
    land.link(a_, b_, w_, bend=0.22)
land.blends(m)

# ---- 2. the centre: the square and its well, the streets leaving it -----------------------------------------------
land.paint_square(m, "town", 14, "RoughCobble")
vc = land.areas["town"]["c"]
land.taken |= {(int(vc[0]) + a, int(vc[1]) + 1 + b) for a in (-2, -1, 0, 1, 2) for b in (-2, -1, 0, 1, 2)}   # the fountain
land.paint_roads(m, "DirtDark2", width_squares=2.8, skip=land.reserved)

# ---- 3. buildings from the square outwards --------------------------------------------------------------------------
placed, door_paths, missed = [], set(), []
order = sorted(range(len(ID.buildings)), key=lambda k: (BUILDINGS[ID.buildings[k].role]["faces"] != "square",
                                                        -BUILDINGS[ID.buildings[k].role]["size"][0], k))
for k in order:
    bid = ID.buildings[k]
    role = BUILDINGS[bid.role]
    size0, min_units0 = role_size(role)
    program = [kind for kind, _ in role["rooms"]]
    b = None
    for shrink in (1.0, 0.92, 0.84):
        size = (2 * round(size0[0] * SCALE * shrink / 2), 2 * round(size0[1] * SCALE * shrink / 2))
        lots = land.square_lots(size) if role["faces"] == "square" and bid.area == "town" else []
        lots += land.lots(bid.area, size)
        for origin, side in lots:
            if not land.lot_free(origin, size, margin=1): continue
            b = generate_building(m, rng, origin, size, role["style"], program=program, entrance_side=side,
                                  building_id=f"B{k}", occupied={square_tile(*s) for s in land.taken}, tries=12,
                                  shape=role.get("shape"), min_units=int(min_units0 * (SCALE * shrink) ** 2))
            if b: break
        if b: break
    if not b:
        missed.append(bid.role)
        print(f"could not place the {bid.role} in the {bid.area}"); continue
    land.take_cells(b.cells, margin=1)
    land.wall_cells |= {c for c in m.wallmap}
    land.taken_strict |= _squares_of(b.footprint)
    placed.append((bid, b))

land.clear_walls(m)
for bid, b in placed:
    foot = _squares_of(b.footprint)
    for d in b.entrances:
        path = land.connect_door(m, d, foot)
        if path is None: print(f"  no path from the {bid.role}'s door")
        else: door_paths |= set(path)
land.trim_dead_ends(m, keep=door_paths)

furnished = []
for bid, b in placed:
    for room in b.rooms:
        objs, res = furnish_original(m, room, kind=room.kind, rng=rng, style="town")
        furnished.append((bid.role, room.kind, len(objs)))

# ---- 4. the land grows round everything, ending in the forest wall; the town's life ---------------------------------
land.carve(margin=4.5)
land.apply(m, wall=FORESTS[FOREST]["wall"], floor="GrassNorm")
vil = Village(m, rng, land)
for bid, b in placed:
    role = BUILDINGS[bid.role]
    for sc in role["scenes"]: vil.scene(b, sc)
    if rng.random() < role["garden"]: vil.garden(b, size=(rng.randint(3, 5), rng.randint(2, 4)))
vil.fountain_square(vc, 7)                         # the paving's radius: 14 uv, 7 squares
land.ground_variety(m, clear=3)
gate = land.areas["gate"]["c"]
keep = {(int(gate[0]) + a, int(gate[1]) + b) for a in range(-3, 4) for b in range(-3, 4)}
for bid, b in placed:
    for d in b.entrances:
        di, dj = px_square(*d.px)
        keep |= {(di + a, dj + b2) for a in range(-2, 3) for b2 in range(-2, 3)}
vil.ground_bits(0.8)
planter = Planter(m, rng, land, FOREST, keep_clear=keep)
n_trees, n_small = planter.plant_all(groves=3)
m.obj_px("PlayerStart", *square_px(gate[0], gate[1]))

# ---- 5. townsfolk: walking between the square and the doorsteps, lingering, turning to look at a passer-by, running
# for a doorstep when a wolf comes into town (Westwood's towns hold 8-26 villagers each; kit/behaviours Villager)
pop = Population(m, rng)
B = pop.behaviours
ring = [square_px(vc[0] + 6.5 * math.cos(a), vc[1] - 0.5 + 6.5 * math.sin(a)) for a in (k * math.pi / 4 for k in range(8))]
square_wps = pop.waypoint_path("Square", ring)
door_wps = []
for bid, b in placed:
    for d in b.entrances[:1]:
        o_ = land.door_outside(d, _squares_of(b.footprint))
        if o_: door_wps += pop.waypoint_path(f"Door{len(door_wps) + 1}", [square_px(o_[0] + 0.5, o_[1] - 0.5)])
for k in range(max(6, len(placed))):
    name = f"Folk{k + 1}"
    x, y = ring[k % len(ring)]
    pop.creature("Maiden", x + rng.uniform(-10, 10), y + rng.uniform(-10, 10), scr=name, aggr=0.0)
    homes = rng.sample(door_wps, min(2, len(door_wps)))
    B.villager(name, rng.sample(square_wps, 3) + homes, home=homes[0] if homes else square_wps[0], linger=5.0)

# ---- 6. the woods round the town: Westwood's town maps keep their creatures out by the forest's edge (rules/NPCS.md:
# most alone, about 2 squares from a wall, idle or on guard), well away from the square; wolves run in packs
edge = land.edge_distance()
far = [s for s, dd in sorted(edge.items()) if 1 <= dd <= 3 and math.hypot(s[0] - vc[0], s[1] - vc[1]) > 30
       and s not in land.taken and s not in land.roads and s not in land.taken_strict]
rng.shuffle(far)
MIX = {"Urchin": 3, "Bat": 3, "Wolf": 2, "SmallAlbinoSpider": 2, "Bear": 1}
n_wild, wild, centres = int(len(land.squares) * 0.7 / 100), 0, []
for s_ in far:
    if wild >= n_wild: break
    if any(math.hypot(s_[0] - a, s_[1] - b) < 6 for a, b in centres): continue
    t = rng.choices(list(MIX), list(MIX.values()))[0]
    k = rng.randint(3, 4) if t == "Wolf" else 1
    members = []
    for q in range(k):
        x, y = square_px(s_[0] + 0.5 + (rng.uniform(-1.2, 1.2) if q else 0), s_[1] - 0.5 + (rng.uniform(-1.2, 1.2) if q else 0))
        if any((int(x // 23) + a, int(y // 23) + b) in m.wallmap for a in (-1, 0, 1) for b in (-1, 0, 1)): continue
        name = pop.name(t) if t == "Wolf" else None
        pop.creature(t, x, y, action="guard" if rng.random() < 0.38 else "idle", scr=name)
        if name: members.append(name)
        wild += 1
    if len(members) >= 2: B.pack(members[0], members[1:])
    centres.append(s_)
m.scripts.update(B.files(m.d["name"]))

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    rooms_sidecar(placed, os.path.join(OUT, "TownLab.rooms.json"))
    meta = [dict(role=bid.role, style=b.style, shape=b.shape, units=list(b.size_units), footprint=len(b.footprint),
                 rooms=[dict(kind=r.kind, tiles=len(r.tiles), doors=len(r.doors)) for r in b.rooms],
                 entrances=len(b.entrances), unreachable=list(b.unreachable),
                 box=[min(x for x, _ in b.footprint), min(y for _, y in b.footprint),
                      max(x for x, _ in b.footprint) + 2, max(y for _, y in b.footprint) + 2]) for bid, b in placed]
    with open(os.path.join(OUT, "TownLab.buildings.json"), "w", encoding="utf-8") as f: json.dump(meta, f, indent=1)
    lines = m.build(os.path.abspath(OUT))
    print("\n".join(l for l in lines if l.startswith(("OK", "ERROR", "CHECK"))))
    print(f"land {len(land.squares)} squares | buildings {len(placed)}/{len(ID.buildings)} (missed: {', '.join(missed) or 'none'}) "
          f"| trees {n_trees} | plants {n_small}")
