"""TreePlace: a sacred mana forest (generator v3, built with PROCESS.md from the centre outwards).

A giant cluster of mana crystals glows in the heart of a silver grove, ringed by standing stones.
Three forests with their own character stretch out from it:
- north, the Grovelord's Wood: ancient green forest, where the grovelord lives in a large shack;
- west, the Golden Wood: aspens and autumn trees, a lily pond;
- south, the Pine Wood: pines and ferns, a brook crossed by a rope bridge.
A long winding path leaves the grove eastwards to a mana mine's mining camp: a bunkhouse, a mess hall,
the foreman's house and an ore shed around a work yard, beneath a rock cliff whose mine mouth is
blocked with boulders (the mines are not accessible). The traveller arrives at the camp's road.

Single player (Solo), one PlayerStart, no .nxz.
    py mapgen/designs/treeplace.py [out_dir|-] [seed]
"""
import json, math, os, random, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from nox import Spec, SOLO
from kit.identity import MapIdentity, AreaIdentity, BuildingIdentity, BUILDINGS
from kit.layout import Land, square_tile, square_px, px_square, cell_square, point_cell, bfs_distance, N4, door_frame
from kit.vegetation import Planter, FORESTS, scatter
from kit.village import Village, _squares_of
from kit.water import Waterworks
from kit.building import generate_building
from kit.originality import furnish_original
from kit.mine import MineEntrance

SEED = int(sys.argv[2]) if len(sys.argv) > 2 else 11
rng = random.Random(SEED)
HERE = os.path.dirname(os.path.abspath(__file__))

# ---- 0. identity: what this place is ---------------------------------------------------------------------
ID = MapIdentity(
    name="TreePlace",
    theme="a sacred mana forest: a giant cluster of mana crystals glows in the heart of its grove, three woods "
          "stretch out from it, and a long winding path leads east to a mana mine's camp",
    environment="forest", mood="hushed, glowing, ancient",
    areas=[AreaIdentity("heart", "the sacred grove: the giant mana crystal cluster ringed by standing stones and "
                                 "silver trees", landmark="MineManaCrystal10"),
           AreaIdentity("grovelord", "the grovelord's clearing in the ancient north wood, his shack and herb garden"),
           AreaIdentity("north_e", "a mossy glade with a fairy ring of mushrooms"),
           AreaIdentity("north_w", "an old glade where the north and golden woods meet"),
           AreaIdentity("west_pond", "a golden glade around a lily pond"),
           AreaIdentity("west_n", "golden aspens"), AreaIdentity("west_s", "golden aspens"),
           AreaIdentity("south_glade", "the pine wood's open heart"),
           AreaIdentity("south_w", "a pine glade beyond the brook"), AreaIdentity("south_e", "a fern hollow"),
           AreaIdentity("p1", "the winding path east"), AreaIdentity("p2", "a waystone on the winding path"),
           AreaIdentity("p3", "the winding path east"), AreaIdentity("p4", "a waystone where the path turns south"),
           AreaIdentity("camp", "the miners' camp: the work yard before the mine cliff"),
           AreaIdentity("gate", "where the road from the outside world arrives")],
    buildings=[BuildingIdentity("grovelord", "grovelord", "the Grovelord's shack", "the Grovelord"),
               BuildingIdentity("ore_shed", "camp", "the ore shed beside the mine mouth", ""),
               BuildingIdentity("bunkhouse", "camp", "the bunkhouse", "the miners"),
               BuildingIdentity("mess", "camp", "the mess hall", "the camp cook"),
               BuildingIdentity("foreman", "camp", "the foreman's house", "Mattock the foreman")])

m = Spec("TreePlace", summary="TreePlace - a sacred mana forest",
         description=f"[env:{ID.environment}] {ID.theme[0].upper() + ID.theme[1:]}. Generated by Claude.",
         author="vdystopia (generated by Claude)", version="0.2", date="Saturday, October 3 2026",
         type=SOLO, minPlayers=1, maxPlayers=1)
m.d["nxz"] = False
m.d["ambient"] = [128, 132, 140]

# sections: their forest (walls, trees, undergrowth) and ground (base, patches, patches)
REGIONS = dict(
    heart=dict(forest="silver", ground=("GrassNorm", "GrassSparse2", "GrassDense")),
    north=dict(forest="ancient", ground=("GrassNorm", "GrassSparse2", "GrassDense")),
    west=dict(forest="aspen", ground=("GrassNormYellow", "GrassSparseYellow", "GrassDenseYellow")),
    south=dict(forest="pine", ground=("GrassSparse2", "GrassNorm", "GrassDense")),
    path=dict(forest="dusk", ground=("GrassNorm", "GrassSparse2", "GrassDense")),
    camp=dict(forest="camp", ground=("GrassSparse2", "GrassNorm", "DirtHard")),
)
# blend order: each material spills over the ones below it (Westwood's overlay directions, floors.json)
for mat, prio in (("GrassNorm", 0), ("GrassSparseYellow", 0.4), ("GrassNormYellow", 0.5), ("GrassDenseYellow", 0.6),
                  ("GrassSparse2", 1), ("GrassDense", 2), ("DirtDark2", 3), ("DirtHard", 4), ("ManaMineDirt", 4.5),
                  ("CaveHardDark", 5)):
    m.blending(mat, prio)

presets = json.load(open(os.path.join(HERE, "..", "..", "rules", "out", "lighting.json")))["colorlight"]["presets"]


def preset(family):
    return max((p for p in presets if p["family"] == family and p["animation"] == "steady" and p["intensity_class"] == "full"),
               key=lambda p: p["weighted_share"])["xfer"]


ORANGE, CYAN, BLUE = preset("orange"), preset("cyan"), preset("blue")

# ---- 1. the plan: areas and the trails joining them (positions from world cells: u = x + y, v = x - y) ------
W = lambda x, y: (x + y, x - y)
land = Land(rng, u_range=(14, 496), v_range=(-236, 236))
A = land.area
A("heart", W(118, 124), 52, roughness=0.10, region="heart")
A("grovelord", W(110, 40), 50, region="north")
A("north_e", W(152, 32), 30, region="north")
A("north_w", W(64, 54), 32, region="north")
A("west_pond", W(34, 118), 46, region="west")
A("west_n", W(38, 78), 30, region="west")
A("west_s", W(40, 170), 32, region="west")
A("south_glade", W(110, 208), 44, region="south")
A("south_w", W(60, 222), 30, region="south")
A("south_e", W(158, 222), 32, region="south")
A("p1", W(166, 110), 20, region="path")
A("p2", W(192, 74), 22, region="path")
A("p3", W(224, 54), 20, region="path")
A("p4", W(238, 104), 18, region="path")
A("camp", W(208, 162), 44, region="camp", clearing=False)
A("gate", W(206, 222), 18, region="camp")
for a_, b_, w_, bend, rw, mat in (
        ("heart", "grovelord", 22, 0.25, 2.0, "DirtDark2"), ("grovelord", "north_e", 15, 0.30, 1.8, "DirtDark2"),
        ("grovelord", "north_w", 15, 0.30, 1.8, "DirtDark2"), ("north_w", "west_n", 11, 0.30, 1.6, "DirtDark2"),
        ("heart", "west_pond", 22, 0.25, 2.0, "DirtDark2"), ("west_pond", "west_n", 15, 0.30, 1.8, "DirtDark2"),
        ("west_pond", "west_s", 15, 0.30, 1.8, "DirtDark2"),
        ("heart", "south_glade", 22, 0.20, 2.0, "DirtDark2"), ("south_glade", "south_w", 15, 0.15, 1.8, "DirtDark2"),
        ("south_glade", "south_e", 15, 0.30, 1.8, "DirtDark2"),
        ("heart", "p1", 17, 0.30, 2.2, "DirtDark2"), ("p1", "p2", 17, 0.35, 2.2, "DirtDark2"),
        ("p2", "p3", 17, 0.35, 2.2, "DirtDark2"), ("p3", "p4", 17, 0.30, 2.2, "DirtDark2"),
        ("p4", "camp", 17, 0.25, 2.2, "DirtDark2"),
        ("camp", "gate", 17, 0.15, 2.4, "DirtHard")):
    land.link(a_, b_, w_, bend=bend, road_width=rw, road_material=mat, pockets=(0, 1))

# the brook in the pine wood is planned now, with its crossing: the trail to the far glade crosses it
# square to a straight stretch, on a rope bridge (Westwood's stream bridges are rope-bridge kits)
cross = land.plan_crossing("south_glade", "south_w", t=0.5, approach=8)
C = cross["uv"]
fu, fv = cross["flow"]
BROOK = [(C[0] - 44 * fu - 8 * fv, C[1] - 44 * fv - 8 * fu), (C[0] - 14 * fu, C[1] - 14 * fv), C,
         (C[0] + 14 * fu, C[1] + 14 * fv), (C[0] + 40 * fu + 10 * fv, C[1] + 40 * fv + 10 * fu)]
land.reserve_band(BROOK, 3.5)
pc = land.areas["west_pond"]["c"]
POND = ((2 * pc[0] - 8, 2 * pc[1] - 10), 6)
land.reserve_band([POND[0], (POND[0][0] + 0.1, POND[0][1])], POND[1] * 1.35 + 2)

# ---- 2. the centre: the heart grove's crystal circle and the ring path the trails arrive at -----------------
hc = land.areas["heart"]["c"]
RING_IN, RING_OUT = 7.0, 8.6
inner = {(i, j) for i in range(int(hc[0]) - 12, int(hc[0]) + 13) for j in range(int(hc[1]) - 11, int(hc[1]) + 14)
         if math.hypot(i + 0.5 - hc[0], j - 0.5 - hc[1]) < RING_IN}
ring = {(i, j) for i in range(int(hc[0]) - 12, int(hc[0]) + 13) for j in range(int(hc[1]) - 11, int(hc[1]) + 14)
        if RING_IN <= math.hypot(i + 0.5 - hc[0], j - 0.5 - hc[1]) <= RING_OUT}
land.taken |= inner
land.paint_roads(m, "DirtDark2", skip=land.reserved | inner)
for s in ring:
    m.floor[square_tile(*s)] = "DirtDark2"
    land.roads.add(s)

# the camp's work yard comes first in the east, and with it the mine: a rock face along the yard's
# north-west side (the side the loop of the winding path encloses), the mouth facing the yard
cc = land.areas["camp"]["c"]
land.paint_square(m, "camp", 11, "DirtHard")
mine = MineEntrance(land, set(land.plaza), (-1, 0), rng, depth=10, width=3, gap=4, reach=5, rock=14)
mine.plan()

# ---- 3. buildings: the camp's buildings face the yard; the grovelord's shack faces his trail -----------------
placed, door_paths = [], set()
for k, bid in enumerate(ID.buildings):
    role = BUILDINGS[bid.role]
    size = role["size"]
    program = [kind for kind, _ in role["rooms"]]
    lots = land.square_lots(size) if role["faces"] == "square" else []
    lots += land.lots(bid.area, size)
    if bid.role == "ore_shed":                                    # ore comes out of the mine into the shed
        mo = mine.mouth
        lots.sort(key=lambda lt: math.hypot(lt[0][0] / 2 + size[0] / 4 - mo[0], lt[0][1] / 2 + size[1] / 4 - mo[1]))
    b = None
    for origin, side in lots:
        if not land.lot_free(origin, size, margin=1): continue
        b = generate_building(m, rng, origin, size, role["style"], program=program, entrance_side=side,
                              building_id=f"B{k}", occupied={square_tile(*s) for s in land.taken}, tries=12,
                              shape=role.get("shape"), min_units=role.get("min_units", 0))
        if b: break
    if not b:
        print(f"could not place the {bid.role} in the {bid.area}"); continue
    land.take_cells(b.cells, margin=1)
    land.taken_strict |= _squares_of(b.footprint)
    land.wall_cells |= set(m.wallmap)
    placed.append((bid, b))

# ---- 4. the outlying features' footprints: obelisks around the grove, the fairy ring --------------------------
trail_angles = sorted(math.atan2(land.areas[x]["c"][1] - hc[1], land.areas[x]["c"][0] - hc[0])
                      for x in ("grovelord", "west_pond", "south_glade", "p1"))
obelisks = []
for k, a0 in enumerate(trail_angles):
    a1 = trail_angles[(k + 1) % len(trail_angles)] + (2 * math.pi if k == len(trail_angles) - 1 else 0)
    gap = a1 - a0
    n = max(1, round(gap / (2 * math.pi / 8)))
    for q in range(n):
        a = a0 + gap * (q + 1) / (n + 1)
        obelisks.append((hc[0] + 10.6 * math.cos(a), hc[1] + 10.6 * math.sin(a)))
for si, sj in obelisks:
    land.taken |= {(int(si) + a, int(sj) + 1 + b) for a in (-1, 0, 1) for b in (-1, 0, 1)}
ne = land.areas["north_e"]["c"]
land.taken |= {(int(ne[0]) + a, int(ne[1]) + 1 + b) for a in (-2, -1, 0, 1, 2) for b in (-2, -1, 0, 1, 2)}

# ---- 5. the land grows around everything placed; the mine cliff and its mouth -------------------------------
land.clear_walls(m)
land.carve(margin=4.6)
mine.cut()
land.assign_regions()
gate = land.areas["gate"]["c"]
open_ground = {(int(gate[0]) + a, int(gate[1]) + b) for a in range(-5, 6) for b in range(-5, 6)} | set(cross["corridor"])
for a_ in ("p2", "p4"):                                           # room for the waystones
    c_ = land.areas[a_]["c"]
    open_ground |= {(int(c_[0]) + a, int(c_[1]) + b) for a in range(-6, 7) for b in range(-6, 7)}
thickets = {}
for name, k in (("north", 16), ("west", 16), ("south", 16), ("path", 10)):   # thickets break up the open woods
    thickets[name] = land.thickets(k, size=(1.2, 2.6), regions=(name,), avoid=open_ground)
land.apply(m, wall=lambda r: FORESTS[REGIONS.get(r, REGIONS["path"])["forest"]]["wall"],
           floor=lambda r: REGIONS.get(r, REGIONS["path"])["ground"][0])
mine.ground(m)
for s in inner: m.floor[square_tile(*s)] = "GrassDense"

# ---- 6. water: the brook and its bridge, the lily pond --------------------------------------------------------
ww = Waterworks(m, rng, inside=lambda x, y: m.floor.get((x, y), "").startswith(("Grass", "Dirt")))
brook = ww.stream(BROOK, width=2.2, wiggle=1.6, calm=[(C, 16)])
pond = ww.pond(*POND)
span = 10
a_uv, b_uv = ((C[0] - span, C[1]), (C[0] + span, C[1])) if cross["axis"] == "u" else ((C[0], C[1] + span), (C[0], C[1] - span))
ww.rope_bridge(a_uv, b_uv, kit=cross["kit"])
for b_ in ww.bodies:
    for t in b_.tiles:
        if "Water" in m.floor.get(t, ""): land.water.add(cell_square(*t))

# ---- 7. life: rooms, the trades' scenes, the crystal heart, the mine mouth -----------------------------------
land.clear_walls(m)
for bid, b in placed:
    foot = _squares_of(b.footprint)
    for d in b.entrances:
        path = land.connect_door(m, d, foot, material="DirtDark2")
        if path is None: print(f"  no path from the {bid.role}'s door")
        else: door_paths |= set(path)
land.trim_dead_ends(m, keep=door_paths)

furnished = []
for bid, b in placed:
    style = "mine" if bid.area == "camp" else "town"
    for room in b.rooms:
        objs, res = furnish_original(m, room, kind=room.kind, rng=rng, style=style)
        furnished.append((bid.role, room.kind, len(objs), res["ok"]))

vil = Village(m, rng, land)
for bid, b in placed:
    role = BUILDINGS[bid.role]
    for sc in role["scenes"]: vil.scene(b, sc)
    if bid.role == "grovelord":                                   # the herb beds, open to the wood
        gardens = [vil.garden(b, size=(4, 3), crop="Plant2Flowered", fence=None),
                   vil.garden(b, size=(3, 3), crop="FlowersPurpleSparse", fence=None)]


def light(si, sj, xfer, dz=-5):
    x, y = square_px(si, sj)
    m.obj_px("ColorLight", x, y + dz, xfer=dict(xfer))


def torch_pole(si, sj):
    s = (int(si), int(sj) + 1)
    if s not in land.squares or s in land.water or s in land.taken_strict: return False
    x, y = square_px(si, sj)
    m.obj_px("TorchPole", x, y)
    m.obj_px("ColorLight", x, y - 5, xfer=dict(ORANGE))
    land.taken.add(s)
    return True


# the giant mana crystal cluster: the three great formations at the core, a ring of medium crystals and
# crystal columns, smaller crystals around them, glowing cyan
m.obj_px("MineManaCrystal10", *square_px(hc[0], hc[1]))
for k in range(6):                                                # the mound of great crystals
    ang = k * math.pi / 3 + 0.5
    rr = 1.15 + 0.2 * (k % 2)
    m.obj_px(("MineManaCrystal11", "MineManaCrystal9", "MineManaCrystal10")[k % 3],
             *square_px(hc[0] + rr * math.cos(ang), hc[1] + rr * math.sin(ang)))
for k in range(9):                                                # medium crystals growing round it
    ang = k * 2 * math.pi / 9 + 0.2
    rr = 2.35 + 0.25 * math.sin(k * 2.1)
    m.obj_px(("MineManaCrystal1", "MineManaCrystal4", "MineManaCrystal7")[k % 3],
             *square_px(hc[0] + rr * math.cos(ang), hc[1] + rr * math.sin(ang)))
for k in range(4):                                                # four crystal columns, balanced
    ang = k * math.pi / 2 + math.pi / 4
    m.obj_px("CrystalColumn", *square_px(hc[0] + 3.3 * math.cos(ang), hc[1] + 3.3 * math.sin(ang)))
smalls = []
for _ in range(200):                                              # small crystals scattered at the foot
    if len(smalls) >= 14: break
    ang, r = rng.uniform(0, 2 * math.pi), rng.uniform(3.6, 5.2)
    si, sj = hc[0] + r * math.cos(ang), hc[1] + r * math.sin(ang)
    if all(math.hypot(si - a, sj - b) > 1.3 for a, b in smalls) and \
            all(math.hypot(si - hc[0] - 3.3 * math.cos(k * math.pi / 2 + math.pi / 4),
                           sj - hc[1] - 3.3 * math.sin(k * math.pi / 2 + math.pi / 4)) > 1.0 for k in range(4)):
        smalls.append((si, sj))
        m.obj_px(rng.choice(["MineManaCrystal2", "MineManaCrystal3", "MineManaCrystal5", "MineManaCrystal6", "MineManaCrystal8"]),
                 *square_px(si, sj))
for k in range(4):                                                # the glow, balanced round the mound
    ang = k * math.pi / 2
    light(hc[0] + 1.8 * math.cos(ang), hc[1] + 1.8 * math.sin(ang), CYAN)
for si, sj in obelisks:                                           # the standing stones, softly blue
    m.obj_px("ObeliskPrimitive", *square_px(si, sj))
    light(si, sj, BLUE)

# the grove itself: a ring of silver trees round the standing stones, open where the trails come in
grove_trees = 0
for k in range(72):
    a = k * 2 * math.pi / 72
    if any(abs((a - t + math.pi) % (2 * math.pi) - math.pi) < 0.42 for t in trail_angles): continue
    if k % 2: continue
    rr = 15.0 + 0.8 * math.sin(k * 1.7)
    si, sj = hc[0] + rr * math.cos(a), hc[1] + rr * math.sin(a)
    s = (int(si), int(sj) + 1)
    if s not in land.squares or s in land.roads or s in land.taken or s in land.water: continue
    m.obj_px(("TreeGreen2", "TreeGreen3", "TreeGreen2", "TreeGreen1")[(k // 2) % 4], *square_px(si, sj))
    land.taken.add(s)
    grove_trees += 1

# waystones along the winding path, softly lit, beside the road
waystones = []
for a_ in ("p2", "p4"):
    c_ = land.areas[a_]["c"]
    spot = min((s for s in land.squares if s not in land.roads and s not in land.taken
                and 2 <= math.hypot(s[0] + 0.5 - c_[0], s[1] - 0.5 - c_[1]) <= 4), default=None,
               key=lambda s: math.hypot(s[0] + 0.5 - c_[0], s[1] - 0.5 - c_[1]))
    if spot:
        m.obj_px("ObeliskPrimitive", *square_px(spot[0] + 0.5, spot[1] - 0.5))
        light(spot[0] + 0.5, spot[1] - 0.5, BLUE)
        land.taken.add(spot)
        waystones.append(spot)

# the fairy ring of mushrooms in the mossy glade
for k in range(11):
    ang = k * 2 * math.pi / 11
    m.obj_px("Mushroom3" if k % 3 else "Mushroom4", *square_px(ne[0] + 1.5 * math.cos(ang), ne[1] + 1.5 * math.sin(ang)))

# the mine: its portal and timber sets, the cave-in that closes it, the glow and creaking beyond;
# outside, torches flanking the mouth, a loaded cart on the track, the winch, tools left about
mine.dress(m, light=light, torch=torch_pole, glow=CYAN)

# the miners' campfire at the heart of the yard, a bench on each side facing it
yi = sum(i for i, _ in land.plaza) / len(land.plaza) + 0.5
yj = sum(j for _, j in land.plaza) / len(land.plaza) - 0.5
m.obj_px("CampFire", *square_px(yi, yj))
light(yi, yj, ORANGE)
for (du, dv), face in (((-1, 0), "+u"), ((1, 0), "-u"), ((0, -1), "+v"), ((0, 1), "-v")):
    m.obj_px(Village.BENCH_FACING[face], *square_px(yi + 1.9 * du, yj + 1.9 * dv))
land.taken |= {(int(yi) + a, int(yj) + 1 + b) for a in (-2, -1, 0, 1, 2) for b in (-2, -1, 0, 1, 2)}

# torch poles at the yard's four corners (balanced), two flanking the grovelord's door
pi0, pi1 = min(i for i, _ in land.plaza), max(i for i, _ in land.plaza)
pj0, pj1 = min(j for _, j in land.plaza), max(j for _, j in land.plaza)
for si, sj in ((pi0 - 0.6, pj0 - 0.6), (pi1 + 1.6, pj0 - 0.6), (pi0 - 0.6, pj1 + 0.6), (pi1 + 1.6, pj1 + 0.6)):
    torch_pole(si, sj)
for bid, b in placed:
    if bid.role != "grovelord" or not b.entrances: continue
    d0 = b.entrances[0]
    halves = [d for d in b.entrances if abs(d.px[0] - d0.px[0]) + abs(d.px[1] - d0.px[1]) <= 100]
    (si, sj), (oi, oj), (ai, aj) = door_frame(halves, _squares_of(b.footprint))
    for gap_ in (2.2, 1.8, 2.8):                                  # a pair, symmetric about the door, or none
        spots = [(si + oi * 0.8 + ai * gap_ * side, sj + oj * 0.8 + aj * gap_ * side) for side in (1, -1)]
        sq_ = [(int(math.floor(a)), int(math.floor(b_)) + 1) for a, b_ in spots]
        if all(q in land.squares and q not in land.taken_strict and q not in land.water for q in sq_):
            for a, b_ in spots: torch_pole(a, b_)
            break

# ---- 8. ground patches, vegetation by section, props spread from where they belong, water's finish ----------
for name, r in REGIONS.items():
    base, sparse, dense = r["ground"]
    land.ground_variety(m, base=base, sparse=sparse, dense=dense, clear=3, region=name)
keep = {(int(gate[0]) + a, int(gate[1]) + b) for a in range(-3, 4) for b in range(-3, 4)} | inner | ring
for w_ in waystones:                                              # the waystones stand in the open
    keep |= {(w_[0] + a, w_[1] + b) for a in range(-3, 4) for b in range(-3, 4)}
for bid, b in placed:
    for d in b.entrances:
        di, dj = px_square(*d.px)
        keep |= {(di + a, dj + b2) for a in range(-2, 3) for b2 in range(-2, 3)}
for c in list(ww.no_walls): land.taken.add(cell_square(*c))
forest_of = lambda s: REGIONS.get(land.region_of(s), REGIONS["path"])["forest"]
planter = Planter(m, rng, land, keep_clear=keep, forest_of=forest_of, settled=("camp", "grovelord", "heart"))
n_trees, n_small = planter.plant_all(groves=7, flowers=10, birds=14)
band = [s for s in land.squares if RING_IN - 2.5 <= math.hypot(s[0] + 0.5 - hc[0], s[1] - 0.5 - hc[1]) <= RING_IN - 0.8]
planter.flower_patches(8, size=(4, 7), near=band)                 # flower beds inside the crystal circle

free = lambda s: s not in land.taken and s not in land.roads and s not in land.water and s not in keep
shack = next((b for bid, b in placed if bid.role == "grovelord"), None)
if shack:                                                         # firewood cut around the grovelord's clearing
    src = list(_squares_of(shack.footprint))
    scatter(m, rng, land, {"Stump1": 2, "Stump2": 2, "Stump3": 1, "Stump4": 1}, src, 7, reach=16, min_gap=4, ok=free)
woods = [s for s in land.squares if land.region_of(s) in ("north", "west", "south", "path") and planter.edge.get(s, 9) <= 3]
scatter(m, rng, land, {"ForestLog01": 1, "ForestLog02": 1, "ForestLog03": 1, "ForestLog04": 1}, woods, 12,
        reach=2, min_gap=14, ok=free)                             # fallen logs here and there along the woods' edges
pines = [s for s in land.squares if land.region_of(s) in ("south", "camp") and planter.edge.get(s, 9) <= 3]
scatter(m, rng, land, {"CaveRocksLarge": 1, "CaveRocksMedium": 2, "CaveRocksSmall": 2, "CaveBoulders": 1}, pines, 16,
        reach=2, min_gap=8, ok=free)                              # rocks along the pine wood and the camp's edges
heart_src = list(inner)
scatter(m, rng, land, {"MineCrystal01": 2, "MineCrystal02": 2, "MineCrystal03": 2, "MineCrystalUp01": 1}, heart_src, 10,
        reach=12, min_gap=4, ok=free)                             # crystal shards spreading out from the heart
east = [s for s in land.roads if land.region_of(s) == "path"]
scatter(m, rng, land, {"MineCrystal04": 1, "MineCrystal05": 2, "MineCrystalUp03": 1}, east, 8, reach=3, min_gap=12,
        ok=free)                                                  # and glinting along the path to the mine
ww.finish()

m.obj_px("PlayerStart", *square_px(gate[0], gate[1]))
xs = [square_px(s[0], s[1]) for s in land.squares]
m.polygon("TreePlace:Forest", tuple(m.d["ambient"]), [(min(x for x, _ in xs) - 40, min(y for _, y in xs) - 40),
                                                    (max(x for x, _ in xs) + 40, min(y for _, y in xs) - 40),
                                                    (max(x for x, _ in xs) + 40, max(y for _, y in xs) + 40),
                                                    (min(x for x, _ in xs) - 40, max(y for _, y in xs) + 40)])

if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] != "-" else os.path.join(HERE, "..", "out")
    lines = m.build(os.path.abspath(out))
    print("\n".join(l for l in lines if not l.startswith("XFER")))
    print(ID.describe())
    print(f"land {len(land.squares)} tiles | buildings {len(placed)}/{len(ID.buildings)} | trees {n_trees} | plants {n_small}"
          f" | herb beds {sum(map(bool, gardens))} | grove trees {grove_trees} | thickets "
          + ", ".join(f"{k} {len(v)}" for k, v in thickets.items()))
    for f in furnished: print("  ", *f)
