"""The scene lab's generator: N variants of one exterior scene type on a template outdoor map, each laid by the kit's
real placement code (kit/camps.py, kit/posts.py, kit/yards.py, kit/village.py, kit/water.py, kit/dressing.py and its
catalogue kit/scenes.py), in its own clearing of the map.

The template: ten clearings on a grid (Land areas joined by forest paths), the forest wall round them, the ground
grass with Westwood's variety patches, planted by the kit's Planter (the user: "Tree and foliage placement is good"),
each clearing in its own forest (deciduous, conifer, oak, aspen, pine, dusk, ancient).

Each variant varies, on a fixed schedule so a batch covers the range:
- size: small, typical, large (the clearing's radius and the scene's counts: a camp's sleepers and tents, a yard's
  plot, a pond's radius);
- site: an open glade, against a wall (the forest's edge, or the house a garden belongs to), by a road (a dirt road
  along one side of the clearing, the scene open toward it), on a shore (a pond on one side);
- seed: every variant its own, from (scene, seed, variant) by crc32.

    from labgen import generate
    batch = generate("bandit_camp", n=10, seed=1, out_dir=..., name="S1a2b3c")   # -> dict(maps, variants)

Builds are reproducible: the same scene, n and seed give the same map.
"""
import json, math, os, random
import labenv as E
from nox import Spec, SOLO
from kit.layout import Land, square_px, px_square, square_tile, tile_square
from kit.vegetation import Planter, FORESTS, TOWN_PLANTING

SCHEDULE = [("typical", "glade"), ("small", "road"), ("large", "glade"), ("typical", "wall"), ("small", "glade"),
            ("large", "road"), ("typical", "shore"), ("large", "wall"), ("small", "shore"), ("typical", "road")]
RADIUS = {"small": 8, "typical": 10, "large": 12}            # the clearing's radius, squares
# A hideout's pocket in the rock (Westwood's camps: half of them are CaveWall2 pockets on DirtDark2 off a cave's passage,
# Wiz03a, Wiz03b, Wiz03c, War03a): a smaller, rougher clearing walled with rock, its one mouth on the passage
CAVE_R = {"small": 4.0, "typical": 4.5, "large": 5.5}
CAVE = dict(wall="CaveWall2", floor="DirtDark2")
# The setting (the independent blind judge, 2026-10-05: "the biggest tell is the lab's setting: ours stand alone in an
# empty forest glade, Westwood's sit in towns, among other yards, walls, paved walks, houses"). A town scene's
# clearing is a hamlet's ground: a road through it, two or three houses round the scene with their walks to the road;
# the glade is kept for the scenes that belong in the wild.
WILD = {"bandit_camp", "ogre_camp", "urchin_camp", "wolf_den", "quarry", "shrine"}
TOWN_RADIUS = {"small": 12, "typical": 14, "large": 15}
TOWN_COLS = [54, 90, 126, 162, 198]                          # 36 squares apart: a hamlet's ground and its wood
TOWN_ROWS = [-18, 18]
CONTEXT_ROLES = ("home", "cottage", "home", "store", "fisher", "cottage", "inn")
FOREST_TURN = ["deciduous", "conifer", "oak", "aspen", "pine", "dusk", "ancient"]
COLS = [64, 96, 128, 160, 192]
ROWS = [-34, 34]
DIRS = [(1, 0), (0, 1), (-1, 0), (0, -1), (0.7071, 0.7071), (-0.7071, 0.7071), (0.7071, -0.7071), (-0.7071, -0.7071)]


def _unit(d):
    L = math.hypot(*d) or 1
    return d[0] / L, d[1] / L


class Plot:
    """One variant's clearing: centre (squares), radius, site, size, forest, the way in, the road, the pond."""
    def __init__(self, k, centre, size, site, forest, rng):
        self.k, self.c, self.size, self.site, self.forest, self.rng = k, centre, size, site, forest, rng
        self.r = RADIUS[size]
        self.town = False
        self.cave = False
        self.dir = _unit(rng.choice(DIRS))                  # the side the road, the shore or the wall is on
        self.road = None                                    # (a, b) road end points, squares
        self.pond = None                                    # (centre squares, radius tiles)
        self.scene_c = centre                               # where the scene's middle goes
        self.toward = (centre[0] + self.dir[0] * self.r, centre[1] + self.dir[1] * self.r)
        self.notes = {}

    @property
    def name(self):
        return f"p{self.k}"


def new_spec(name, scene):
    m = Spec(name, summary=f"Scene lab: {scene}", description=f"Scene lab variants of the {scene} scene. Generated by "
             f"Claude.", author="vdystopia (generated by Claude)", version="1", date="2026", type=SOLO, minPlayers=1,
             maxPlayers=1)
    m.d["nxz"] = False
    m.d["ambient"] = [150, 146, 120]
    m.loot = False
    return m


def plan_plots(scene, n, seed, rng):
    plots = []
    town = scene not in WILD
    cols, rows = (TOWN_COLS, TOWN_ROWS) if town else (COLS, ROWS)
    for k in range(n):
        size, site = SCHEDULE[k % len(SCHEDULE)]
        if town and site == "glade": site = "road"            # a hamlet's ground has its road
        prng = random.Random(E.seed_of("scenelab", scene, seed, k))
        c = (cols[k % len(cols)] + 0.5, rows[(k // len(cols)) % len(rows)] - 0.5)
        forest = FOREST_TURN[(k + seed) % len(FOREST_TURN)]
        p = Plot(k, c, size, site, forest, prng)
        if town:
            p.town, p.r = True, TOWN_RADIUS[size]
            p.toward = (c[0] + p.dir[0] * p.r, c[1] + p.dir[1] * p.r)
        elif k % len(SCHEDULE) in recipe_caves(scene):
            # a hideout: a pocket in the rock, its mouth on the passage toward the middle of the map (the spine)
            p.cave, p.site, p.forest, p.r = True, "cave", "cave", CAVE_R[size]
            p.dir = (0.0, -1.0 if c[1] > 0 else 1.0)
            p.toward = (c[0], c[1] + p.dir[1] * (p.r + 2))
        plots.append(p)
    return plots


def recipe_caves(scene):
    import recipes
    return recipes.RECIPES[scene].get("caves", ())


def plan_context(ctx):
    """A town scene's neighbours, after the scene has planned its own ground: two or three houses round the clearing,
    away from the scene's middle (kit/building.generate_building, furnished as a map's are), each to be joined to the
    road by its walk (build_context)."""
    import recipes
    for p in ctx["plots"]:
        if not p.town: continue
        sx, sy = p.notes.get("scene_sq") or p.scene_c
        got = 0
        if ctx["scene"] == "pond_dock" and p.pond:
            # the fisher's hut on the bank beside his dock's landing (Con03A: the hut a few steps from the dock's root)
            (pci, pcj), pr = p.pond
            ux, uy = p.toward[0] - pci, p.toward[1] - pcj
            L = math.hypot(ux, uy) or 1
            ux, uy = ux / L, uy / L
            for sd in (1, -1):
                at = (pci + ux * (pr + 3.5) - uy * sd * 4.5, pcj + uy * (pr + 3.5) + ux * sd * 4.5)
                h = recipes._house(ctx, p, "fisher", at, quiet=True)
                if h:
                    got += 1
                    ctx.setdefault("context_houses", []).append(h)
                    break
        base = math.atan2(sy - p.c[1], sx - p.c[0]) if (sx, sy) != tuple(p.c) else math.atan2(-p.dir[1], -p.dir[0])
        for q in range(8):
            if got >= 2 + (p.size == "large"): break
            a = base + math.pi + (q // 2 + 1) * 0.55 * (1 if q % 2 else -1) - 0.55
            R = p.r - 5.0
            at = (p.c[0] + R * math.cos(a), p.c[1] + R * math.sin(a))
            if math.hypot(at[0] - sx, at[1] - sy) < 7: continue
            role = CONTEXT_ROLES[(p.k + q) % len(CONTEXT_ROLES)]
            h = recipes._house(ctx, p, role, at, quiet=True)
            if h:
                got += 1
                ctx.setdefault("context_houses", []).append(h)


def build_context(ctx):
    """The context houses' walks to the road."""
    from kit.village import _squares_of
    m, land = ctx["m"], ctx["land"]
    if ctx.get("context_houses"): land.clear_walls(m)
    done = ctx.setdefault("connected", set())
    for bid, b in ctx.get("context_houses", []):
        if id(b) in done: continue
        done.add(id(b))
        for d in b.entrances: land.connect_door(m, d, _squares_of(b.footprint))


def lay_land(m, rng, plots, recipe):
    """The template's land: the clearings, the paths joining them, each site's road or pond. Returns the Land (not yet
    carved: the recipe's planning goes first)."""
    land = Land(rng, u_range=(40, 470), v_range=(-205, 205))
    for p in plots:
        land.area(p.name, (2 * p.c[0], 2 * p.c[1]), 2 * p.r, roughness=0.3 if p.cave else 0.18, region=p.name)
    if any(p.cave for p in plots):
        # a spine of forest path between the rows, each clearing on its own spur off it: a hideout's pocket has one
        # mouth, as Westwood's have (a pocket off a cave's passage)
        cols = sorted({p.c[0] for p in plots})
        for q, x in enumerate(cols):
            land.area(f"spine{q}", (2 * x, 0.0), 6, roughness=0.1, region="spine")
            if q: land.link(f"spine{q - 1}", f"spine{q}", 8, bend=0.05, road=False, pockets=(0, 0))
        for p in plots:
            land.link(p.name, f"spine{cols.index(p.c[0])}", 6 if p.cave else 8, bend=0.08, road=False, pockets=(0, 0))
    else:
        # forest paths join the clearings in each row, and the rows at their west ends
        for a, b in zip(plots, plots[1:]):
            if (a.k // len(COLS)) == (b.k // len(COLS)) or (b.k % len(COLS) == 0):
                if b.k % len(COLS) == 0: a = plots[b.k - len(COLS)]
                land.link(a.name, b.name, 8, bend=0.15, road=False, pockets=(0, 0))
    for p in plots:
        ux, uy = p.dir
        tx, ty = -uy, ux
        if p.cave: continue
        if p.site == "road":
            off = p.r - 3.0
            a = (p.c[0] + ux * off - tx * (p.r + 3), p.c[1] + uy * off - ty * (p.r + 3))
            b = (p.c[0] + ux * off + tx * (p.r + 3), p.c[1] + uy * off + ty * (p.r + 3))
            land.area(p.name + "ra", (2 * a[0], 2 * a[1]), 6, region=p.name)
            land.area(p.name + "rb", (2 * b[0], 2 * b[1]), 6, region=p.name)
            land.link(p.name + "ra", p.name + "rb", 10, bend=0.04, road=True, pockets=(0, 0))
            p.road = (a, b)
            p.toward = (p.c[0] + ux * off, p.c[1] + uy * off)
            if p.town and recipe.get("by_road"):
                # the scene by its road, its gate or its front a few squares off it: the road in the picture, as
                # Westwood's town scenes stand on their streets (the blind judge, 2026-10-06: "standing alone on open
                # grass ... no road to the gate")
                p.scene_c = (p.toward[0] - ux * recipe["by_road"], p.toward[1] - uy * recipe["by_road"])
        elif p.site == "shore" and not recipe.get("pond"):
            pr = 3.5 if p.size == "small" else 4.5
            pc = (p.c[0] + ux * (p.r - 1.5), p.c[1] + uy * (p.r - 1.5))
            land.area(p.name + "w", (2 * pc[0], 2 * pc[1]), 2 * (pr + 3), region=p.name)
            p.pond = (pc, pr)
            land.reserve_band([(2 * pc[0], 2 * pc[1]), (2 * pc[0] + 0.1, 2 * pc[1])], pr + 1.5)
            p.toward = (p.c[0] - ux * p.r, p.c[1] - uy * p.r)          # the way in from the land side
        elif p.site == "wall":
            p.scene_c = (p.c[0] + ux * (p.r - 6.5), p.c[1] + uy * (p.r - 6.5))
            p.toward = (p.c[0] - ux * p.r, p.c[1] - uy * p.r)
    return land


def carve_apply(m, land, plots):
    land.carve(margin=3.0)
    land.assign_regions()
    by = {p.name: p for p in plots}
    cave = lambda r: r in by and by[r].cave
    land.apply(m, wall=lambda r: CAVE["wall"] if cave(r) else FORESTS[by[r].forest if r in by else "deciduous"]["wall"],
               floor=lambda r: CAVE["floor"] if cave(r) else "GrassNorm")


def lay_ponds(m, rng, land, plots, ww=None):
    """Each shore site's pond (kit/water.Waterworks), its squares joined to land.water."""
    from kit.water import Waterworks
    ww = ww or Waterworks(m, rng, inside=lambda x, y: tile_square(x, y) in land.squares)
    for p in plots:
        if not p.pond: continue
        (ci, cj), pr = p.pond
        body = ww.pond((2 * ci + 1, 2 * cj + 1), radius=pr, roughness=0.25)
        land.water |= {tile_square(*t) for t in body.tiles}
        p.notes["body"] = body
    return ww


def plant(m, rng, land, plots, keep=()):
    by = {p.name: p for p in plots}
    rock = {s for s in land.squares if land.region_of(s) in by and by[land.region_of(s)].cave}     # no tree in the rock
    planter = Planter(m, rng, land, "deciduous", keep_clear=set(keep) | rock,
                      forest_of=lambda s: by[land.region_of(s)].forest if land.region_of(s) in by and
                      not by[land.region_of(s)].cave else "deciduous",
                      settled=tuple(p.name for p in plots))
    planter.plant_all(groves=0, profile=TOWN_PLANTING)


def generate(scene, n=10, seed=1, out_dir=None, name="SceneLab", log=print):
    """Builds the batch's map. Returns dict(maps=[path], variants=[dict(index, size, site, forest, anchor (px), reach
    (px), plot centre, notes)])."""
    import recipes
    rec = recipes.RECIPES[scene]
    rng = random.Random(E.seed_of("scenelab-map", scene, seed))
    os.makedirs(out_dir, exist_ok=True)
    m = new_spec(name, scene)
    plots = plan_plots(scene, n, seed, rng)
    land = lay_land(m, rng, plots, rec)
    land.blends(m)
    land.paint_roads(m, "DirtDark2", width_squares=2.4, skip=land.reserved)
    ctx = dict(m=m, rng=rng, land=land, plots=plots, scene=scene, seed=seed, log=log)
    rec["plan"](ctx)                                   # before the carve: yards, buildings, ponds the scene is round
    plan_context(ctx)                                  # a town scene's neighbours
    carve_apply(m, land, plots)
    if any(p.pond for p in plots): ctx["ww"] = lay_ponds(m, rng, land, plots)
    for p in plots:
        if p.town and p.road and p.k % 3 == 1:
            for sq in land.roads:
                if land.region_of(sq) == p.name: m.floor[square_tile(*sq)] = "RoughCobble"
    land.ground_variety(m, clear=3)
    rec["build"](ctx)                                  # after the walls: the scene's own code
    build_context(ctx)
    if ctx.get("ww"): ctx["ww"].finish()
    plant(m, rng, land, plots, set(ctx.get("keep", ())))
    if rec.get("after_plant"): rec["after_plant"](ctx)  # the catalogue's scenes are dressed last, as in a map
    m.obj_px("PlayerStart", *square_px(plots[0].c[0], plots[0].c[1] - plots[0].r + 2))
    if ctx.get("pop"): m.scripts.update(ctx["pop"].behaviours.files(m.d["name"]))
    lines = m.build(out_dir, check=False)
    bad = [l for l in lines if l.startswith("ERROR")]
    if bad: log("\n".join(bad[:10]))
    variants = []
    for p in plots:
        v = dict(index=p.k + 1, size=p.size, site=p.site, forest=p.forest, plot=[round(p.c[0], 1), round(p.c[1], 1)],
                 reach=round(p.r * 32.5 + 60), map=name, **{k: v for k, v in p.notes.items() if k != "body"})
        if "anchor" not in v:
            v["anchor"] = list(square_px(*p.scene_c))
        variants.append(v)
    return dict(maps=[os.path.join(out_dir, name + ".map")], variants=variants)
